/* Generated by Yosys 0.9 (git sha1 UNKNOWN, gcc 10.2.0 -march=x86-64 -mtune=generic -O2 -fno-plt -fPIC -Os) */

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "./final_logic_synth/D0_fifo_synth.v:1" *)
module D0_fifo_synth(clk, reset_L, wr_enable, rd_enable, data_in, full_fifo_D0, empty_fifo_D0, almost_full_fifo_D0, almost_empty_fifo_D0, error_D0_synth, data_out_D0_synth);
  (* src = "./final_logic_synth/D0_fifo_synth.v:61" *)
  wire [2:0] _000_;
  (* src = "./final_logic_synth/D0_fifo_synth.v:46" *)
  wire [5:0] _001_;
  (* src = "./final_logic_synth/D0_fifo_synth.v:46" *)
  wire [1:0] _002_;
  (* src = "./final_logic_synth/D0_fifo_synth.v:30" *)
  wire [1:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  (* src = "./final_logic_synth/D0_fifo_synth.v:11" *)
  output almost_empty_fifo_D0;
  (* src = "./final_logic_synth/D0_fifo_synth.v:10" *)
  output almost_full_fifo_D0;
  (* src = "./final_logic_synth/D0_fifo_synth.v:6" *)
  input clk;
  (* src = "./final_logic_synth/D0_fifo_synth.v:20" *)
  wire [2:0] cnt;
  (* src = "./final_logic_synth/D0_fifo_synth.v:7" *)
  input [5:0] data_in;
  (* src = "./final_logic_synth/D0_fifo_synth.v:13" *)
  output [5:0] data_out_D0_synth;
  (* src = "./final_logic_synth/D0_fifo_synth.v:9" *)
  output empty_fifo_D0;
  (* src = "./final_logic_synth/D0_fifo_synth.v:12" *)
  output error_D0_synth;
  (* src = "./final_logic_synth/D0_fifo_synth.v:8" *)
  output full_fifo_D0;
  (* src = "./final_logic_synth/D0_fifo_synth.v:28" *)
  wire [31:0] i;
  wire [5:0] \mem[0] ;
  wire [5:0] \mem[1] ;
  wire [5:0] \mem[2] ;
  wire [5:0] \mem[3] ;
  (* src = "./final_logic_synth/D0_fifo_synth.v:6" *)
  input rd_enable;
  (* src = "./final_logic_synth/D0_fifo_synth.v:19" *)
  wire [1:0] rd_ptr;
  (* src = "./final_logic_synth/D0_fifo_synth.v:6" *)
  input reset_L;
  (* src = "./final_logic_synth/D0_fifo_synth.v:6" *)
  input wr_enable;
  (* src = "./final_logic_synth/D0_fifo_synth.v:18" *)
  wire [1:0] wr_ptr;
  NOT _260_ (
    .A(cnt[2]),
    .Y(_243_)
  );
  NOT _261_ (
    .A(rd_enable),
    .Y(_244_)
  );
  NOT _262_ (
    .A(wr_enable),
    .Y(_245_)
  );
  NOT _263_ (
    .A(cnt[1]),
    .Y(_246_)
  );
  NOT _264_ (
    .A(reset_L),
    .Y(_247_)
  );
  NOT _265_ (
    .A(rd_ptr[1]),
    .Y(_248_)
  );
  NOT _266_ (
    .A(\mem[3] [0]),
    .Y(_249_)
  );
  NOT _267_ (
    .A(\mem[3] [1]),
    .Y(_250_)
  );
  NOT _268_ (
    .A(\mem[3] [2]),
    .Y(_251_)
  );
  NOT _269_ (
    .A(\mem[3] [3]),
    .Y(_252_)
  );
  NOT _270_ (
    .A(\mem[3] [4]),
    .Y(_253_)
  );
  NOT _271_ (
    .A(\mem[3] [5]),
    .Y(_254_)
  );
  NOT _272_ (
    .A(wr_ptr[1]),
    .Y(_255_)
  );
  NOT _273_ (
    .A(data_in[0]),
    .Y(_256_)
  );
  NOT _274_ (
    .A(data_in[1]),
    .Y(_257_)
  );
  NOT _275_ (
    .A(data_in[2]),
    .Y(_258_)
  );
  NOT _276_ (
    .A(data_in[3]),
    .Y(_259_)
  );
  NOT _277_ (
    .A(data_in[4]),
    .Y(_028_)
  );
  NOT _278_ (
    .A(data_in[5]),
    .Y(_029_)
  );
  NOT _279_ (
    .A(\mem[0] [0]),
    .Y(_030_)
  );
  NOT _280_ (
    .A(\mem[0] [1]),
    .Y(_031_)
  );
  NOT _281_ (
    .A(\mem[0] [2]),
    .Y(_032_)
  );
  NOT _282_ (
    .A(\mem[0] [3]),
    .Y(_033_)
  );
  NOT _283_ (
    .A(\mem[0] [4]),
    .Y(_034_)
  );
  NOT _284_ (
    .A(\mem[0] [5]),
    .Y(_035_)
  );
  NAND _285_ (
    .A(_243_),
    .B(cnt[0]),
    .Y(_036_)
  );
  NOR _286_ (
    .A(cnt[1]),
    .B(_036_),
    .Y(almost_empty_fifo_D0)
  );
  NAND _287_ (
    .A(cnt[0]),
    .B(cnt[1]),
    .Y(_037_)
  );
  NOT _288_ (
    .A(_037_),
    .Y(_038_)
  );
  NOR _289_ (
    .A(cnt[2]),
    .B(_037_),
    .Y(almost_full_fifo_D0)
  );
  NOR _290_ (
    .A(cnt[0]),
    .B(cnt[1]),
    .Y(_039_)
  );
  NOT _291_ (
    .A(_039_),
    .Y(_040_)
  );
  NAND _292_ (
    .A(cnt[2]),
    .B(_039_),
    .Y(_041_)
  );
  NOT _293_ (
    .A(_041_),
    .Y(full_fifo_D0)
  );
  NOR _294_ (
    .A(cnt[2]),
    .B(_040_),
    .Y(empty_fifo_D0)
  );
  NAND _295_ (
    .A(wr_enable),
    .B(wr_ptr[0]),
    .Y(_042_)
  );
  NOT _296_ (
    .A(_042_),
    .Y(_043_)
  );
  NAND _297_ (
    .A(reset_L),
    .B(_042_),
    .Y(_044_)
  );
  NOT _298_ (
    .A(_044_),
    .Y(_045_)
  );
  NAND _299_ (
    .A(reset_L),
    .B(_255_),
    .Y(_046_)
  );
  NOT _300_ (
    .A(_046_),
    .Y(_047_)
  );
  NOR _301_ (
    .A(_045_),
    .B(_047_),
    .Y(_048_)
  );
  NAND _302_ (
    .A(_044_),
    .B(_046_),
    .Y(_049_)
  );
  NAND _303_ (
    .A(wr_enable),
    .B(reset_L),
    .Y(_050_)
  );
  NOR _304_ (
    .A(_256_),
    .B(_050_),
    .Y(_051_)
  );
  NAND _305_ (
    .A(_048_),
    .B(_051_),
    .Y(_052_)
  );
  NAND _306_ (
    .A(\mem[3] [0]),
    .B(_049_),
    .Y(_053_)
  );
  NAND _307_ (
    .A(_052_),
    .B(_053_),
    .Y(_022_)
  );
  NOR _308_ (
    .A(_257_),
    .B(_050_),
    .Y(_054_)
  );
  NAND _309_ (
    .A(_048_),
    .B(_054_),
    .Y(_055_)
  );
  NAND _310_ (
    .A(\mem[3] [1]),
    .B(_049_),
    .Y(_056_)
  );
  NAND _311_ (
    .A(_055_),
    .B(_056_),
    .Y(_023_)
  );
  NOR _312_ (
    .A(_258_),
    .B(_050_),
    .Y(_057_)
  );
  NAND _313_ (
    .A(_048_),
    .B(_057_),
    .Y(_058_)
  );
  NAND _314_ (
    .A(\mem[3] [2]),
    .B(_049_),
    .Y(_059_)
  );
  NAND _315_ (
    .A(_058_),
    .B(_059_),
    .Y(_024_)
  );
  NOR _316_ (
    .A(_259_),
    .B(_050_),
    .Y(_060_)
  );
  NAND _317_ (
    .A(_048_),
    .B(_060_),
    .Y(_061_)
  );
  NAND _318_ (
    .A(\mem[3] [3]),
    .B(_049_),
    .Y(_062_)
  );
  NAND _319_ (
    .A(_061_),
    .B(_062_),
    .Y(_025_)
  );
  NOR _320_ (
    .A(_028_),
    .B(_050_),
    .Y(_063_)
  );
  NAND _321_ (
    .A(_048_),
    .B(_063_),
    .Y(_064_)
  );
  NAND _322_ (
    .A(\mem[3] [4]),
    .B(_049_),
    .Y(_065_)
  );
  NAND _323_ (
    .A(_064_),
    .B(_065_),
    .Y(_026_)
  );
  NOR _324_ (
    .A(_029_),
    .B(_050_),
    .Y(_066_)
  );
  NAND _325_ (
    .A(_048_),
    .B(_066_),
    .Y(_067_)
  );
  NAND _326_ (
    .A(\mem[3] [5]),
    .B(_049_),
    .Y(_068_)
  );
  NAND _327_ (
    .A(_067_),
    .B(_068_),
    .Y(_027_)
  );
  NOR _328_ (
    .A(rd_enable),
    .B(_245_),
    .Y(_069_)
  );
  NAND _329_ (
    .A(_244_),
    .B(wr_enable),
    .Y(_070_)
  );
  NOR _330_ (
    .A(_244_),
    .B(wr_enable),
    .Y(_071_)
  );
  NAND _331_ (
    .A(rd_enable),
    .B(_245_),
    .Y(_072_)
  );
  NAND _332_ (
    .A(_070_),
    .B(_072_),
    .Y(_073_)
  );
  NAND _333_ (
    .A(cnt[0]),
    .B(_073_),
    .Y(_074_)
  );
  NOT _334_ (
    .A(_074_),
    .Y(_075_)
  );
  NOR _335_ (
    .A(cnt[0]),
    .B(_073_),
    .Y(_076_)
  );
  NOT _336_ (
    .A(_076_),
    .Y(_077_)
  );
  NAND _337_ (
    .A(reset_L),
    .B(_077_),
    .Y(_078_)
  );
  NOR _338_ (
    .A(_075_),
    .B(_078_),
    .Y(_000_[0])
  );
  NOR _339_ (
    .A(_246_),
    .B(_073_),
    .Y(_079_)
  );
  NOR _340_ (
    .A(_038_),
    .B(_039_),
    .Y(_080_)
  );
  NAND _341_ (
    .A(_037_),
    .B(_040_),
    .Y(_081_)
  );
  NOR _342_ (
    .A(_069_),
    .B(_081_),
    .Y(_082_)
  );
  NOR _343_ (
    .A(_071_),
    .B(_080_),
    .Y(_083_)
  );
  NOR _344_ (
    .A(_082_),
    .B(_083_),
    .Y(_084_)
  );
  NOR _345_ (
    .A(_079_),
    .B(_084_),
    .Y(_085_)
  );
  NOR _346_ (
    .A(_247_),
    .B(_085_),
    .Y(_000_[1])
  );
  NOR _347_ (
    .A(_243_),
    .B(_039_),
    .Y(error_D0_synth)
  );
  NOR _348_ (
    .A(empty_fifo_D0),
    .B(error_D0_synth),
    .Y(_086_)
  );
  NOR _349_ (
    .A(_072_),
    .B(_086_),
    .Y(_087_)
  );
  NOR _350_ (
    .A(_037_),
    .B(_070_),
    .Y(_088_)
  );
  NAND _351_ (
    .A(_038_),
    .B(_069_),
    .Y(_089_)
  );
  NOR _352_ (
    .A(_243_),
    .B(_089_),
    .Y(_090_)
  );
  NOR _353_ (
    .A(_243_),
    .B(_071_),
    .Y(_091_)
  );
  NOR _354_ (
    .A(_088_),
    .B(_091_),
    .Y(_092_)
  );
  NOR _355_ (
    .A(_090_),
    .B(_092_),
    .Y(_093_)
  );
  NOR _356_ (
    .A(_087_),
    .B(_093_),
    .Y(_094_)
  );
  NOR _357_ (
    .A(_247_),
    .B(_094_),
    .Y(_000_[2])
  );
  NAND _358_ (
    .A(rd_enable),
    .B(rd_ptr[0]),
    .Y(_095_)
  );
  NOT _359_ (
    .A(_095_),
    .Y(_096_)
  );
  NOR _360_ (
    .A(rd_enable),
    .B(rd_ptr[0]),
    .Y(_097_)
  );
  NOT _361_ (
    .A(_097_),
    .Y(_098_)
  );
  NAND _362_ (
    .A(reset_L),
    .B(_098_),
    .Y(_099_)
  );
  NOR _363_ (
    .A(_096_),
    .B(_099_),
    .Y(_002_[0])
  );
  NOR _364_ (
    .A(_248_),
    .B(_095_),
    .Y(_100_)
  );
  NAND _365_ (
    .A(_248_),
    .B(_095_),
    .Y(_101_)
  );
  NAND _366_ (
    .A(reset_L),
    .B(_101_),
    .Y(_102_)
  );
  NOR _367_ (
    .A(_100_),
    .B(_102_),
    .Y(_002_[1])
  );
  NAND _368_ (
    .A(rd_enable),
    .B(reset_L),
    .Y(_103_)
  );
  NOR _369_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [0]),
    .Y(_104_)
  );
  NAND _370_ (
    .A(rd_ptr[0]),
    .B(_249_),
    .Y(_105_)
  );
  NAND _371_ (
    .A(rd_ptr[1]),
    .B(_105_),
    .Y(_106_)
  );
  NOR _372_ (
    .A(_104_),
    .B(_106_),
    .Y(_107_)
  );
  NAND _373_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [0]),
    .Y(_108_)
  );
  NOT _374_ (
    .A(_108_),
    .Y(_109_)
  );
  NOR _375_ (
    .A(rd_ptr[0]),
    .B(_030_),
    .Y(_110_)
  );
  NOR _376_ (
    .A(_109_),
    .B(_110_),
    .Y(_111_)
  );
  NOR _377_ (
    .A(rd_ptr[1]),
    .B(_111_),
    .Y(_112_)
  );
  NOR _378_ (
    .A(_107_),
    .B(_112_),
    .Y(_113_)
  );
  NOR _379_ (
    .A(_103_),
    .B(_113_),
    .Y(_001_[0])
  );
  NOR _380_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [1]),
    .Y(_114_)
  );
  NAND _381_ (
    .A(rd_ptr[0]),
    .B(_250_),
    .Y(_115_)
  );
  NAND _382_ (
    .A(rd_ptr[1]),
    .B(_115_),
    .Y(_116_)
  );
  NOR _383_ (
    .A(_114_),
    .B(_116_),
    .Y(_117_)
  );
  NAND _384_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [1]),
    .Y(_118_)
  );
  NOT _385_ (
    .A(_118_),
    .Y(_119_)
  );
  NOR _386_ (
    .A(rd_ptr[0]),
    .B(_031_),
    .Y(_120_)
  );
  NOR _387_ (
    .A(_119_),
    .B(_120_),
    .Y(_121_)
  );
  NOR _388_ (
    .A(rd_ptr[1]),
    .B(_121_),
    .Y(_122_)
  );
  NOR _389_ (
    .A(_117_),
    .B(_122_),
    .Y(_123_)
  );
  NOR _390_ (
    .A(_103_),
    .B(_123_),
    .Y(_001_[1])
  );
  NOR _391_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [2]),
    .Y(_124_)
  );
  NAND _392_ (
    .A(rd_ptr[0]),
    .B(_251_),
    .Y(_125_)
  );
  NAND _393_ (
    .A(rd_ptr[1]),
    .B(_125_),
    .Y(_126_)
  );
  NOR _394_ (
    .A(_124_),
    .B(_126_),
    .Y(_127_)
  );
  NAND _395_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [2]),
    .Y(_128_)
  );
  NOT _396_ (
    .A(_128_),
    .Y(_129_)
  );
  NOR _397_ (
    .A(rd_ptr[0]),
    .B(_032_),
    .Y(_130_)
  );
  NOR _398_ (
    .A(_129_),
    .B(_130_),
    .Y(_131_)
  );
  NOR _399_ (
    .A(rd_ptr[1]),
    .B(_131_),
    .Y(_132_)
  );
  NOR _400_ (
    .A(_127_),
    .B(_132_),
    .Y(_133_)
  );
  NOR _401_ (
    .A(_103_),
    .B(_133_),
    .Y(_001_[2])
  );
  NOR _402_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [3]),
    .Y(_134_)
  );
  NAND _403_ (
    .A(rd_ptr[0]),
    .B(_252_),
    .Y(_135_)
  );
  NAND _404_ (
    .A(rd_ptr[1]),
    .B(_135_),
    .Y(_136_)
  );
  NOR _405_ (
    .A(_134_),
    .B(_136_),
    .Y(_137_)
  );
  NAND _406_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [3]),
    .Y(_138_)
  );
  NOT _407_ (
    .A(_138_),
    .Y(_139_)
  );
  NOR _408_ (
    .A(rd_ptr[0]),
    .B(_033_),
    .Y(_140_)
  );
  NOR _409_ (
    .A(_139_),
    .B(_140_),
    .Y(_141_)
  );
  NOR _410_ (
    .A(rd_ptr[1]),
    .B(_141_),
    .Y(_142_)
  );
  NOR _411_ (
    .A(_137_),
    .B(_142_),
    .Y(_143_)
  );
  NOR _412_ (
    .A(_103_),
    .B(_143_),
    .Y(_001_[3])
  );
  NOR _413_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [4]),
    .Y(_144_)
  );
  NAND _414_ (
    .A(rd_ptr[0]),
    .B(_253_),
    .Y(_145_)
  );
  NAND _415_ (
    .A(rd_ptr[1]),
    .B(_145_),
    .Y(_146_)
  );
  NOR _416_ (
    .A(_144_),
    .B(_146_),
    .Y(_147_)
  );
  NAND _417_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [4]),
    .Y(_148_)
  );
  NOT _418_ (
    .A(_148_),
    .Y(_149_)
  );
  NOR _419_ (
    .A(rd_ptr[0]),
    .B(_034_),
    .Y(_150_)
  );
  NOR _420_ (
    .A(_149_),
    .B(_150_),
    .Y(_151_)
  );
  NOR _421_ (
    .A(rd_ptr[1]),
    .B(_151_),
    .Y(_152_)
  );
  NOR _422_ (
    .A(_147_),
    .B(_152_),
    .Y(_153_)
  );
  NOR _423_ (
    .A(_103_),
    .B(_153_),
    .Y(_001_[4])
  );
  NOR _424_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [5]),
    .Y(_154_)
  );
  NAND _425_ (
    .A(rd_ptr[0]),
    .B(_254_),
    .Y(_155_)
  );
  NAND _426_ (
    .A(rd_ptr[1]),
    .B(_155_),
    .Y(_156_)
  );
  NOR _427_ (
    .A(_154_),
    .B(_156_),
    .Y(_157_)
  );
  NAND _428_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [5]),
    .Y(_158_)
  );
  NOT _429_ (
    .A(_158_),
    .Y(_159_)
  );
  NOR _430_ (
    .A(rd_ptr[0]),
    .B(_035_),
    .Y(_160_)
  );
  NOR _431_ (
    .A(_159_),
    .B(_160_),
    .Y(_161_)
  );
  NOR _432_ (
    .A(rd_ptr[1]),
    .B(_161_),
    .Y(_162_)
  );
  NOR _433_ (
    .A(_157_),
    .B(_162_),
    .Y(_163_)
  );
  NOR _434_ (
    .A(_103_),
    .B(_163_),
    .Y(_001_[5])
  );
  NOR _435_ (
    .A(wr_ptr[0]),
    .B(_050_),
    .Y(_164_)
  );
  NOT _436_ (
    .A(_164_),
    .Y(_165_)
  );
  NAND _437_ (
    .A(wr_ptr[1]),
    .B(_164_),
    .Y(_166_)
  );
  NAND _438_ (
    .A(reset_L),
    .B(\mem[2] [0]),
    .Y(_167_)
  );
  NAND _439_ (
    .A(_166_),
    .B(_167_),
    .Y(_168_)
  );
  NOT _440_ (
    .A(_168_),
    .Y(_169_)
  );
  NOR _441_ (
    .A(data_in[0]),
    .B(_166_),
    .Y(_170_)
  );
  NOR _442_ (
    .A(_169_),
    .B(_170_),
    .Y(_016_)
  );
  NAND _443_ (
    .A(reset_L),
    .B(\mem[2] [1]),
    .Y(_171_)
  );
  NAND _444_ (
    .A(_166_),
    .B(_171_),
    .Y(_172_)
  );
  NOT _445_ (
    .A(_172_),
    .Y(_173_)
  );
  NOR _446_ (
    .A(data_in[1]),
    .B(_166_),
    .Y(_174_)
  );
  NOR _447_ (
    .A(_173_),
    .B(_174_),
    .Y(_017_)
  );
  NAND _448_ (
    .A(reset_L),
    .B(\mem[2] [2]),
    .Y(_175_)
  );
  NAND _449_ (
    .A(_166_),
    .B(_175_),
    .Y(_176_)
  );
  NOT _450_ (
    .A(_176_),
    .Y(_177_)
  );
  NOR _451_ (
    .A(data_in[2]),
    .B(_166_),
    .Y(_178_)
  );
  NOR _452_ (
    .A(_177_),
    .B(_178_),
    .Y(_018_)
  );
  NAND _453_ (
    .A(reset_L),
    .B(\mem[2] [3]),
    .Y(_179_)
  );
  NAND _454_ (
    .A(_166_),
    .B(_179_),
    .Y(_180_)
  );
  NOT _455_ (
    .A(_180_),
    .Y(_181_)
  );
  NOR _456_ (
    .A(data_in[3]),
    .B(_166_),
    .Y(_182_)
  );
  NOR _457_ (
    .A(_181_),
    .B(_182_),
    .Y(_019_)
  );
  NAND _458_ (
    .A(reset_L),
    .B(\mem[2] [4]),
    .Y(_183_)
  );
  NAND _459_ (
    .A(_166_),
    .B(_183_),
    .Y(_184_)
  );
  NOT _460_ (
    .A(_184_),
    .Y(_185_)
  );
  NOR _461_ (
    .A(data_in[4]),
    .B(_166_),
    .Y(_186_)
  );
  NOR _462_ (
    .A(_185_),
    .B(_186_),
    .Y(_020_)
  );
  NAND _463_ (
    .A(reset_L),
    .B(\mem[2] [5]),
    .Y(_187_)
  );
  NAND _464_ (
    .A(_166_),
    .B(_187_),
    .Y(_188_)
  );
  NOT _465_ (
    .A(_188_),
    .Y(_189_)
  );
  NOR _466_ (
    .A(data_in[5]),
    .B(_166_),
    .Y(_190_)
  );
  NOR _467_ (
    .A(_189_),
    .B(_190_),
    .Y(_021_)
  );
  NOR _468_ (
    .A(wr_enable),
    .B(wr_ptr[0]),
    .Y(_191_)
  );
  NOR _469_ (
    .A(_044_),
    .B(_191_),
    .Y(_003_[0])
  );
  NOR _470_ (
    .A(wr_ptr[1]),
    .B(_043_),
    .Y(_192_)
  );
  NOR _471_ (
    .A(_048_),
    .B(_192_),
    .Y(_003_[1])
  );
  NOR _472_ (
    .A(wr_ptr[1]),
    .B(_165_),
    .Y(_193_)
  );
  NAND _473_ (
    .A(reset_L),
    .B(\mem[0] [0]),
    .Y(_194_)
  );
  NAND _474_ (
    .A(data_in[0]),
    .B(_193_),
    .Y(_195_)
  );
  NOR _475_ (
    .A(_193_),
    .B(_194_),
    .Y(_196_)
  );
  NOT _476_ (
    .A(_196_),
    .Y(_197_)
  );
  NAND _477_ (
    .A(_195_),
    .B(_197_),
    .Y(_004_)
  );
  NAND _478_ (
    .A(reset_L),
    .B(\mem[0] [1]),
    .Y(_198_)
  );
  NAND _479_ (
    .A(data_in[1]),
    .B(_193_),
    .Y(_199_)
  );
  NOR _480_ (
    .A(_193_),
    .B(_198_),
    .Y(_200_)
  );
  NOT _481_ (
    .A(_200_),
    .Y(_201_)
  );
  NAND _482_ (
    .A(_199_),
    .B(_201_),
    .Y(_005_)
  );
  NAND _483_ (
    .A(reset_L),
    .B(\mem[0] [2]),
    .Y(_202_)
  );
  NAND _484_ (
    .A(data_in[2]),
    .B(_193_),
    .Y(_203_)
  );
  NOR _485_ (
    .A(_193_),
    .B(_202_),
    .Y(_204_)
  );
  NOT _486_ (
    .A(_204_),
    .Y(_205_)
  );
  NAND _487_ (
    .A(_203_),
    .B(_205_),
    .Y(_006_)
  );
  NAND _488_ (
    .A(reset_L),
    .B(\mem[0] [3]),
    .Y(_206_)
  );
  NAND _489_ (
    .A(data_in[3]),
    .B(_193_),
    .Y(_207_)
  );
  NOR _490_ (
    .A(_193_),
    .B(_206_),
    .Y(_208_)
  );
  NOT _491_ (
    .A(_208_),
    .Y(_209_)
  );
  NAND _492_ (
    .A(_207_),
    .B(_209_),
    .Y(_007_)
  );
  NAND _493_ (
    .A(reset_L),
    .B(\mem[0] [4]),
    .Y(_210_)
  );
  NAND _494_ (
    .A(data_in[4]),
    .B(_193_),
    .Y(_211_)
  );
  NOR _495_ (
    .A(_193_),
    .B(_210_),
    .Y(_212_)
  );
  NOT _496_ (
    .A(_212_),
    .Y(_213_)
  );
  NAND _497_ (
    .A(_211_),
    .B(_213_),
    .Y(_008_)
  );
  NAND _498_ (
    .A(reset_L),
    .B(\mem[0] [5]),
    .Y(_214_)
  );
  NAND _499_ (
    .A(data_in[5]),
    .B(_193_),
    .Y(_215_)
  );
  NOR _500_ (
    .A(_193_),
    .B(_214_),
    .Y(_216_)
  );
  NOT _501_ (
    .A(_216_),
    .Y(_217_)
  );
  NAND _502_ (
    .A(_215_),
    .B(_217_),
    .Y(_009_)
  );
  NOR _503_ (
    .A(_042_),
    .B(_046_),
    .Y(_218_)
  );
  NAND _504_ (
    .A(reset_L),
    .B(\mem[1] [0]),
    .Y(_219_)
  );
  NAND _505_ (
    .A(_051_),
    .B(_218_),
    .Y(_220_)
  );
  NOR _506_ (
    .A(_218_),
    .B(_219_),
    .Y(_221_)
  );
  NOT _507_ (
    .A(_221_),
    .Y(_222_)
  );
  NAND _508_ (
    .A(_220_),
    .B(_222_),
    .Y(_010_)
  );
  NAND _509_ (
    .A(reset_L),
    .B(\mem[1] [1]),
    .Y(_223_)
  );
  NAND _510_ (
    .A(_054_),
    .B(_218_),
    .Y(_224_)
  );
  NOR _511_ (
    .A(_218_),
    .B(_223_),
    .Y(_225_)
  );
  NOT _512_ (
    .A(_225_),
    .Y(_226_)
  );
  NAND _513_ (
    .A(_224_),
    .B(_226_),
    .Y(_011_)
  );
  NAND _514_ (
    .A(reset_L),
    .B(\mem[1] [2]),
    .Y(_227_)
  );
  NAND _515_ (
    .A(_057_),
    .B(_218_),
    .Y(_228_)
  );
  NOR _516_ (
    .A(_218_),
    .B(_227_),
    .Y(_229_)
  );
  NOT _517_ (
    .A(_229_),
    .Y(_230_)
  );
  NAND _518_ (
    .A(_228_),
    .B(_230_),
    .Y(_012_)
  );
  NAND _519_ (
    .A(reset_L),
    .B(\mem[1] [3]),
    .Y(_231_)
  );
  NAND _520_ (
    .A(_060_),
    .B(_218_),
    .Y(_232_)
  );
  NOR _521_ (
    .A(_218_),
    .B(_231_),
    .Y(_233_)
  );
  NOT _522_ (
    .A(_233_),
    .Y(_234_)
  );
  NAND _523_ (
    .A(_232_),
    .B(_234_),
    .Y(_013_)
  );
  NAND _524_ (
    .A(reset_L),
    .B(\mem[1] [4]),
    .Y(_235_)
  );
  NAND _525_ (
    .A(_063_),
    .B(_218_),
    .Y(_236_)
  );
  NOR _526_ (
    .A(_218_),
    .B(_235_),
    .Y(_237_)
  );
  NOT _527_ (
    .A(_237_),
    .Y(_238_)
  );
  NAND _528_ (
    .A(_236_),
    .B(_238_),
    .Y(_014_)
  );
  NAND _529_ (
    .A(reset_L),
    .B(\mem[1] [5]),
    .Y(_239_)
  );
  NAND _530_ (
    .A(_066_),
    .B(_218_),
    .Y(_240_)
  );
  NOR _531_ (
    .A(_218_),
    .B(_239_),
    .Y(_241_)
  );
  NOT _532_ (
    .A(_241_),
    .Y(_242_)
  );
  NAND _533_ (
    .A(_240_),
    .B(_242_),
    .Y(_015_)
  );
  DFF _534_ (
    .C(clk),
    .D(_004_),
    .Q(\mem[0] [0])
  );
  DFF _535_ (
    .C(clk),
    .D(_005_),
    .Q(\mem[0] [1])
  );
  DFF _536_ (
    .C(clk),
    .D(_006_),
    .Q(\mem[0] [2])
  );
  DFF _537_ (
    .C(clk),
    .D(_007_),
    .Q(\mem[0] [3])
  );
  DFF _538_ (
    .C(clk),
    .D(_008_),
    .Q(\mem[0] [4])
  );
  DFF _539_ (
    .C(clk),
    .D(_009_),
    .Q(\mem[0] [5])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:61" *)
  DFF _540_ (
    .C(clk),
    .D(_000_[0]),
    .Q(cnt[0])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:61" *)
  DFF _541_ (
    .C(clk),
    .D(_000_[1]),
    .Q(cnt[1])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:61" *)
  DFF _542_ (
    .C(clk),
    .D(_000_[2]),
    .Q(cnt[2])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:46" *)
  DFF _543_ (
    .C(clk),
    .D(_001_[0]),
    .Q(data_out_D0_synth[0])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:46" *)
  DFF _544_ (
    .C(clk),
    .D(_001_[1]),
    .Q(data_out_D0_synth[1])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:46" *)
  DFF _545_ (
    .C(clk),
    .D(_001_[2]),
    .Q(data_out_D0_synth[2])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:46" *)
  DFF _546_ (
    .C(clk),
    .D(_001_[3]),
    .Q(data_out_D0_synth[3])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:46" *)
  DFF _547_ (
    .C(clk),
    .D(_001_[4]),
    .Q(data_out_D0_synth[4])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:46" *)
  DFF _548_ (
    .C(clk),
    .D(_001_[5]),
    .Q(data_out_D0_synth[5])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:30" *)
  DFF _549_ (
    .C(clk),
    .D(_003_[0]),
    .Q(wr_ptr[0])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:30" *)
  DFF _550_ (
    .C(clk),
    .D(_003_[1]),
    .Q(wr_ptr[1])
  );
  DFF _551_ (
    .C(clk),
    .D(_002_[0]),
    .Q(rd_ptr[0])
  );
  DFF _552_ (
    .C(clk),
    .D(_002_[1]),
    .Q(rd_ptr[1])
  );
  DFF _553_ (
    .C(clk),
    .D(_010_),
    .Q(\mem[1] [0])
  );
  DFF _554_ (
    .C(clk),
    .D(_011_),
    .Q(\mem[1] [1])
  );
  DFF _555_ (
    .C(clk),
    .D(_012_),
    .Q(\mem[1] [2])
  );
  DFF _556_ (
    .C(clk),
    .D(_013_),
    .Q(\mem[1] [3])
  );
  DFF _557_ (
    .C(clk),
    .D(_014_),
    .Q(\mem[1] [4])
  );
  DFF _558_ (
    .C(clk),
    .D(_015_),
    .Q(\mem[1] [5])
  );
  DFF _559_ (
    .C(clk),
    .D(_016_),
    .Q(\mem[2] [0])
  );
  DFF _560_ (
    .C(clk),
    .D(_017_),
    .Q(\mem[2] [1])
  );
  DFF _561_ (
    .C(clk),
    .D(_018_),
    .Q(\mem[2] [2])
  );
  DFF _562_ (
    .C(clk),
    .D(_019_),
    .Q(\mem[2] [3])
  );
  DFF _563_ (
    .C(clk),
    .D(_020_),
    .Q(\mem[2] [4])
  );
  DFF _564_ (
    .C(clk),
    .D(_021_),
    .Q(\mem[2] [5])
  );
  DFF _565_ (
    .C(clk),
    .D(_022_),
    .Q(\mem[3] [0])
  );
  DFF _566_ (
    .C(clk),
    .D(_023_),
    .Q(\mem[3] [1])
  );
  DFF _567_ (
    .C(clk),
    .D(_024_),
    .Q(\mem[3] [2])
  );
  DFF _568_ (
    .C(clk),
    .D(_025_),
    .Q(\mem[3] [3])
  );
  DFF _569_ (
    .C(clk),
    .D(_026_),
    .Q(\mem[3] [4])
  );
  DFF _570_ (
    .C(clk),
    .D(_027_),
    .Q(\mem[3] [5])
  );
  assign i = 32'd4;
endmodule

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "./final_logic_synth/D1_fifo_synth.v:1" *)
module D1_fifo_synth(clk, reset_L, wr_enable, rd_enable, data_in, full_fifo_D1, empty_fifo_D1, almost_full_fifo_D1, almost_empty_fifo_D1, error_D1_synth, data_out_D1_synth);
  (* src = "./final_logic_synth/D1_fifo_synth.v:62" *)
  wire [2:0] _000_;
  (* src = "./final_logic_synth/D1_fifo_synth.v:47" *)
  wire [5:0] _001_;
  (* src = "./final_logic_synth/D1_fifo_synth.v:47" *)
  wire [1:0] _002_;
  (* src = "./final_logic_synth/D1_fifo_synth.v:31" *)
  wire [1:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  (* src = "./final_logic_synth/D1_fifo_synth.v:11" *)
  output almost_empty_fifo_D1;
  (* src = "./final_logic_synth/D1_fifo_synth.v:10" *)
  output almost_full_fifo_D1;
  (* src = "./final_logic_synth/D1_fifo_synth.v:6" *)
  input clk;
  (* src = "./final_logic_synth/D1_fifo_synth.v:20" *)
  wire [2:0] cnt;
  (* src = "./final_logic_synth/D1_fifo_synth.v:7" *)
  input [5:0] data_in;
  (* src = "./final_logic_synth/D1_fifo_synth.v:13" *)
  output [5:0] data_out_D1_synth;
  (* src = "./final_logic_synth/D1_fifo_synth.v:9" *)
  output empty_fifo_D1;
  (* src = "./final_logic_synth/D1_fifo_synth.v:12" *)
  output error_D1_synth;
  (* src = "./final_logic_synth/D1_fifo_synth.v:8" *)
  output full_fifo_D1;
  (* src = "./final_logic_synth/D1_fifo_synth.v:28" *)
  wire [31:0] i;
  wire [5:0] \mem[0] ;
  wire [5:0] \mem[1] ;
  wire [5:0] \mem[2] ;
  wire [5:0] \mem[3] ;
  (* src = "./final_logic_synth/D1_fifo_synth.v:6" *)
  input rd_enable;
  (* src = "./final_logic_synth/D1_fifo_synth.v:19" *)
  wire [1:0] rd_ptr;
  (* src = "./final_logic_synth/D1_fifo_synth.v:6" *)
  input reset_L;
  (* src = "./final_logic_synth/D1_fifo_synth.v:6" *)
  input wr_enable;
  (* src = "./final_logic_synth/D1_fifo_synth.v:18" *)
  wire [1:0] wr_ptr;
  NOT _262_ (
    .A(cnt[1]),
    .Y(_245_)
  );
  NOT _263_ (
    .A(cnt[2]),
    .Y(_246_)
  );
  NOT _264_ (
    .A(wr_enable),
    .Y(_247_)
  );
  NOT _265_ (
    .A(rd_enable),
    .Y(_248_)
  );
  NOT _266_ (
    .A(\mem[3] [0]),
    .Y(_249_)
  );
  NOT _267_ (
    .A(\mem[3] [1]),
    .Y(_250_)
  );
  NOT _268_ (
    .A(\mem[3] [2]),
    .Y(_251_)
  );
  NOT _269_ (
    .A(\mem[3] [3]),
    .Y(_252_)
  );
  NOT _270_ (
    .A(\mem[3] [4]),
    .Y(_253_)
  );
  NOT _271_ (
    .A(\mem[3] [5]),
    .Y(_254_)
  );
  NOT _272_ (
    .A(\mem[0] [0]),
    .Y(_255_)
  );
  NOT _273_ (
    .A(\mem[0] [1]),
    .Y(_256_)
  );
  NOT _274_ (
    .A(\mem[0] [2]),
    .Y(_257_)
  );
  NOT _275_ (
    .A(\mem[0] [3]),
    .Y(_258_)
  );
  NOT _276_ (
    .A(\mem[0] [4]),
    .Y(_259_)
  );
  NOT _277_ (
    .A(\mem[0] [5]),
    .Y(_260_)
  );
  NOT _278_ (
    .A(rd_ptr[1]),
    .Y(_261_)
  );
  NOT _279_ (
    .A(reset_L),
    .Y(_028_)
  );
  NOT _280_ (
    .A(wr_ptr[0]),
    .Y(_029_)
  );
  NOT _281_ (
    .A(data_in[0]),
    .Y(_030_)
  );
  NOT _282_ (
    .A(data_in[1]),
    .Y(_031_)
  );
  NOT _283_ (
    .A(data_in[2]),
    .Y(_032_)
  );
  NOT _284_ (
    .A(data_in[3]),
    .Y(_033_)
  );
  NOT _285_ (
    .A(data_in[4]),
    .Y(_034_)
  );
  NOT _286_ (
    .A(data_in[5]),
    .Y(_035_)
  );
  NOR _287_ (
    .A(cnt[1]),
    .B(cnt[0]),
    .Y(_036_)
  );
  NOT _288_ (
    .A(_036_),
    .Y(_037_)
  );
  NAND _289_ (
    .A(cnt[2]),
    .B(_036_),
    .Y(_038_)
  );
  NOT _290_ (
    .A(_038_),
    .Y(full_fifo_D1)
  );
  NOR _291_ (
    .A(cnt[2]),
    .B(_037_),
    .Y(empty_fifo_D1)
  );
  NAND _292_ (
    .A(_246_),
    .B(cnt[0]),
    .Y(_039_)
  );
  NOR _293_ (
    .A(cnt[1]),
    .B(_039_),
    .Y(almost_empty_fifo_D1)
  );
  NAND _294_ (
    .A(cnt[1]),
    .B(cnt[0]),
    .Y(_040_)
  );
  NOT _295_ (
    .A(_040_),
    .Y(_041_)
  );
  NOR _296_ (
    .A(cnt[2]),
    .B(_040_),
    .Y(almost_full_fifo_D1)
  );
  NAND _297_ (
    .A(wr_enable),
    .B(wr_ptr[1]),
    .Y(_042_)
  );
  NAND _298_ (
    .A(reset_L),
    .B(_042_),
    .Y(_043_)
  );
  NOT _299_ (
    .A(_043_),
    .Y(_044_)
  );
  NAND _300_ (
    .A(wr_enable),
    .B(wr_ptr[0]),
    .Y(_045_)
  );
  NOT _301_ (
    .A(_045_),
    .Y(_046_)
  );
  NOR _302_ (
    .A(_043_),
    .B(_045_),
    .Y(_047_)
  );
  NAND _303_ (
    .A(\mem[1] [0]),
    .B(reset_L),
    .Y(_048_)
  );
  NAND _304_ (
    .A(wr_enable),
    .B(reset_L),
    .Y(_049_)
  );
  NOR _305_ (
    .A(_030_),
    .B(_049_),
    .Y(_050_)
  );
  NAND _306_ (
    .A(_047_),
    .B(_050_),
    .Y(_051_)
  );
  NOR _307_ (
    .A(_047_),
    .B(_048_),
    .Y(_052_)
  );
  NOT _308_ (
    .A(_052_),
    .Y(_053_)
  );
  NAND _309_ (
    .A(_051_),
    .B(_053_),
    .Y(_010_)
  );
  NAND _310_ (
    .A(\mem[1] [1]),
    .B(reset_L),
    .Y(_054_)
  );
  NOR _311_ (
    .A(_031_),
    .B(_049_),
    .Y(_055_)
  );
  NAND _312_ (
    .A(_047_),
    .B(_055_),
    .Y(_056_)
  );
  NOR _313_ (
    .A(_047_),
    .B(_054_),
    .Y(_057_)
  );
  NOT _314_ (
    .A(_057_),
    .Y(_058_)
  );
  NAND _315_ (
    .A(_056_),
    .B(_058_),
    .Y(_011_)
  );
  NAND _316_ (
    .A(\mem[1] [2]),
    .B(reset_L),
    .Y(_059_)
  );
  NOR _317_ (
    .A(_032_),
    .B(_049_),
    .Y(_060_)
  );
  NAND _318_ (
    .A(_047_),
    .B(_060_),
    .Y(_061_)
  );
  NOR _319_ (
    .A(_047_),
    .B(_059_),
    .Y(_062_)
  );
  NOT _320_ (
    .A(_062_),
    .Y(_063_)
  );
  NAND _321_ (
    .A(_061_),
    .B(_063_),
    .Y(_012_)
  );
  NAND _322_ (
    .A(\mem[1] [3]),
    .B(reset_L),
    .Y(_064_)
  );
  NOR _323_ (
    .A(_033_),
    .B(_049_),
    .Y(_065_)
  );
  NAND _324_ (
    .A(_047_),
    .B(_065_),
    .Y(_066_)
  );
  NOR _325_ (
    .A(_047_),
    .B(_064_),
    .Y(_067_)
  );
  NOT _326_ (
    .A(_067_),
    .Y(_068_)
  );
  NAND _327_ (
    .A(_066_),
    .B(_068_),
    .Y(_013_)
  );
  NAND _328_ (
    .A(\mem[1] [4]),
    .B(reset_L),
    .Y(_069_)
  );
  NOR _329_ (
    .A(_034_),
    .B(_049_),
    .Y(_070_)
  );
  NOR _330_ (
    .A(_047_),
    .B(_069_),
    .Y(_071_)
  );
  NOT _331_ (
    .A(_071_),
    .Y(_072_)
  );
  NAND _332_ (
    .A(_047_),
    .B(_070_),
    .Y(_073_)
  );
  NAND _333_ (
    .A(_072_),
    .B(_073_),
    .Y(_014_)
  );
  NAND _334_ (
    .A(\mem[1] [5]),
    .B(reset_L),
    .Y(_074_)
  );
  NOR _335_ (
    .A(_035_),
    .B(_049_),
    .Y(_075_)
  );
  NAND _336_ (
    .A(_047_),
    .B(_075_),
    .Y(_076_)
  );
  NOR _337_ (
    .A(_047_),
    .B(_074_),
    .Y(_077_)
  );
  NOT _338_ (
    .A(_077_),
    .Y(_078_)
  );
  NAND _339_ (
    .A(_076_),
    .B(_078_),
    .Y(_015_)
  );
  NAND _340_ (
    .A(reset_L),
    .B(_029_),
    .Y(_079_)
  );
  NOT _341_ (
    .A(_079_),
    .Y(_080_)
  );
  NOR _342_ (
    .A(_042_),
    .B(_079_),
    .Y(_081_)
  );
  NAND _343_ (
    .A(\mem[2] [0]),
    .B(reset_L),
    .Y(_082_)
  );
  NAND _344_ (
    .A(_050_),
    .B(_081_),
    .Y(_083_)
  );
  NOR _345_ (
    .A(_081_),
    .B(_082_),
    .Y(_084_)
  );
  NOT _346_ (
    .A(_084_),
    .Y(_085_)
  );
  NAND _347_ (
    .A(_083_),
    .B(_085_),
    .Y(_016_)
  );
  NAND _348_ (
    .A(\mem[2] [1]),
    .B(reset_L),
    .Y(_086_)
  );
  NAND _349_ (
    .A(_055_),
    .B(_081_),
    .Y(_087_)
  );
  NOR _350_ (
    .A(_081_),
    .B(_086_),
    .Y(_088_)
  );
  NOT _351_ (
    .A(_088_),
    .Y(_089_)
  );
  NAND _352_ (
    .A(_087_),
    .B(_089_),
    .Y(_017_)
  );
  NAND _353_ (
    .A(\mem[2] [2]),
    .B(reset_L),
    .Y(_090_)
  );
  NAND _354_ (
    .A(_060_),
    .B(_081_),
    .Y(_091_)
  );
  NOR _355_ (
    .A(_081_),
    .B(_090_),
    .Y(_092_)
  );
  NOT _356_ (
    .A(_092_),
    .Y(_093_)
  );
  NAND _357_ (
    .A(_091_),
    .B(_093_),
    .Y(_018_)
  );
  NAND _358_ (
    .A(\mem[2] [3]),
    .B(reset_L),
    .Y(_094_)
  );
  NAND _359_ (
    .A(_065_),
    .B(_081_),
    .Y(_095_)
  );
  NOR _360_ (
    .A(_081_),
    .B(_094_),
    .Y(_096_)
  );
  NOT _361_ (
    .A(_096_),
    .Y(_097_)
  );
  NAND _362_ (
    .A(_095_),
    .B(_097_),
    .Y(_019_)
  );
  NAND _363_ (
    .A(\mem[2] [4]),
    .B(reset_L),
    .Y(_098_)
  );
  NOR _364_ (
    .A(_081_),
    .B(_098_),
    .Y(_099_)
  );
  NOT _365_ (
    .A(_099_),
    .Y(_100_)
  );
  NAND _366_ (
    .A(_070_),
    .B(_081_),
    .Y(_101_)
  );
  NAND _367_ (
    .A(_100_),
    .B(_101_),
    .Y(_020_)
  );
  NAND _368_ (
    .A(\mem[2] [5]),
    .B(reset_L),
    .Y(_102_)
  );
  NAND _369_ (
    .A(_075_),
    .B(_081_),
    .Y(_103_)
  );
  NOR _370_ (
    .A(_081_),
    .B(_102_),
    .Y(_104_)
  );
  NOT _371_ (
    .A(_104_),
    .Y(_105_)
  );
  NAND _372_ (
    .A(_103_),
    .B(_105_),
    .Y(_021_)
  );
  NOR _373_ (
    .A(_247_),
    .B(rd_enable),
    .Y(_106_)
  );
  NAND _374_ (
    .A(wr_enable),
    .B(_248_),
    .Y(_107_)
  );
  NOR _375_ (
    .A(wr_enable),
    .B(_248_),
    .Y(_108_)
  );
  NAND _376_ (
    .A(_247_),
    .B(rd_enable),
    .Y(_109_)
  );
  NAND _377_ (
    .A(_107_),
    .B(_109_),
    .Y(_110_)
  );
  NAND _378_ (
    .A(cnt[0]),
    .B(_110_),
    .Y(_111_)
  );
  NOT _379_ (
    .A(_111_),
    .Y(_112_)
  );
  NOR _380_ (
    .A(cnt[0]),
    .B(_110_),
    .Y(_113_)
  );
  NOT _381_ (
    .A(_113_),
    .Y(_114_)
  );
  NAND _382_ (
    .A(reset_L),
    .B(_114_),
    .Y(_115_)
  );
  NOR _383_ (
    .A(_112_),
    .B(_115_),
    .Y(_000_[0])
  );
  NOR _384_ (
    .A(_245_),
    .B(_110_),
    .Y(_116_)
  );
  NOR _385_ (
    .A(_036_),
    .B(_041_),
    .Y(_117_)
  );
  NAND _386_ (
    .A(_037_),
    .B(_040_),
    .Y(_118_)
  );
  NOR _387_ (
    .A(_106_),
    .B(_118_),
    .Y(_119_)
  );
  NOR _388_ (
    .A(_108_),
    .B(_117_),
    .Y(_120_)
  );
  NOR _389_ (
    .A(_119_),
    .B(_120_),
    .Y(_121_)
  );
  NOR _390_ (
    .A(_116_),
    .B(_121_),
    .Y(_122_)
  );
  NOR _391_ (
    .A(_028_),
    .B(_122_),
    .Y(_000_[1])
  );
  NOR _392_ (
    .A(_246_),
    .B(_036_),
    .Y(error_D1_synth)
  );
  NOR _393_ (
    .A(empty_fifo_D1),
    .B(error_D1_synth),
    .Y(_123_)
  );
  NOR _394_ (
    .A(_109_),
    .B(_123_),
    .Y(_124_)
  );
  NOR _395_ (
    .A(_040_),
    .B(_107_),
    .Y(_125_)
  );
  NAND _396_ (
    .A(_041_),
    .B(_106_),
    .Y(_126_)
  );
  NOR _397_ (
    .A(_246_),
    .B(_126_),
    .Y(_127_)
  );
  NOR _398_ (
    .A(_246_),
    .B(_108_),
    .Y(_128_)
  );
  NOR _399_ (
    .A(_125_),
    .B(_128_),
    .Y(_129_)
  );
  NOR _400_ (
    .A(_127_),
    .B(_129_),
    .Y(_130_)
  );
  NOR _401_ (
    .A(_124_),
    .B(_130_),
    .Y(_131_)
  );
  NOR _402_ (
    .A(_028_),
    .B(_131_),
    .Y(_000_[2])
  );
  NAND _403_ (
    .A(rd_enable),
    .B(reset_L),
    .Y(_132_)
  );
  NOR _404_ (
    .A(\mem[2] [0]),
    .B(rd_ptr[0]),
    .Y(_133_)
  );
  NAND _405_ (
    .A(_249_),
    .B(rd_ptr[0]),
    .Y(_134_)
  );
  NAND _406_ (
    .A(rd_ptr[1]),
    .B(_134_),
    .Y(_135_)
  );
  NOR _407_ (
    .A(_133_),
    .B(_135_),
    .Y(_136_)
  );
  NAND _408_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [0]),
    .Y(_137_)
  );
  NOT _409_ (
    .A(_137_),
    .Y(_138_)
  );
  NOR _410_ (
    .A(rd_ptr[0]),
    .B(_255_),
    .Y(_139_)
  );
  NOR _411_ (
    .A(_138_),
    .B(_139_),
    .Y(_140_)
  );
  NOR _412_ (
    .A(rd_ptr[1]),
    .B(_140_),
    .Y(_141_)
  );
  NOR _413_ (
    .A(_136_),
    .B(_141_),
    .Y(_142_)
  );
  NOR _414_ (
    .A(_132_),
    .B(_142_),
    .Y(_001_[0])
  );
  NOR _415_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [1]),
    .Y(_143_)
  );
  NAND _416_ (
    .A(rd_ptr[0]),
    .B(_250_),
    .Y(_144_)
  );
  NAND _417_ (
    .A(rd_ptr[1]),
    .B(_144_),
    .Y(_145_)
  );
  NOR _418_ (
    .A(_143_),
    .B(_145_),
    .Y(_146_)
  );
  NAND _419_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [1]),
    .Y(_147_)
  );
  NOT _420_ (
    .A(_147_),
    .Y(_148_)
  );
  NOR _421_ (
    .A(rd_ptr[0]),
    .B(_256_),
    .Y(_149_)
  );
  NOR _422_ (
    .A(_148_),
    .B(_149_),
    .Y(_150_)
  );
  NOR _423_ (
    .A(rd_ptr[1]),
    .B(_150_),
    .Y(_151_)
  );
  NOR _424_ (
    .A(_146_),
    .B(_151_),
    .Y(_152_)
  );
  NOR _425_ (
    .A(_132_),
    .B(_152_),
    .Y(_001_[1])
  );
  NOR _426_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [2]),
    .Y(_153_)
  );
  NAND _427_ (
    .A(rd_ptr[0]),
    .B(_251_),
    .Y(_154_)
  );
  NAND _428_ (
    .A(rd_ptr[1]),
    .B(_154_),
    .Y(_155_)
  );
  NOR _429_ (
    .A(_153_),
    .B(_155_),
    .Y(_156_)
  );
  NAND _430_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [2]),
    .Y(_157_)
  );
  NOT _431_ (
    .A(_157_),
    .Y(_158_)
  );
  NOR _432_ (
    .A(rd_ptr[0]),
    .B(_257_),
    .Y(_159_)
  );
  NOR _433_ (
    .A(_158_),
    .B(_159_),
    .Y(_160_)
  );
  NOR _434_ (
    .A(rd_ptr[1]),
    .B(_160_),
    .Y(_161_)
  );
  NOR _435_ (
    .A(_156_),
    .B(_161_),
    .Y(_162_)
  );
  NOR _436_ (
    .A(_132_),
    .B(_162_),
    .Y(_001_[2])
  );
  NOR _437_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [3]),
    .Y(_163_)
  );
  NAND _438_ (
    .A(rd_ptr[0]),
    .B(_252_),
    .Y(_164_)
  );
  NAND _439_ (
    .A(rd_ptr[1]),
    .B(_164_),
    .Y(_165_)
  );
  NOR _440_ (
    .A(_163_),
    .B(_165_),
    .Y(_166_)
  );
  NAND _441_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [3]),
    .Y(_167_)
  );
  NOT _442_ (
    .A(_167_),
    .Y(_168_)
  );
  NOR _443_ (
    .A(rd_ptr[0]),
    .B(_258_),
    .Y(_169_)
  );
  NOR _444_ (
    .A(_168_),
    .B(_169_),
    .Y(_170_)
  );
  NOR _445_ (
    .A(rd_ptr[1]),
    .B(_170_),
    .Y(_171_)
  );
  NOR _446_ (
    .A(_166_),
    .B(_171_),
    .Y(_172_)
  );
  NOR _447_ (
    .A(_132_),
    .B(_172_),
    .Y(_001_[3])
  );
  NOR _448_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [4]),
    .Y(_173_)
  );
  NAND _449_ (
    .A(rd_ptr[0]),
    .B(_253_),
    .Y(_174_)
  );
  NAND _450_ (
    .A(rd_ptr[1]),
    .B(_174_),
    .Y(_175_)
  );
  NOR _451_ (
    .A(_173_),
    .B(_175_),
    .Y(_176_)
  );
  NAND _452_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [4]),
    .Y(_177_)
  );
  NOT _453_ (
    .A(_177_),
    .Y(_178_)
  );
  NOR _454_ (
    .A(rd_ptr[0]),
    .B(_259_),
    .Y(_179_)
  );
  NOR _455_ (
    .A(_178_),
    .B(_179_),
    .Y(_180_)
  );
  NOR _456_ (
    .A(rd_ptr[1]),
    .B(_180_),
    .Y(_181_)
  );
  NOR _457_ (
    .A(_176_),
    .B(_181_),
    .Y(_182_)
  );
  NOR _458_ (
    .A(_132_),
    .B(_182_),
    .Y(_001_[4])
  );
  NOR _459_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [5]),
    .Y(_183_)
  );
  NAND _460_ (
    .A(rd_ptr[0]),
    .B(_254_),
    .Y(_184_)
  );
  NAND _461_ (
    .A(rd_ptr[1]),
    .B(_184_),
    .Y(_185_)
  );
  NOR _462_ (
    .A(_183_),
    .B(_185_),
    .Y(_186_)
  );
  NAND _463_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [5]),
    .Y(_187_)
  );
  NOT _464_ (
    .A(_187_),
    .Y(_188_)
  );
  NOR _465_ (
    .A(rd_ptr[0]),
    .B(_260_),
    .Y(_189_)
  );
  NOR _466_ (
    .A(_188_),
    .B(_189_),
    .Y(_190_)
  );
  NOR _467_ (
    .A(rd_ptr[1]),
    .B(_190_),
    .Y(_191_)
  );
  NOR _468_ (
    .A(_186_),
    .B(_191_),
    .Y(_192_)
  );
  NOR _469_ (
    .A(_132_),
    .B(_192_),
    .Y(_001_[5])
  );
  NAND _470_ (
    .A(rd_enable),
    .B(rd_ptr[0]),
    .Y(_193_)
  );
  NOT _471_ (
    .A(_193_),
    .Y(_194_)
  );
  NOR _472_ (
    .A(rd_enable),
    .B(rd_ptr[0]),
    .Y(_195_)
  );
  NOT _473_ (
    .A(_195_),
    .Y(_196_)
  );
  NAND _474_ (
    .A(reset_L),
    .B(_196_),
    .Y(_197_)
  );
  NOR _475_ (
    .A(_194_),
    .B(_197_),
    .Y(_002_[0])
  );
  NOR _476_ (
    .A(_261_),
    .B(_193_),
    .Y(_198_)
  );
  NAND _477_ (
    .A(_261_),
    .B(_193_),
    .Y(_199_)
  );
  NAND _478_ (
    .A(reset_L),
    .B(_199_),
    .Y(_200_)
  );
  NOR _479_ (
    .A(_198_),
    .B(_200_),
    .Y(_002_[1])
  );
  NOR _480_ (
    .A(wr_ptr[0]),
    .B(wr_ptr[1]),
    .Y(_201_)
  );
  NOT _481_ (
    .A(_201_),
    .Y(_202_)
  );
  NOR _482_ (
    .A(_049_),
    .B(_202_),
    .Y(_203_)
  );
  NAND _483_ (
    .A(\mem[0] [0]),
    .B(reset_L),
    .Y(_204_)
  );
  NAND _484_ (
    .A(_050_),
    .B(_201_),
    .Y(_205_)
  );
  NOR _485_ (
    .A(_203_),
    .B(_204_),
    .Y(_206_)
  );
  NOT _486_ (
    .A(_206_),
    .Y(_207_)
  );
  NAND _487_ (
    .A(_205_),
    .B(_207_),
    .Y(_004_)
  );
  NAND _488_ (
    .A(\mem[0] [1]),
    .B(reset_L),
    .Y(_208_)
  );
  NAND _489_ (
    .A(_055_),
    .B(_201_),
    .Y(_209_)
  );
  NOR _490_ (
    .A(_203_),
    .B(_208_),
    .Y(_210_)
  );
  NOT _491_ (
    .A(_210_),
    .Y(_211_)
  );
  NAND _492_ (
    .A(_209_),
    .B(_211_),
    .Y(_005_)
  );
  NAND _493_ (
    .A(\mem[0] [2]),
    .B(reset_L),
    .Y(_212_)
  );
  NAND _494_ (
    .A(_060_),
    .B(_201_),
    .Y(_213_)
  );
  NOR _495_ (
    .A(_203_),
    .B(_212_),
    .Y(_214_)
  );
  NOT _496_ (
    .A(_214_),
    .Y(_215_)
  );
  NAND _497_ (
    .A(_213_),
    .B(_215_),
    .Y(_006_)
  );
  NAND _498_ (
    .A(\mem[0] [3]),
    .B(reset_L),
    .Y(_216_)
  );
  NAND _499_ (
    .A(_065_),
    .B(_201_),
    .Y(_217_)
  );
  NOR _500_ (
    .A(_203_),
    .B(_216_),
    .Y(_218_)
  );
  NOT _501_ (
    .A(_218_),
    .Y(_219_)
  );
  NAND _502_ (
    .A(_217_),
    .B(_219_),
    .Y(_007_)
  );
  NAND _503_ (
    .A(\mem[0] [4]),
    .B(reset_L),
    .Y(_220_)
  );
  NAND _504_ (
    .A(_070_),
    .B(_201_),
    .Y(_221_)
  );
  NOR _505_ (
    .A(_203_),
    .B(_220_),
    .Y(_222_)
  );
  NOT _506_ (
    .A(_222_),
    .Y(_223_)
  );
  NAND _507_ (
    .A(_221_),
    .B(_223_),
    .Y(_008_)
  );
  NAND _508_ (
    .A(\mem[0] [5]),
    .B(reset_L),
    .Y(_224_)
  );
  NAND _509_ (
    .A(_075_),
    .B(_201_),
    .Y(_225_)
  );
  NOR _510_ (
    .A(_203_),
    .B(_224_),
    .Y(_226_)
  );
  NOT _511_ (
    .A(_226_),
    .Y(_227_)
  );
  NAND _512_ (
    .A(_225_),
    .B(_227_),
    .Y(_009_)
  );
  NOR _513_ (
    .A(wr_enable),
    .B(wr_ptr[0]),
    .Y(_228_)
  );
  NAND _514_ (
    .A(reset_L),
    .B(_045_),
    .Y(_229_)
  );
  NOR _515_ (
    .A(_228_),
    .B(_229_),
    .Y(_003_[0])
  );
  NOR _516_ (
    .A(wr_ptr[1]),
    .B(_046_),
    .Y(_230_)
  );
  NOR _517_ (
    .A(_044_),
    .B(_080_),
    .Y(_231_)
  );
  NAND _518_ (
    .A(_043_),
    .B(_079_),
    .Y(_232_)
  );
  NOR _519_ (
    .A(_230_),
    .B(_231_),
    .Y(_003_[1])
  );
  NAND _520_ (
    .A(_050_),
    .B(_231_),
    .Y(_233_)
  );
  NAND _521_ (
    .A(\mem[3] [0]),
    .B(_232_),
    .Y(_234_)
  );
  NAND _522_ (
    .A(_233_),
    .B(_234_),
    .Y(_022_)
  );
  NAND _523_ (
    .A(_055_),
    .B(_231_),
    .Y(_235_)
  );
  NAND _524_ (
    .A(\mem[3] [1]),
    .B(_232_),
    .Y(_236_)
  );
  NAND _525_ (
    .A(_235_),
    .B(_236_),
    .Y(_023_)
  );
  NAND _526_ (
    .A(_060_),
    .B(_231_),
    .Y(_237_)
  );
  NAND _527_ (
    .A(\mem[3] [2]),
    .B(_232_),
    .Y(_238_)
  );
  NAND _528_ (
    .A(_237_),
    .B(_238_),
    .Y(_024_)
  );
  NAND _529_ (
    .A(_065_),
    .B(_231_),
    .Y(_239_)
  );
  NAND _530_ (
    .A(\mem[3] [3]),
    .B(_232_),
    .Y(_240_)
  );
  NAND _531_ (
    .A(_239_),
    .B(_240_),
    .Y(_025_)
  );
  NAND _532_ (
    .A(_070_),
    .B(_231_),
    .Y(_241_)
  );
  NAND _533_ (
    .A(\mem[3] [4]),
    .B(_232_),
    .Y(_242_)
  );
  NAND _534_ (
    .A(_241_),
    .B(_242_),
    .Y(_026_)
  );
  NAND _535_ (
    .A(_075_),
    .B(_231_),
    .Y(_243_)
  );
  NAND _536_ (
    .A(\mem[3] [5]),
    .B(_232_),
    .Y(_244_)
  );
  NAND _537_ (
    .A(_243_),
    .B(_244_),
    .Y(_027_)
  );
  DFF _538_ (
    .C(clk),
    .D(_002_[0]),
    .Q(rd_ptr[0])
  );
  DFF _539_ (
    .C(clk),
    .D(_002_[1]),
    .Q(rd_ptr[1])
  );
  DFF _540_ (
    .C(clk),
    .D(_022_),
    .Q(\mem[3] [0])
  );
  DFF _541_ (
    .C(clk),
    .D(_023_),
    .Q(\mem[3] [1])
  );
  DFF _542_ (
    .C(clk),
    .D(_024_),
    .Q(\mem[3] [2])
  );
  DFF _543_ (
    .C(clk),
    .D(_025_),
    .Q(\mem[3] [3])
  );
  DFF _544_ (
    .C(clk),
    .D(_026_),
    .Q(\mem[3] [4])
  );
  DFF _545_ (
    .C(clk),
    .D(_027_),
    .Q(\mem[3] [5])
  );
  DFF _546_ (
    .C(clk),
    .D(_016_),
    .Q(\mem[2] [0])
  );
  DFF _547_ (
    .C(clk),
    .D(_017_),
    .Q(\mem[2] [1])
  );
  DFF _548_ (
    .C(clk),
    .D(_018_),
    .Q(\mem[2] [2])
  );
  DFF _549_ (
    .C(clk),
    .D(_019_),
    .Q(\mem[2] [3])
  );
  DFF _550_ (
    .C(clk),
    .D(_020_),
    .Q(\mem[2] [4])
  );
  DFF _551_ (
    .C(clk),
    .D(_021_),
    .Q(\mem[2] [5])
  );
  DFF _552_ (
    .C(clk),
    .D(_010_),
    .Q(\mem[1] [0])
  );
  DFF _553_ (
    .C(clk),
    .D(_011_),
    .Q(\mem[1] [1])
  );
  DFF _554_ (
    .C(clk),
    .D(_012_),
    .Q(\mem[1] [2])
  );
  DFF _555_ (
    .C(clk),
    .D(_013_),
    .Q(\mem[1] [3])
  );
  DFF _556_ (
    .C(clk),
    .D(_014_),
    .Q(\mem[1] [4])
  );
  DFF _557_ (
    .C(clk),
    .D(_015_),
    .Q(\mem[1] [5])
  );
  DFF _558_ (
    .C(clk),
    .D(_004_),
    .Q(\mem[0] [0])
  );
  DFF _559_ (
    .C(clk),
    .D(_005_),
    .Q(\mem[0] [1])
  );
  DFF _560_ (
    .C(clk),
    .D(_006_),
    .Q(\mem[0] [2])
  );
  DFF _561_ (
    .C(clk),
    .D(_007_),
    .Q(\mem[0] [3])
  );
  DFF _562_ (
    .C(clk),
    .D(_008_),
    .Q(\mem[0] [4])
  );
  DFF _563_ (
    .C(clk),
    .D(_009_),
    .Q(\mem[0] [5])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:62" *)
  DFF _564_ (
    .C(clk),
    .D(_000_[0]),
    .Q(cnt[0])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:62" *)
  DFF _565_ (
    .C(clk),
    .D(_000_[1]),
    .Q(cnt[1])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:62" *)
  DFF _566_ (
    .C(clk),
    .D(_000_[2]),
    .Q(cnt[2])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:47" *)
  DFF _567_ (
    .C(clk),
    .D(_001_[0]),
    .Q(data_out_D1_synth[0])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:47" *)
  DFF _568_ (
    .C(clk),
    .D(_001_[1]),
    .Q(data_out_D1_synth[1])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:47" *)
  DFF _569_ (
    .C(clk),
    .D(_001_[2]),
    .Q(data_out_D1_synth[2])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:47" *)
  DFF _570_ (
    .C(clk),
    .D(_001_[3]),
    .Q(data_out_D1_synth[3])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:47" *)
  DFF _571_ (
    .C(clk),
    .D(_001_[4]),
    .Q(data_out_D1_synth[4])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:47" *)
  DFF _572_ (
    .C(clk),
    .D(_001_[5]),
    .Q(data_out_D1_synth[5])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:31" *)
  DFF _573_ (
    .C(clk),
    .D(_003_[0]),
    .Q(wr_ptr[0])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:31" *)
  DFF _574_ (
    .C(clk),
    .D(_003_[1]),
    .Q(wr_ptr[1])
  );
  assign i = 32'd4;
endmodule

(* cells_not_processed =  1  *)
(* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:5" *)
module arbitro_enrutamiento_synth(VC0, VC1, clk, reset_L, VC0_empty, VC1_empty, D1_pause, D0_pause, VC1_pop, VC0_pop, D0_push, D1_push, D0_out, D1_out);
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:9" *)
  output [5:0] D0_out;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:7" *)
  input D0_pause;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:8" *)
  output D0_push;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:9" *)
  output [5:0] D1_out;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:7" *)
  input D1_pause;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:8" *)
  output D1_push;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:5" *)
  input [5:0] VC0;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:7" *)
  input VC0_empty;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:8" *)
  output VC0_pop;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:5" *)
  input [5:0] VC1;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:7" *)
  input VC1_empty;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:8" *)
  output VC1_pop;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:6" *)
  input clk;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:11" *)
  wire pop_delay_VC0;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:11" *)
  wire pop_delay_VC1;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:6" *)
  input reset_L;
  (* module_not_derived = 32'd1 *)
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:13" *)
  arbitro_mux_synth u_arbitro_mux_synthes (
    .D0_out(D0_out),
    .D0_push(D0_push),
    .D1_out(D1_out),
    .D1_push(D1_push),
    .VC0(VC0),
    .VC0_empty(VC0_empty),
    .VC1(VC1),
    .VC1_empty(VC1_empty),
    .clk(clk),
    .pop_delay_VC0(pop_delay_VC0),
    .pop_delay_VC1(pop_delay_VC1),
    .reset_L(reset_L)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:29" *)
  logica_pops_synth u_logica_pops_synth (
    .D0_pause(D0_pause),
    .D1_pause(D1_pause),
    .VC0_empty(VC0_empty),
    .VC0_pop(VC0_pop),
    .VC1_empty(VC1_empty),
    .VC1_pop(VC1_pop),
    .clk(clk),
    .pop_delay_VC0(pop_delay_VC0),
    .pop_delay_VC1(pop_delay_VC1),
    .reset_L(reset_L)
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:1" *)
module arbitro_mux_synth(reset_L, clk, VC0, VC1, pop_delay_VC0, pop_delay_VC1, VC0_empty, VC1_empty, D0_out, D1_out, D0_push, D1_push);
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  wire [5:0] _000_;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  wire _001_;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  wire [5:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:6" *)
  output [5:0] D0_out;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:7" *)
  output D0_push;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:6" *)
  output [5:0] D1_out;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:7" *)
  output D1_push;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:2" *)
  input [5:0] VC0;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:5" *)
  input VC0_empty;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:3" *)
  input [5:0] VC1;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:5" *)
  input VC1_empty;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:1" *)
  input clk;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:4" *)
  input pop_delay_VC0;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:4" *)
  input pop_delay_VC1;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:1" *)
  input reset_L;
  NOT _058_ (
    .A(VC1[4]),
    .Y(_003_)
  );
  NOT _059_ (
    .A(VC0[4]),
    .Y(_004_)
  );
  NOT _060_ (
    .A(reset_L),
    .Y(_005_)
  );
  NOT _061_ (
    .A(VC1[0]),
    .Y(_006_)
  );
  NOT _062_ (
    .A(VC1[1]),
    .Y(_007_)
  );
  NOT _063_ (
    .A(VC1[2]),
    .Y(_008_)
  );
  NOT _064_ (
    .A(VC1[3]),
    .Y(_009_)
  );
  NOT _065_ (
    .A(VC1[5]),
    .Y(_010_)
  );
  NOT _066_ (
    .A(VC0[0]),
    .Y(_011_)
  );
  NOT _067_ (
    .A(VC0[1]),
    .Y(_012_)
  );
  NOT _068_ (
    .A(VC0[2]),
    .Y(_013_)
  );
  NOT _069_ (
    .A(VC0[3]),
    .Y(_014_)
  );
  NOT _070_ (
    .A(VC0[5]),
    .Y(_015_)
  );
  NOR _071_ (
    .A(VC0_empty),
    .B(VC0[4]),
    .Y(_016_)
  );
  NAND _072_ (
    .A(pop_delay_VC0),
    .B(_016_),
    .Y(_017_)
  );
  NAND _073_ (
    .A(pop_delay_VC1),
    .B(VC0_empty),
    .Y(_018_)
  );
  NOR _074_ (
    .A(VC1_empty),
    .B(_018_),
    .Y(_019_)
  );
  NAND _075_ (
    .A(_003_),
    .B(_019_),
    .Y(_020_)
  );
  NAND _076_ (
    .A(_017_),
    .B(_020_),
    .Y(_021_)
  );
  NAND _077_ (
    .A(reset_L),
    .B(_021_),
    .Y(_022_)
  );
  NOT _078_ (
    .A(_022_),
    .Y(_001_)
  );
  NOR _079_ (
    .A(VC0_empty),
    .B(_004_),
    .Y(_023_)
  );
  NAND _080_ (
    .A(pop_delay_VC0),
    .B(_023_),
    .Y(_024_)
  );
  NOR _081_ (
    .A(_011_),
    .B(_024_),
    .Y(_025_)
  );
  NAND _082_ (
    .A(VC1[4]),
    .B(_019_),
    .Y(_026_)
  );
  NOR _083_ (
    .A(_006_),
    .B(_026_),
    .Y(_027_)
  );
  NOR _084_ (
    .A(_025_),
    .B(_027_),
    .Y(_028_)
  );
  NOR _085_ (
    .A(_005_),
    .B(_028_),
    .Y(_002_[0])
  );
  NOR _086_ (
    .A(_012_),
    .B(_024_),
    .Y(_029_)
  );
  NOR _087_ (
    .A(_007_),
    .B(_026_),
    .Y(_030_)
  );
  NOR _088_ (
    .A(_029_),
    .B(_030_),
    .Y(_031_)
  );
  NOR _089_ (
    .A(_005_),
    .B(_031_),
    .Y(_002_[1])
  );
  NOR _090_ (
    .A(_013_),
    .B(_024_),
    .Y(_032_)
  );
  NOR _091_ (
    .A(_008_),
    .B(_026_),
    .Y(_033_)
  );
  NOR _092_ (
    .A(_032_),
    .B(_033_),
    .Y(_034_)
  );
  NOR _093_ (
    .A(_005_),
    .B(_034_),
    .Y(_002_[2])
  );
  NOR _094_ (
    .A(_014_),
    .B(_024_),
    .Y(_035_)
  );
  NOR _095_ (
    .A(_009_),
    .B(_026_),
    .Y(_036_)
  );
  NOR _096_ (
    .A(_035_),
    .B(_036_),
    .Y(_037_)
  );
  NOR _097_ (
    .A(_005_),
    .B(_037_),
    .Y(_002_[3])
  );
  NAND _098_ (
    .A(_024_),
    .B(_026_),
    .Y(_038_)
  );
  NAND _099_ (
    .A(reset_L),
    .B(_038_),
    .Y(_039_)
  );
  NOT _100_ (
    .A(_039_),
    .Y(_002_[4])
  );
  NOR _101_ (
    .A(_015_),
    .B(_024_),
    .Y(_040_)
  );
  NOR _102_ (
    .A(_010_),
    .B(_026_),
    .Y(_041_)
  );
  NOR _103_ (
    .A(_040_),
    .B(_041_),
    .Y(_042_)
  );
  NOR _104_ (
    .A(_005_),
    .B(_042_),
    .Y(_002_[5])
  );
  NOR _105_ (
    .A(_011_),
    .B(_017_),
    .Y(_043_)
  );
  NOR _106_ (
    .A(_006_),
    .B(_020_),
    .Y(_044_)
  );
  NOR _107_ (
    .A(_043_),
    .B(_044_),
    .Y(_045_)
  );
  NOR _108_ (
    .A(_005_),
    .B(_045_),
    .Y(_000_[0])
  );
  NOR _109_ (
    .A(_012_),
    .B(_017_),
    .Y(_046_)
  );
  NOR _110_ (
    .A(_007_),
    .B(_020_),
    .Y(_047_)
  );
  NOR _111_ (
    .A(_046_),
    .B(_047_),
    .Y(_048_)
  );
  NOR _112_ (
    .A(_005_),
    .B(_048_),
    .Y(_000_[1])
  );
  NOR _113_ (
    .A(_013_),
    .B(_017_),
    .Y(_049_)
  );
  NOR _114_ (
    .A(_008_),
    .B(_020_),
    .Y(_050_)
  );
  NOR _115_ (
    .A(_049_),
    .B(_050_),
    .Y(_051_)
  );
  NOR _116_ (
    .A(_005_),
    .B(_051_),
    .Y(_000_[2])
  );
  NOR _117_ (
    .A(_014_),
    .B(_017_),
    .Y(_052_)
  );
  NOR _118_ (
    .A(_009_),
    .B(_020_),
    .Y(_053_)
  );
  NOR _119_ (
    .A(_052_),
    .B(_053_),
    .Y(_054_)
  );
  NOR _120_ (
    .A(_005_),
    .B(_054_),
    .Y(_000_[3])
  );
  NOR _121_ (
    .A(_015_),
    .B(_017_),
    .Y(_055_)
  );
  NOR _122_ (
    .A(_010_),
    .B(_020_),
    .Y(_056_)
  );
  NOR _123_ (
    .A(_055_),
    .B(_056_),
    .Y(_057_)
  );
  NOR _124_ (
    .A(_005_),
    .B(_057_),
    .Y(_000_[5])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _125_ (
    .C(clk),
    .D(_000_[0]),
    .Q(D0_out[0])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _126_ (
    .C(clk),
    .D(_000_[1]),
    .Q(D0_out[1])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _127_ (
    .C(clk),
    .D(_000_[2]),
    .Q(D0_out[2])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _128_ (
    .C(clk),
    .D(_000_[3]),
    .Q(D0_out[3])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _129_ (
    .C(clk),
    .D(_000_[5]),
    .Q(D0_out[5])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _130_ (
    .C(clk),
    .D(_002_[0]),
    .Q(D1_out[0])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _131_ (
    .C(clk),
    .D(_002_[1]),
    .Q(D1_out[1])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _132_ (
    .C(clk),
    .D(_002_[2]),
    .Q(D1_out[2])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _133_ (
    .C(clk),
    .D(_002_[3]),
    .Q(D1_out[3])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _134_ (
    .C(clk),
    .D(_002_[5]),
    .Q(D1_out[5])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _135_ (
    .C(clk),
    .D(_001_),
    .Q(D0_push)
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _136_ (
    .C(clk),
    .D(_002_[4]),
    .Q(D1_push)
  );
  assign _000_[4] = 1'h0;
  assign D0_out[4] = 1'h0;
  assign D1_out[4] = D1_push;
endmodule

(* cells_not_processed =  1  *)
(* src = "./final_logic_synth/final_logic_synth.v:5" *)
module final_logic_synth(data_out_VC0, data_out_VC1, clk, reset_L, empty_fifo_VC0, empty_fifo_VC1, D0_pop, D1_pop, data_out_D0_synth, data_out_D1_synth, pop_VC0_fifo_synth, pop_VC1_fifo_synth, error_D1_synth, error_D0_synth);
  (* src = "./final_logic_synth/final_logic_synth.v:17" *)
  wire [5:0] D0_out;
  (* src = "./final_logic_synth/final_logic_synth.v:11" *)
  input D0_pop;
  (* src = "./final_logic_synth/final_logic_synth.v:16" *)
  wire D0_push;
  (* src = "./final_logic_synth/final_logic_synth.v:17" *)
  wire [5:0] D1_out;
  (* src = "./final_logic_synth/final_logic_synth.v:11" *)
  input D1_pop;
  (* src = "./final_logic_synth/final_logic_synth.v:16" *)
  wire D1_push;
  (* src = "./final_logic_synth/final_logic_synth.v:45" *)
  (* unused_bits = "0" *)
  wire almost_empty_fifo_D0;
  (* src = "./final_logic_synth/final_logic_synth.v:59" *)
  (* unused_bits = "0" *)
  wire almost_empty_fifo_D1;
  (* src = "./final_logic_synth/final_logic_synth.v:10" *)
  input clk;
  (* src = "./final_logic_synth/final_logic_synth.v:12" *)
  output [5:0] data_out_D0_synth;
  (* src = "./final_logic_synth/final_logic_synth.v:12" *)
  output [5:0] data_out_D1_synth;
  (* src = "./final_logic_synth/final_logic_synth.v:9" *)
  input [5:0] data_out_VC0;
  (* src = "./final_logic_synth/final_logic_synth.v:9" *)
  input [5:0] data_out_VC1;
  (* src = "./final_logic_synth/final_logic_synth.v:43" *)
  (* unused_bits = "0" *)
  wire empty_fifo_D0;
  (* src = "./final_logic_synth/final_logic_synth.v:57" *)
  (* unused_bits = "0" *)
  wire empty_fifo_D1;
  (* src = "./final_logic_synth/final_logic_synth.v:10" *)
  input empty_fifo_VC0;
  (* src = "./final_logic_synth/final_logic_synth.v:10" *)
  input empty_fifo_VC1;
  (* src = "./final_logic_synth/final_logic_synth.v:14" *)
  output error_D0_synth;
  (* src = "./final_logic_synth/final_logic_synth.v:14" *)
  output error_D1_synth;
  (* src = "./final_logic_synth/final_logic_synth.v:42" *)
  (* unused_bits = "0" *)
  wire full_fifo_D0;
  (* src = "./final_logic_synth/final_logic_synth.v:56" *)
  (* unused_bits = "0" *)
  wire full_fifo_D1;
  (* src = "./final_logic_synth/final_logic_synth.v:16" *)
  wire fulloralmostfull_D0;
  (* src = "./final_logic_synth/final_logic_synth.v:16" *)
  wire fulloralmostfull_D1;
  (* src = "./final_logic_synth/final_logic_synth.v:13" *)
  output pop_VC0_fifo_synth;
  (* src = "./final_logic_synth/final_logic_synth.v:13" *)
  output pop_VC1_fifo_synth;
  (* src = "./final_logic_synth/final_logic_synth.v:10" *)
  input reset_L;
  (* module_not_derived = 32'd1 *)
  (* src = "./final_logic_synth/final_logic_synth.v:36" *)
  D0_fifo_synth u_D0_fifo_synth (
    .almost_empty_fifo_D0(almost_empty_fifo_D0),
    .almost_full_fifo_D0(fulloralmostfull_D0),
    .clk(clk),
    .data_in(D0_out),
    .data_out_D0_synth(data_out_D0_synth),
    .empty_fifo_D0(empty_fifo_D0),
    .error_D0_synth(error_D0_synth),
    .full_fifo_D0(full_fifo_D0),
    .rd_enable(D0_pop),
    .reset_L(reset_L),
    .wr_enable(D0_push)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./final_logic_synth/final_logic_synth.v:50" *)
  D1_fifo_synth u_D1_fifo_synth (
    .almost_empty_fifo_D1(almost_empty_fifo_D1),
    .almost_full_fifo_D1(fulloralmostfull_D1),
    .clk(clk),
    .data_in(D1_out),
    .data_out_D1_synth(data_out_D1_synth),
    .empty_fifo_D1(empty_fifo_D1),
    .error_D1_synth(error_D1_synth),
    .full_fifo_D1(full_fifo_D1),
    .rd_enable(D1_pop),
    .reset_L(reset_L),
    .wr_enable(D1_push)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./final_logic_synth/final_logic_synth.v:19" *)
  arbitro_enrutamiento_synth u_arbitro_enrutamiento_synth (
    .D0_out(D0_out),
    .D0_pause(fulloralmostfull_D0),
    .D0_push(D0_push),
    .D1_out(D1_out),
    .D1_pause(fulloralmostfull_D1),
    .D1_push(D1_push),
    .VC0(data_out_VC0),
    .VC0_empty(empty_fifo_VC0),
    .VC0_pop(pop_VC0_fifo_synth),
    .VC1(data_out_VC1),
    .VC1_empty(empty_fifo_VC1),
    .VC1_pop(pop_VC1_fifo_synth),
    .clk(clk),
    .reset_L(reset_L)
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
module logica_pops_synth(VC0_empty, VC1_empty, D0_pause, D1_pause, clk, reset_L, VC0_pop, VC1_pop, pop_delay_VC0, pop_delay_VC1);
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:4" *)
  wire _00_;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:4" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
  input D0_pause;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
  input D1_pause;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
  input VC0_empty;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:2" *)
  output VC0_pop;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
  input VC1_empty;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:2" *)
  output VC1_pop;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
  input clk;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:2" *)
  output pop_delay_VC0;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:2" *)
  output pop_delay_VC1;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
  input reset_L;
  NOT _08_ (
    .A(reset_L),
    .Y(_02_)
  );
  NOT _09_ (
    .A(VC1_empty),
    .Y(_03_)
  );
  NOT _10_ (
    .A(D1_pause),
    .Y(_04_)
  );
  NOR _11_ (
    .A(_02_),
    .B(D0_pause),
    .Y(_05_)
  );
  NAND _12_ (
    .A(_04_),
    .B(_05_),
    .Y(_06_)
  );
  NAND _13_ (
    .A(VC0_empty),
    .B(_03_),
    .Y(_07_)
  );
  NOR _14_ (
    .A(_06_),
    .B(_07_),
    .Y(VC1_pop)
  );
  NOR _15_ (
    .A(VC0_empty),
    .B(_06_),
    .Y(VC0_pop)
  );
  NOR _16_ (
    .A(_06_),
    .B(_07_),
    .Y(_01_)
  );
  NOR _17_ (
    .A(VC0_empty),
    .B(_06_),
    .Y(_00_)
  );
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:4" *)
  DFF _18_ (
    .C(clk),
    .D(_00_),
    .Q(pop_delay_VC0)
  );
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:4" *)
  DFF _19_ (
    .C(clk),
    .D(_01_),
    .Q(pop_delay_VC1)
  );
endmodule
