/* Generated by Yosys 0.9 (git sha1 UNKNOWN, gcc 10.2.0 -march=x86-64 -mtune=generic -O2 -fno-plt -fPIC -Os) */

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "./final_logic_synth/D0_fifo_synth.v:1" *)
module D0_fifo_synth(clk, reset_L, wr_enable, rd_enable, data_in, full_fifo_D0, empty_fifo_D0, almost_full_fifo_D0, almost_empty_fifo_D0, error_D0_synth, data_out_D0_synth);
  (* src = "./final_logic_synth/D0_fifo_synth.v:58" *)
  wire [2:0] _000_;
  (* src = "./final_logic_synth/D0_fifo_synth.v:43" *)
  wire [5:0] _001_;
  (* src = "./final_logic_synth/D0_fifo_synth.v:43" *)
  wire [1:0] _002_;
  (* src = "./final_logic_synth/D0_fifo_synth.v:30" *)
  wire [1:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  (* src = "./final_logic_synth/D0_fifo_synth.v:11" *)
  output almost_empty_fifo_D0;
  (* src = "./final_logic_synth/D0_fifo_synth.v:10" *)
  output almost_full_fifo_D0;
  (* src = "./final_logic_synth/D0_fifo_synth.v:6" *)
  input clk;
  (* src = "./final_logic_synth/D0_fifo_synth.v:20" *)
  wire [2:0] cnt;
  (* src = "./final_logic_synth/D0_fifo_synth.v:7" *)
  input [5:0] data_in;
  (* src = "./final_logic_synth/D0_fifo_synth.v:13" *)
  output [5:0] data_out_D0_synth;
  (* src = "./final_logic_synth/D0_fifo_synth.v:9" *)
  output empty_fifo_D0;
  (* src = "./final_logic_synth/D0_fifo_synth.v:12" *)
  output error_D0_synth;
  (* src = "./final_logic_synth/D0_fifo_synth.v:8" *)
  output full_fifo_D0;
  wire [5:0] \mem[0] ;
  wire [5:0] \mem[1] ;
  wire [5:0] \mem[2] ;
  wire [5:0] \mem[3] ;
  (* src = "./final_logic_synth/D0_fifo_synth.v:6" *)
  input rd_enable;
  (* src = "./final_logic_synth/D0_fifo_synth.v:19" *)
  wire [1:0] rd_ptr;
  (* src = "./final_logic_synth/D0_fifo_synth.v:6" *)
  input reset_L;
  (* src = "./final_logic_synth/D0_fifo_synth.v:6" *)
  input wr_enable;
  (* src = "./final_logic_synth/D0_fifo_synth.v:18" *)
  wire [1:0] wr_ptr;
  NOT _219_ (
    .A(cnt[1]),
    .Y(_202_)
  );
  NOT _220_ (
    .A(cnt[2]),
    .Y(_203_)
  );
  NOT _221_ (
    .A(rd_enable),
    .Y(_204_)
  );
  NOT _222_ (
    .A(wr_enable),
    .Y(_205_)
  );
  NOT _223_ (
    .A(reset_L),
    .Y(_206_)
  );
  NOT _224_ (
    .A(rd_ptr[1]),
    .Y(_207_)
  );
  NOT _225_ (
    .A(wr_ptr[0]),
    .Y(_208_)
  );
  NOT _226_ (
    .A(wr_ptr[1]),
    .Y(_209_)
  );
  NOT _227_ (
    .A(\mem[3] [0]),
    .Y(_210_)
  );
  NOT _228_ (
    .A(\mem[3] [1]),
    .Y(_211_)
  );
  NOT _229_ (
    .A(\mem[3] [2]),
    .Y(_212_)
  );
  NOT _230_ (
    .A(\mem[3] [3]),
    .Y(_213_)
  );
  NOT _231_ (
    .A(\mem[3] [4]),
    .Y(_214_)
  );
  NOT _232_ (
    .A(\mem[3] [5]),
    .Y(_215_)
  );
  NOT _233_ (
    .A(\mem[0] [0]),
    .Y(_216_)
  );
  NOT _234_ (
    .A(\mem[0] [1]),
    .Y(_217_)
  );
  NOT _235_ (
    .A(\mem[0] [2]),
    .Y(_218_)
  );
  NOT _236_ (
    .A(\mem[0] [3]),
    .Y(_028_)
  );
  NOT _237_ (
    .A(\mem[0] [4]),
    .Y(_029_)
  );
  NOT _238_ (
    .A(\mem[0] [5]),
    .Y(_030_)
  );
  NOR _239_ (
    .A(cnt[1]),
    .B(cnt[0]),
    .Y(_031_)
  );
  NOT _240_ (
    .A(_031_),
    .Y(_032_)
  );
  NAND _241_ (
    .A(cnt[2]),
    .B(_031_),
    .Y(_033_)
  );
  NOT _242_ (
    .A(_033_),
    .Y(full_fifo_D0)
  );
  NOR _243_ (
    .A(cnt[2]),
    .B(_032_),
    .Y(empty_fifo_D0)
  );
  NAND _244_ (
    .A(_203_),
    .B(cnt[0]),
    .Y(_034_)
  );
  NOR _245_ (
    .A(cnt[1]),
    .B(_034_),
    .Y(almost_empty_fifo_D0)
  );
  NAND _246_ (
    .A(cnt[1]),
    .B(cnt[0]),
    .Y(_035_)
  );
  NOT _247_ (
    .A(_035_),
    .Y(_036_)
  );
  NOR _248_ (
    .A(cnt[2]),
    .B(_035_),
    .Y(almost_full_fifo_D0)
  );
  NOR _249_ (
    .A(_205_),
    .B(_206_),
    .Y(_037_)
  );
  NAND _250_ (
    .A(wr_enable),
    .B(reset_L),
    .Y(_038_)
  );
  NOR _251_ (
    .A(_209_),
    .B(_038_),
    .Y(_039_)
  );
  NAND _252_ (
    .A(wr_ptr[1]),
    .B(_037_),
    .Y(_040_)
  );
  NOR _253_ (
    .A(wr_ptr[0]),
    .B(_040_),
    .Y(_041_)
  );
  NAND _254_ (
    .A(_208_),
    .B(_039_),
    .Y(_042_)
  );
  NAND _255_ (
    .A(data_in[0]),
    .B(_041_),
    .Y(_043_)
  );
  NAND _256_ (
    .A(\mem[2] [0]),
    .B(_042_),
    .Y(_044_)
  );
  NAND _257_ (
    .A(_043_),
    .B(_044_),
    .Y(_016_)
  );
  NAND _258_ (
    .A(data_in[1]),
    .B(_041_),
    .Y(_045_)
  );
  NAND _259_ (
    .A(\mem[2] [1]),
    .B(_042_),
    .Y(_046_)
  );
  NAND _260_ (
    .A(_045_),
    .B(_046_),
    .Y(_017_)
  );
  NAND _261_ (
    .A(data_in[2]),
    .B(_041_),
    .Y(_047_)
  );
  NAND _262_ (
    .A(\mem[2] [2]),
    .B(_042_),
    .Y(_048_)
  );
  NAND _263_ (
    .A(_047_),
    .B(_048_),
    .Y(_018_)
  );
  NAND _264_ (
    .A(data_in[3]),
    .B(_041_),
    .Y(_049_)
  );
  NAND _265_ (
    .A(\mem[2] [3]),
    .B(_042_),
    .Y(_050_)
  );
  NAND _266_ (
    .A(_049_),
    .B(_050_),
    .Y(_019_)
  );
  NAND _267_ (
    .A(data_in[4]),
    .B(_041_),
    .Y(_051_)
  );
  NAND _268_ (
    .A(\mem[2] [4]),
    .B(_042_),
    .Y(_052_)
  );
  NAND _269_ (
    .A(_051_),
    .B(_052_),
    .Y(_020_)
  );
  NAND _270_ (
    .A(data_in[5]),
    .B(_041_),
    .Y(_053_)
  );
  NAND _271_ (
    .A(\mem[2] [5]),
    .B(_042_),
    .Y(_054_)
  );
  NAND _272_ (
    .A(_053_),
    .B(_054_),
    .Y(_021_)
  );
  NOR _273_ (
    .A(rd_enable),
    .B(_205_),
    .Y(_055_)
  );
  NAND _274_ (
    .A(_204_),
    .B(wr_enable),
    .Y(_056_)
  );
  NOR _275_ (
    .A(_204_),
    .B(wr_enable),
    .Y(_057_)
  );
  NAND _276_ (
    .A(rd_enable),
    .B(_205_),
    .Y(_058_)
  );
  NAND _277_ (
    .A(_056_),
    .B(_058_),
    .Y(_059_)
  );
  NAND _278_ (
    .A(cnt[0]),
    .B(_059_),
    .Y(_060_)
  );
  NOT _279_ (
    .A(_060_),
    .Y(_061_)
  );
  NOR _280_ (
    .A(cnt[0]),
    .B(_059_),
    .Y(_062_)
  );
  NOT _281_ (
    .A(_062_),
    .Y(_063_)
  );
  NAND _282_ (
    .A(reset_L),
    .B(_063_),
    .Y(_064_)
  );
  NOR _283_ (
    .A(_061_),
    .B(_064_),
    .Y(_000_[0])
  );
  NOR _284_ (
    .A(_202_),
    .B(_059_),
    .Y(_065_)
  );
  NOR _285_ (
    .A(_031_),
    .B(_036_),
    .Y(_066_)
  );
  NAND _286_ (
    .A(_032_),
    .B(_035_),
    .Y(_067_)
  );
  NOR _287_ (
    .A(_055_),
    .B(_067_),
    .Y(_068_)
  );
  NOR _288_ (
    .A(_057_),
    .B(_066_),
    .Y(_069_)
  );
  NOR _289_ (
    .A(_068_),
    .B(_069_),
    .Y(_070_)
  );
  NOR _290_ (
    .A(_065_),
    .B(_070_),
    .Y(_071_)
  );
  NOR _291_ (
    .A(_206_),
    .B(_071_),
    .Y(_000_[1])
  );
  NOR _292_ (
    .A(_203_),
    .B(_031_),
    .Y(error_D0_synth)
  );
  NOR _293_ (
    .A(empty_fifo_D0),
    .B(error_D0_synth),
    .Y(_072_)
  );
  NOR _294_ (
    .A(_058_),
    .B(_072_),
    .Y(_073_)
  );
  NOR _295_ (
    .A(_035_),
    .B(_056_),
    .Y(_074_)
  );
  NAND _296_ (
    .A(_036_),
    .B(_055_),
    .Y(_075_)
  );
  NOR _297_ (
    .A(_203_),
    .B(_075_),
    .Y(_076_)
  );
  NOR _298_ (
    .A(_203_),
    .B(_057_),
    .Y(_077_)
  );
  NOR _299_ (
    .A(_074_),
    .B(_077_),
    .Y(_078_)
  );
  NOR _300_ (
    .A(_076_),
    .B(_078_),
    .Y(_079_)
  );
  NOR _301_ (
    .A(_073_),
    .B(_079_),
    .Y(_080_)
  );
  NOR _302_ (
    .A(_206_),
    .B(_080_),
    .Y(_000_[2])
  );
  NAND _303_ (
    .A(rd_enable),
    .B(rd_ptr[0]),
    .Y(_081_)
  );
  NOT _304_ (
    .A(_081_),
    .Y(_082_)
  );
  NOR _305_ (
    .A(rd_enable),
    .B(rd_ptr[0]),
    .Y(_083_)
  );
  NOT _306_ (
    .A(_083_),
    .Y(_084_)
  );
  NAND _307_ (
    .A(reset_L),
    .B(_084_),
    .Y(_085_)
  );
  NOR _308_ (
    .A(_082_),
    .B(_085_),
    .Y(_002_[0])
  );
  NOR _309_ (
    .A(_207_),
    .B(_081_),
    .Y(_086_)
  );
  NAND _310_ (
    .A(_207_),
    .B(_081_),
    .Y(_087_)
  );
  NAND _311_ (
    .A(reset_L),
    .B(_087_),
    .Y(_088_)
  );
  NOR _312_ (
    .A(_086_),
    .B(_088_),
    .Y(_002_[1])
  );
  NAND _313_ (
    .A(rd_enable),
    .B(reset_L),
    .Y(_089_)
  );
  NOR _314_ (
    .A(\mem[2] [0]),
    .B(rd_ptr[0]),
    .Y(_090_)
  );
  NAND _315_ (
    .A(rd_ptr[0]),
    .B(_210_),
    .Y(_091_)
  );
  NAND _316_ (
    .A(rd_ptr[1]),
    .B(_091_),
    .Y(_092_)
  );
  NOR _317_ (
    .A(_090_),
    .B(_092_),
    .Y(_093_)
  );
  NAND _318_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [0]),
    .Y(_094_)
  );
  NOT _319_ (
    .A(_094_),
    .Y(_095_)
  );
  NOR _320_ (
    .A(rd_ptr[0]),
    .B(_216_),
    .Y(_096_)
  );
  NOR _321_ (
    .A(_095_),
    .B(_096_),
    .Y(_097_)
  );
  NOR _322_ (
    .A(rd_ptr[1]),
    .B(_097_),
    .Y(_098_)
  );
  NOR _323_ (
    .A(_093_),
    .B(_098_),
    .Y(_099_)
  );
  NOR _324_ (
    .A(_089_),
    .B(_099_),
    .Y(_001_[0])
  );
  NOR _325_ (
    .A(\mem[2] [1]),
    .B(rd_ptr[0]),
    .Y(_100_)
  );
  NAND _326_ (
    .A(rd_ptr[0]),
    .B(_211_),
    .Y(_101_)
  );
  NAND _327_ (
    .A(rd_ptr[1]),
    .B(_101_),
    .Y(_102_)
  );
  NOR _328_ (
    .A(_100_),
    .B(_102_),
    .Y(_103_)
  );
  NAND _329_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [1]),
    .Y(_104_)
  );
  NOT _330_ (
    .A(_104_),
    .Y(_105_)
  );
  NOR _331_ (
    .A(rd_ptr[0]),
    .B(_217_),
    .Y(_106_)
  );
  NOR _332_ (
    .A(_105_),
    .B(_106_),
    .Y(_107_)
  );
  NOR _333_ (
    .A(rd_ptr[1]),
    .B(_107_),
    .Y(_108_)
  );
  NOR _334_ (
    .A(_103_),
    .B(_108_),
    .Y(_109_)
  );
  NOR _335_ (
    .A(_089_),
    .B(_109_),
    .Y(_001_[1])
  );
  NOR _336_ (
    .A(\mem[2] [2]),
    .B(rd_ptr[0]),
    .Y(_110_)
  );
  NAND _337_ (
    .A(rd_ptr[0]),
    .B(_212_),
    .Y(_111_)
  );
  NAND _338_ (
    .A(rd_ptr[1]),
    .B(_111_),
    .Y(_112_)
  );
  NOR _339_ (
    .A(_110_),
    .B(_112_),
    .Y(_113_)
  );
  NAND _340_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [2]),
    .Y(_114_)
  );
  NOT _341_ (
    .A(_114_),
    .Y(_115_)
  );
  NOR _342_ (
    .A(rd_ptr[0]),
    .B(_218_),
    .Y(_116_)
  );
  NOR _343_ (
    .A(_115_),
    .B(_116_),
    .Y(_117_)
  );
  NOR _344_ (
    .A(rd_ptr[1]),
    .B(_117_),
    .Y(_118_)
  );
  NOR _345_ (
    .A(_113_),
    .B(_118_),
    .Y(_119_)
  );
  NOR _346_ (
    .A(_089_),
    .B(_119_),
    .Y(_001_[2])
  );
  NOR _347_ (
    .A(\mem[2] [3]),
    .B(rd_ptr[0]),
    .Y(_120_)
  );
  NAND _348_ (
    .A(rd_ptr[0]),
    .B(_213_),
    .Y(_121_)
  );
  NAND _349_ (
    .A(rd_ptr[1]),
    .B(_121_),
    .Y(_122_)
  );
  NOR _350_ (
    .A(_120_),
    .B(_122_),
    .Y(_123_)
  );
  NAND _351_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [3]),
    .Y(_124_)
  );
  NOT _352_ (
    .A(_124_),
    .Y(_125_)
  );
  NOR _353_ (
    .A(rd_ptr[0]),
    .B(_028_),
    .Y(_126_)
  );
  NOR _354_ (
    .A(_125_),
    .B(_126_),
    .Y(_127_)
  );
  NOR _355_ (
    .A(rd_ptr[1]),
    .B(_127_),
    .Y(_128_)
  );
  NOR _356_ (
    .A(_123_),
    .B(_128_),
    .Y(_129_)
  );
  NOR _357_ (
    .A(_089_),
    .B(_129_),
    .Y(_001_[3])
  );
  NOR _358_ (
    .A(\mem[2] [4]),
    .B(rd_ptr[0]),
    .Y(_130_)
  );
  NAND _359_ (
    .A(rd_ptr[0]),
    .B(_214_),
    .Y(_131_)
  );
  NAND _360_ (
    .A(rd_ptr[1]),
    .B(_131_),
    .Y(_132_)
  );
  NOR _361_ (
    .A(_130_),
    .B(_132_),
    .Y(_133_)
  );
  NAND _362_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [4]),
    .Y(_134_)
  );
  NOT _363_ (
    .A(_134_),
    .Y(_135_)
  );
  NOR _364_ (
    .A(rd_ptr[0]),
    .B(_029_),
    .Y(_136_)
  );
  NOR _365_ (
    .A(_135_),
    .B(_136_),
    .Y(_137_)
  );
  NOR _366_ (
    .A(rd_ptr[1]),
    .B(_137_),
    .Y(_138_)
  );
  NOR _367_ (
    .A(_133_),
    .B(_138_),
    .Y(_139_)
  );
  NOR _368_ (
    .A(_089_),
    .B(_139_),
    .Y(_001_[4])
  );
  NOR _369_ (
    .A(\mem[2] [5]),
    .B(rd_ptr[0]),
    .Y(_140_)
  );
  NAND _370_ (
    .A(rd_ptr[0]),
    .B(_215_),
    .Y(_141_)
  );
  NAND _371_ (
    .A(rd_ptr[1]),
    .B(_141_),
    .Y(_142_)
  );
  NOR _372_ (
    .A(_140_),
    .B(_142_),
    .Y(_143_)
  );
  NAND _373_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [5]),
    .Y(_144_)
  );
  NOT _374_ (
    .A(_144_),
    .Y(_145_)
  );
  NOR _375_ (
    .A(rd_ptr[0]),
    .B(_030_),
    .Y(_146_)
  );
  NOR _376_ (
    .A(_145_),
    .B(_146_),
    .Y(_147_)
  );
  NOR _377_ (
    .A(rd_ptr[1]),
    .B(_147_),
    .Y(_148_)
  );
  NOR _378_ (
    .A(_143_),
    .B(_148_),
    .Y(_149_)
  );
  NOR _379_ (
    .A(_089_),
    .B(_149_),
    .Y(_001_[5])
  );
  NOR _380_ (
    .A(_205_),
    .B(_208_),
    .Y(_150_)
  );
  NOR _381_ (
    .A(wr_enable),
    .B(wr_ptr[0]),
    .Y(_151_)
  );
  NOT _382_ (
    .A(_151_),
    .Y(_152_)
  );
  NAND _383_ (
    .A(reset_L),
    .B(_152_),
    .Y(_153_)
  );
  NOR _384_ (
    .A(_150_),
    .B(_153_),
    .Y(_003_[0])
  );
  NOR _385_ (
    .A(wr_ptr[1]),
    .B(_150_),
    .Y(_154_)
  );
  NOT _386_ (
    .A(_154_),
    .Y(_155_)
  );
  NAND _387_ (
    .A(wr_ptr[1]),
    .B(_150_),
    .Y(_156_)
  );
  NAND _388_ (
    .A(reset_L),
    .B(_156_),
    .Y(_157_)
  );
  NOR _389_ (
    .A(_154_),
    .B(_157_),
    .Y(_003_[1])
  );
  NOR _390_ (
    .A(_206_),
    .B(_156_),
    .Y(_158_)
  );
  NAND _391_ (
    .A(wr_ptr[0]),
    .B(_039_),
    .Y(_159_)
  );
  NAND _392_ (
    .A(data_in[0]),
    .B(_158_),
    .Y(_160_)
  );
  NAND _393_ (
    .A(\mem[3] [0]),
    .B(_159_),
    .Y(_161_)
  );
  NAND _394_ (
    .A(_160_),
    .B(_161_),
    .Y(_022_)
  );
  NAND _395_ (
    .A(data_in[1]),
    .B(_158_),
    .Y(_162_)
  );
  NAND _396_ (
    .A(\mem[3] [1]),
    .B(_159_),
    .Y(_163_)
  );
  NAND _397_ (
    .A(_162_),
    .B(_163_),
    .Y(_023_)
  );
  NAND _398_ (
    .A(data_in[2]),
    .B(_158_),
    .Y(_164_)
  );
  NAND _399_ (
    .A(\mem[3] [2]),
    .B(_159_),
    .Y(_165_)
  );
  NAND _400_ (
    .A(_164_),
    .B(_165_),
    .Y(_024_)
  );
  NAND _401_ (
    .A(data_in[3]),
    .B(_158_),
    .Y(_166_)
  );
  NAND _402_ (
    .A(\mem[3] [3]),
    .B(_159_),
    .Y(_167_)
  );
  NAND _403_ (
    .A(_166_),
    .B(_167_),
    .Y(_025_)
  );
  NAND _404_ (
    .A(data_in[4]),
    .B(_158_),
    .Y(_168_)
  );
  NAND _405_ (
    .A(\mem[3] [4]),
    .B(_159_),
    .Y(_169_)
  );
  NAND _406_ (
    .A(_168_),
    .B(_169_),
    .Y(_026_)
  );
  NAND _407_ (
    .A(data_in[5]),
    .B(_158_),
    .Y(_170_)
  );
  NAND _408_ (
    .A(\mem[3] [5]),
    .B(_159_),
    .Y(_171_)
  );
  NAND _409_ (
    .A(_170_),
    .B(_171_),
    .Y(_027_)
  );
  NAND _410_ (
    .A(wr_ptr[0]),
    .B(_209_),
    .Y(_172_)
  );
  NOR _411_ (
    .A(_206_),
    .B(wr_ptr[1]),
    .Y(_173_)
  );
  NOR _412_ (
    .A(_038_),
    .B(_172_),
    .Y(_174_)
  );
  NAND _413_ (
    .A(_150_),
    .B(_173_),
    .Y(_175_)
  );
  NAND _414_ (
    .A(data_in[0]),
    .B(_174_),
    .Y(_176_)
  );
  NAND _415_ (
    .A(\mem[1] [0]),
    .B(_175_),
    .Y(_177_)
  );
  NAND _416_ (
    .A(_176_),
    .B(_177_),
    .Y(_010_)
  );
  NAND _417_ (
    .A(data_in[1]),
    .B(_174_),
    .Y(_178_)
  );
  NAND _418_ (
    .A(\mem[1] [1]),
    .B(_175_),
    .Y(_179_)
  );
  NAND _419_ (
    .A(_178_),
    .B(_179_),
    .Y(_011_)
  );
  NAND _420_ (
    .A(data_in[2]),
    .B(_174_),
    .Y(_180_)
  );
  NAND _421_ (
    .A(\mem[1] [2]),
    .B(_175_),
    .Y(_181_)
  );
  NAND _422_ (
    .A(_180_),
    .B(_181_),
    .Y(_012_)
  );
  NAND _423_ (
    .A(data_in[3]),
    .B(_174_),
    .Y(_182_)
  );
  NAND _424_ (
    .A(\mem[1] [3]),
    .B(_175_),
    .Y(_183_)
  );
  NAND _425_ (
    .A(_182_),
    .B(_183_),
    .Y(_013_)
  );
  NAND _426_ (
    .A(data_in[4]),
    .B(_174_),
    .Y(_184_)
  );
  NAND _427_ (
    .A(\mem[1] [4]),
    .B(_175_),
    .Y(_185_)
  );
  NAND _428_ (
    .A(_184_),
    .B(_185_),
    .Y(_014_)
  );
  NAND _429_ (
    .A(data_in[5]),
    .B(_174_),
    .Y(_186_)
  );
  NAND _430_ (
    .A(\mem[1] [5]),
    .B(_175_),
    .Y(_187_)
  );
  NAND _431_ (
    .A(_186_),
    .B(_187_),
    .Y(_015_)
  );
  NOR _432_ (
    .A(_038_),
    .B(_155_),
    .Y(_188_)
  );
  NAND _433_ (
    .A(_037_),
    .B(_154_),
    .Y(_189_)
  );
  NOR _434_ (
    .A(\mem[0] [0]),
    .B(_188_),
    .Y(_190_)
  );
  NOR _435_ (
    .A(data_in[0]),
    .B(_189_),
    .Y(_191_)
  );
  NOR _436_ (
    .A(_190_),
    .B(_191_),
    .Y(_004_)
  );
  NOR _437_ (
    .A(\mem[0] [1]),
    .B(_188_),
    .Y(_192_)
  );
  NOR _438_ (
    .A(data_in[1]),
    .B(_189_),
    .Y(_193_)
  );
  NOR _439_ (
    .A(_192_),
    .B(_193_),
    .Y(_005_)
  );
  NOR _440_ (
    .A(\mem[0] [2]),
    .B(_188_),
    .Y(_194_)
  );
  NOR _441_ (
    .A(data_in[2]),
    .B(_189_),
    .Y(_195_)
  );
  NOR _442_ (
    .A(_194_),
    .B(_195_),
    .Y(_006_)
  );
  NOR _443_ (
    .A(\mem[0] [3]),
    .B(_188_),
    .Y(_196_)
  );
  NOR _444_ (
    .A(data_in[3]),
    .B(_189_),
    .Y(_197_)
  );
  NOR _445_ (
    .A(_196_),
    .B(_197_),
    .Y(_007_)
  );
  NOR _446_ (
    .A(\mem[0] [4]),
    .B(_188_),
    .Y(_198_)
  );
  NOR _447_ (
    .A(data_in[4]),
    .B(_189_),
    .Y(_199_)
  );
  NOR _448_ (
    .A(_198_),
    .B(_199_),
    .Y(_008_)
  );
  NOR _449_ (
    .A(\mem[0] [5]),
    .B(_188_),
    .Y(_200_)
  );
  NOR _450_ (
    .A(data_in[5]),
    .B(_189_),
    .Y(_201_)
  );
  NOR _451_ (
    .A(_200_),
    .B(_201_),
    .Y(_009_)
  );
  DFF _452_ (
    .C(clk),
    .D(_010_),
    .Q(\mem[1] [0])
  );
  DFF _453_ (
    .C(clk),
    .D(_011_),
    .Q(\mem[1] [1])
  );
  DFF _454_ (
    .C(clk),
    .D(_012_),
    .Q(\mem[1] [2])
  );
  DFF _455_ (
    .C(clk),
    .D(_013_),
    .Q(\mem[1] [3])
  );
  DFF _456_ (
    .C(clk),
    .D(_014_),
    .Q(\mem[1] [4])
  );
  DFF _457_ (
    .C(clk),
    .D(_015_),
    .Q(\mem[1] [5])
  );
  DFF _458_ (
    .C(clk),
    .D(_016_),
    .Q(\mem[2] [0])
  );
  DFF _459_ (
    .C(clk),
    .D(_017_),
    .Q(\mem[2] [1])
  );
  DFF _460_ (
    .C(clk),
    .D(_018_),
    .Q(\mem[2] [2])
  );
  DFF _461_ (
    .C(clk),
    .D(_019_),
    .Q(\mem[2] [3])
  );
  DFF _462_ (
    .C(clk),
    .D(_020_),
    .Q(\mem[2] [4])
  );
  DFF _463_ (
    .C(clk),
    .D(_021_),
    .Q(\mem[2] [5])
  );
  DFF _464_ (
    .C(clk),
    .D(_004_),
    .Q(\mem[0] [0])
  );
  DFF _465_ (
    .C(clk),
    .D(_005_),
    .Q(\mem[0] [1])
  );
  DFF _466_ (
    .C(clk),
    .D(_006_),
    .Q(\mem[0] [2])
  );
  DFF _467_ (
    .C(clk),
    .D(_007_),
    .Q(\mem[0] [3])
  );
  DFF _468_ (
    .C(clk),
    .D(_008_),
    .Q(\mem[0] [4])
  );
  DFF _469_ (
    .C(clk),
    .D(_009_),
    .Q(\mem[0] [5])
  );
  DFF _470_ (
    .C(clk),
    .D(_002_[0]),
    .Q(rd_ptr[0])
  );
  DFF _471_ (
    .C(clk),
    .D(_002_[1]),
    .Q(rd_ptr[1])
  );
  DFF _472_ (
    .C(clk),
    .D(_022_),
    .Q(\mem[3] [0])
  );
  DFF _473_ (
    .C(clk),
    .D(_023_),
    .Q(\mem[3] [1])
  );
  DFF _474_ (
    .C(clk),
    .D(_024_),
    .Q(\mem[3] [2])
  );
  DFF _475_ (
    .C(clk),
    .D(_025_),
    .Q(\mem[3] [3])
  );
  DFF _476_ (
    .C(clk),
    .D(_026_),
    .Q(\mem[3] [4])
  );
  DFF _477_ (
    .C(clk),
    .D(_027_),
    .Q(\mem[3] [5])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:58" *)
  DFF _478_ (
    .C(clk),
    .D(_000_[0]),
    .Q(cnt[0])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:58" *)
  DFF _479_ (
    .C(clk),
    .D(_000_[1]),
    .Q(cnt[1])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:58" *)
  DFF _480_ (
    .C(clk),
    .D(_000_[2]),
    .Q(cnt[2])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:43" *)
  DFF _481_ (
    .C(clk),
    .D(_001_[0]),
    .Q(data_out_D0_synth[0])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:43" *)
  DFF _482_ (
    .C(clk),
    .D(_001_[1]),
    .Q(data_out_D0_synth[1])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:43" *)
  DFF _483_ (
    .C(clk),
    .D(_001_[2]),
    .Q(data_out_D0_synth[2])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:43" *)
  DFF _484_ (
    .C(clk),
    .D(_001_[3]),
    .Q(data_out_D0_synth[3])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:43" *)
  DFF _485_ (
    .C(clk),
    .D(_001_[4]),
    .Q(data_out_D0_synth[4])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:43" *)
  DFF _486_ (
    .C(clk),
    .D(_001_[5]),
    .Q(data_out_D0_synth[5])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:30" *)
  DFF _487_ (
    .C(clk),
    .D(_003_[0]),
    .Q(wr_ptr[0])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:30" *)
  DFF _488_ (
    .C(clk),
    .D(_003_[1]),
    .Q(wr_ptr[1])
  );
endmodule

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "./final_logic_synth/D1_fifo_synth.v:1" *)
module D1_fifo_synth(clk, reset_L, wr_enable, rd_enable, data_in, full_fifo_D1, empty_fifo_D1, almost_full_fifo_D1, almost_empty_fifo_D1, error_D1_synth, data_out_D1_synth);
  (* src = "./final_logic_synth/D1_fifo_synth.v:58" *)
  wire [2:0] _000_;
  (* src = "./final_logic_synth/D1_fifo_synth.v:43" *)
  wire [5:0] _001_;
  (* src = "./final_logic_synth/D1_fifo_synth.v:43" *)
  wire [1:0] _002_;
  (* src = "./final_logic_synth/D1_fifo_synth.v:30" *)
  wire [1:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  (* src = "./final_logic_synth/D1_fifo_synth.v:11" *)
  output almost_empty_fifo_D1;
  (* src = "./final_logic_synth/D1_fifo_synth.v:10" *)
  output almost_full_fifo_D1;
  (* src = "./final_logic_synth/D1_fifo_synth.v:6" *)
  input clk;
  (* src = "./final_logic_synth/D1_fifo_synth.v:20" *)
  wire [2:0] cnt;
  (* src = "./final_logic_synth/D1_fifo_synth.v:7" *)
  input [5:0] data_in;
  (* src = "./final_logic_synth/D1_fifo_synth.v:13" *)
  output [5:0] data_out_D1_synth;
  (* src = "./final_logic_synth/D1_fifo_synth.v:9" *)
  output empty_fifo_D1;
  (* src = "./final_logic_synth/D1_fifo_synth.v:12" *)
  output error_D1_synth;
  (* src = "./final_logic_synth/D1_fifo_synth.v:8" *)
  output full_fifo_D1;
  wire [5:0] \mem[0] ;
  wire [5:0] \mem[1] ;
  wire [5:0] \mem[2] ;
  wire [5:0] \mem[3] ;
  (* src = "./final_logic_synth/D1_fifo_synth.v:6" *)
  input rd_enable;
  (* src = "./final_logic_synth/D1_fifo_synth.v:19" *)
  wire [1:0] rd_ptr;
  (* src = "./final_logic_synth/D1_fifo_synth.v:6" *)
  input reset_L;
  (* src = "./final_logic_synth/D1_fifo_synth.v:6" *)
  input wr_enable;
  (* src = "./final_logic_synth/D1_fifo_synth.v:18" *)
  wire [1:0] wr_ptr;
  NOT _219_ (
    .A(cnt[1]),
    .Y(_202_)
  );
  NOT _220_ (
    .A(cnt[2]),
    .Y(_203_)
  );
  NOT _221_ (
    .A(wr_enable),
    .Y(_204_)
  );
  NOT _222_ (
    .A(rd_enable),
    .Y(_205_)
  );
  NOT _223_ (
    .A(rd_ptr[1]),
    .Y(_206_)
  );
  NOT _224_ (
    .A(\mem[0] [0]),
    .Y(_207_)
  );
  NOT _225_ (
    .A(\mem[0] [1]),
    .Y(_208_)
  );
  NOT _226_ (
    .A(\mem[0] [2]),
    .Y(_209_)
  );
  NOT _227_ (
    .A(\mem[0] [3]),
    .Y(_210_)
  );
  NOT _228_ (
    .A(\mem[0] [4]),
    .Y(_211_)
  );
  NOT _229_ (
    .A(\mem[0] [5]),
    .Y(_212_)
  );
  NOT _230_ (
    .A(\mem[3] [0]),
    .Y(_213_)
  );
  NOT _231_ (
    .A(\mem[3] [1]),
    .Y(_214_)
  );
  NOT _232_ (
    .A(\mem[3] [2]),
    .Y(_215_)
  );
  NOT _233_ (
    .A(\mem[3] [3]),
    .Y(_216_)
  );
  NOT _234_ (
    .A(\mem[3] [4]),
    .Y(_217_)
  );
  NOT _235_ (
    .A(\mem[3] [5]),
    .Y(_218_)
  );
  NOT _236_ (
    .A(reset_L),
    .Y(_028_)
  );
  NOT _237_ (
    .A(wr_ptr[0]),
    .Y(_029_)
  );
  NOT _238_ (
    .A(wr_ptr[1]),
    .Y(_030_)
  );
  NOR _239_ (
    .A(cnt[1]),
    .B(cnt[0]),
    .Y(_031_)
  );
  NOT _240_ (
    .A(_031_),
    .Y(_032_)
  );
  NAND _241_ (
    .A(cnt[2]),
    .B(_031_),
    .Y(_033_)
  );
  NOT _242_ (
    .A(_033_),
    .Y(full_fifo_D1)
  );
  NOR _243_ (
    .A(cnt[2]),
    .B(_032_),
    .Y(empty_fifo_D1)
  );
  NAND _244_ (
    .A(_203_),
    .B(cnt[0]),
    .Y(_034_)
  );
  NOR _245_ (
    .A(cnt[1]),
    .B(_034_),
    .Y(almost_empty_fifo_D1)
  );
  NAND _246_ (
    .A(cnt[1]),
    .B(cnt[0]),
    .Y(_035_)
  );
  NOT _247_ (
    .A(_035_),
    .Y(_036_)
  );
  NOR _248_ (
    .A(cnt[2]),
    .B(_035_),
    .Y(almost_full_fifo_D1)
  );
  NOR _249_ (
    .A(_204_),
    .B(_028_),
    .Y(_037_)
  );
  NAND _250_ (
    .A(wr_enable),
    .B(reset_L),
    .Y(_038_)
  );
  NOR _251_ (
    .A(_030_),
    .B(_038_),
    .Y(_039_)
  );
  NAND _252_ (
    .A(wr_ptr[1]),
    .B(_037_),
    .Y(_040_)
  );
  NOR _253_ (
    .A(wr_ptr[0]),
    .B(_040_),
    .Y(_041_)
  );
  NAND _254_ (
    .A(_029_),
    .B(_039_),
    .Y(_042_)
  );
  NAND _255_ (
    .A(data_in[0]),
    .B(_041_),
    .Y(_043_)
  );
  NAND _256_ (
    .A(\mem[2] [0]),
    .B(_042_),
    .Y(_044_)
  );
  NAND _257_ (
    .A(_043_),
    .B(_044_),
    .Y(_016_)
  );
  NAND _258_ (
    .A(data_in[1]),
    .B(_041_),
    .Y(_045_)
  );
  NAND _259_ (
    .A(\mem[2] [1]),
    .B(_042_),
    .Y(_046_)
  );
  NAND _260_ (
    .A(_045_),
    .B(_046_),
    .Y(_017_)
  );
  NAND _261_ (
    .A(data_in[2]),
    .B(_041_),
    .Y(_047_)
  );
  NAND _262_ (
    .A(\mem[2] [2]),
    .B(_042_),
    .Y(_048_)
  );
  NAND _263_ (
    .A(_047_),
    .B(_048_),
    .Y(_018_)
  );
  NAND _264_ (
    .A(data_in[3]),
    .B(_041_),
    .Y(_049_)
  );
  NAND _265_ (
    .A(\mem[2] [3]),
    .B(_042_),
    .Y(_050_)
  );
  NAND _266_ (
    .A(_049_),
    .B(_050_),
    .Y(_019_)
  );
  NAND _267_ (
    .A(data_in[4]),
    .B(_041_),
    .Y(_051_)
  );
  NAND _268_ (
    .A(\mem[2] [4]),
    .B(_042_),
    .Y(_052_)
  );
  NAND _269_ (
    .A(_051_),
    .B(_052_),
    .Y(_020_)
  );
  NAND _270_ (
    .A(data_in[5]),
    .B(_041_),
    .Y(_053_)
  );
  NAND _271_ (
    .A(\mem[2] [5]),
    .B(_042_),
    .Y(_054_)
  );
  NAND _272_ (
    .A(_053_),
    .B(_054_),
    .Y(_021_)
  );
  NOR _273_ (
    .A(_204_),
    .B(rd_enable),
    .Y(_055_)
  );
  NAND _274_ (
    .A(wr_enable),
    .B(_205_),
    .Y(_056_)
  );
  NOR _275_ (
    .A(wr_enable),
    .B(_205_),
    .Y(_057_)
  );
  NAND _276_ (
    .A(_204_),
    .B(rd_enable),
    .Y(_058_)
  );
  NAND _277_ (
    .A(_056_),
    .B(_058_),
    .Y(_059_)
  );
  NAND _278_ (
    .A(cnt[0]),
    .B(_059_),
    .Y(_060_)
  );
  NOT _279_ (
    .A(_060_),
    .Y(_061_)
  );
  NOR _280_ (
    .A(cnt[0]),
    .B(_059_),
    .Y(_062_)
  );
  NOT _281_ (
    .A(_062_),
    .Y(_063_)
  );
  NAND _282_ (
    .A(reset_L),
    .B(_063_),
    .Y(_064_)
  );
  NOR _283_ (
    .A(_061_),
    .B(_064_),
    .Y(_000_[0])
  );
  NOR _284_ (
    .A(_202_),
    .B(_059_),
    .Y(_065_)
  );
  NOR _285_ (
    .A(_031_),
    .B(_036_),
    .Y(_066_)
  );
  NAND _286_ (
    .A(_032_),
    .B(_035_),
    .Y(_067_)
  );
  NOR _287_ (
    .A(_055_),
    .B(_067_),
    .Y(_068_)
  );
  NOR _288_ (
    .A(_057_),
    .B(_066_),
    .Y(_069_)
  );
  NOR _289_ (
    .A(_068_),
    .B(_069_),
    .Y(_070_)
  );
  NOR _290_ (
    .A(_065_),
    .B(_070_),
    .Y(_071_)
  );
  NOR _291_ (
    .A(_028_),
    .B(_071_),
    .Y(_000_[1])
  );
  NOR _292_ (
    .A(_203_),
    .B(_031_),
    .Y(error_D1_synth)
  );
  NOR _293_ (
    .A(empty_fifo_D1),
    .B(error_D1_synth),
    .Y(_072_)
  );
  NOR _294_ (
    .A(_058_),
    .B(_072_),
    .Y(_073_)
  );
  NOR _295_ (
    .A(_035_),
    .B(_056_),
    .Y(_074_)
  );
  NAND _296_ (
    .A(_036_),
    .B(_055_),
    .Y(_075_)
  );
  NOR _297_ (
    .A(_203_),
    .B(_075_),
    .Y(_076_)
  );
  NOR _298_ (
    .A(_203_),
    .B(_057_),
    .Y(_077_)
  );
  NOR _299_ (
    .A(_074_),
    .B(_077_),
    .Y(_078_)
  );
  NOR _300_ (
    .A(_076_),
    .B(_078_),
    .Y(_079_)
  );
  NOR _301_ (
    .A(_073_),
    .B(_079_),
    .Y(_080_)
  );
  NOR _302_ (
    .A(_028_),
    .B(_080_),
    .Y(_000_[2])
  );
  NAND _303_ (
    .A(rd_enable),
    .B(reset_L),
    .Y(_081_)
  );
  NOR _304_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [0]),
    .Y(_082_)
  );
  NAND _305_ (
    .A(rd_ptr[0]),
    .B(_213_),
    .Y(_083_)
  );
  NAND _306_ (
    .A(rd_ptr[1]),
    .B(_083_),
    .Y(_084_)
  );
  NOR _307_ (
    .A(_082_),
    .B(_084_),
    .Y(_085_)
  );
  NAND _308_ (
    .A(\mem[1] [0]),
    .B(rd_ptr[0]),
    .Y(_086_)
  );
  NOT _309_ (
    .A(_086_),
    .Y(_087_)
  );
  NOR _310_ (
    .A(_207_),
    .B(rd_ptr[0]),
    .Y(_088_)
  );
  NOR _311_ (
    .A(_087_),
    .B(_088_),
    .Y(_089_)
  );
  NOR _312_ (
    .A(rd_ptr[1]),
    .B(_089_),
    .Y(_090_)
  );
  NOR _313_ (
    .A(_085_),
    .B(_090_),
    .Y(_091_)
  );
  NOR _314_ (
    .A(_081_),
    .B(_091_),
    .Y(_001_[0])
  );
  NOR _315_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [1]),
    .Y(_092_)
  );
  NAND _316_ (
    .A(rd_ptr[0]),
    .B(_214_),
    .Y(_093_)
  );
  NAND _317_ (
    .A(rd_ptr[1]),
    .B(_093_),
    .Y(_094_)
  );
  NOR _318_ (
    .A(_092_),
    .B(_094_),
    .Y(_095_)
  );
  NAND _319_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [1]),
    .Y(_096_)
  );
  NOT _320_ (
    .A(_096_),
    .Y(_097_)
  );
  NOR _321_ (
    .A(rd_ptr[0]),
    .B(_208_),
    .Y(_098_)
  );
  NOR _322_ (
    .A(_097_),
    .B(_098_),
    .Y(_099_)
  );
  NOR _323_ (
    .A(rd_ptr[1]),
    .B(_099_),
    .Y(_100_)
  );
  NOR _324_ (
    .A(_095_),
    .B(_100_),
    .Y(_101_)
  );
  NOR _325_ (
    .A(_081_),
    .B(_101_),
    .Y(_001_[1])
  );
  NOR _326_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [2]),
    .Y(_102_)
  );
  NAND _327_ (
    .A(rd_ptr[0]),
    .B(_215_),
    .Y(_103_)
  );
  NAND _328_ (
    .A(rd_ptr[1]),
    .B(_103_),
    .Y(_104_)
  );
  NOR _329_ (
    .A(_102_),
    .B(_104_),
    .Y(_105_)
  );
  NAND _330_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [2]),
    .Y(_106_)
  );
  NOT _331_ (
    .A(_106_),
    .Y(_107_)
  );
  NOR _332_ (
    .A(rd_ptr[0]),
    .B(_209_),
    .Y(_108_)
  );
  NOR _333_ (
    .A(_107_),
    .B(_108_),
    .Y(_109_)
  );
  NOR _334_ (
    .A(rd_ptr[1]),
    .B(_109_),
    .Y(_110_)
  );
  NOR _335_ (
    .A(_105_),
    .B(_110_),
    .Y(_111_)
  );
  NOR _336_ (
    .A(_081_),
    .B(_111_),
    .Y(_001_[2])
  );
  NOR _337_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [3]),
    .Y(_112_)
  );
  NAND _338_ (
    .A(rd_ptr[0]),
    .B(_216_),
    .Y(_113_)
  );
  NAND _339_ (
    .A(rd_ptr[1]),
    .B(_113_),
    .Y(_114_)
  );
  NOR _340_ (
    .A(_112_),
    .B(_114_),
    .Y(_115_)
  );
  NAND _341_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [3]),
    .Y(_116_)
  );
  NOT _342_ (
    .A(_116_),
    .Y(_117_)
  );
  NOR _343_ (
    .A(rd_ptr[0]),
    .B(_210_),
    .Y(_118_)
  );
  NOR _344_ (
    .A(_117_),
    .B(_118_),
    .Y(_119_)
  );
  NOR _345_ (
    .A(rd_ptr[1]),
    .B(_119_),
    .Y(_120_)
  );
  NOR _346_ (
    .A(_115_),
    .B(_120_),
    .Y(_121_)
  );
  NOR _347_ (
    .A(_081_),
    .B(_121_),
    .Y(_001_[3])
  );
  NOR _348_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [4]),
    .Y(_122_)
  );
  NAND _349_ (
    .A(rd_ptr[0]),
    .B(_217_),
    .Y(_123_)
  );
  NAND _350_ (
    .A(rd_ptr[1]),
    .B(_123_),
    .Y(_124_)
  );
  NOR _351_ (
    .A(_122_),
    .B(_124_),
    .Y(_125_)
  );
  NAND _352_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [4]),
    .Y(_126_)
  );
  NOT _353_ (
    .A(_126_),
    .Y(_127_)
  );
  NOR _354_ (
    .A(rd_ptr[0]),
    .B(_211_),
    .Y(_128_)
  );
  NOR _355_ (
    .A(_127_),
    .B(_128_),
    .Y(_129_)
  );
  NOR _356_ (
    .A(rd_ptr[1]),
    .B(_129_),
    .Y(_130_)
  );
  NOR _357_ (
    .A(_125_),
    .B(_130_),
    .Y(_131_)
  );
  NOR _358_ (
    .A(_081_),
    .B(_131_),
    .Y(_001_[4])
  );
  NOR _359_ (
    .A(rd_ptr[0]),
    .B(\mem[2] [5]),
    .Y(_132_)
  );
  NAND _360_ (
    .A(rd_ptr[0]),
    .B(_218_),
    .Y(_133_)
  );
  NAND _361_ (
    .A(rd_ptr[1]),
    .B(_133_),
    .Y(_134_)
  );
  NOR _362_ (
    .A(_132_),
    .B(_134_),
    .Y(_135_)
  );
  NAND _363_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [5]),
    .Y(_136_)
  );
  NOT _364_ (
    .A(_136_),
    .Y(_137_)
  );
  NOR _365_ (
    .A(rd_ptr[0]),
    .B(_212_),
    .Y(_138_)
  );
  NOR _366_ (
    .A(_137_),
    .B(_138_),
    .Y(_139_)
  );
  NOR _367_ (
    .A(rd_ptr[1]),
    .B(_139_),
    .Y(_140_)
  );
  NOR _368_ (
    .A(_135_),
    .B(_140_),
    .Y(_141_)
  );
  NOR _369_ (
    .A(_081_),
    .B(_141_),
    .Y(_001_[5])
  );
  NAND _370_ (
    .A(rd_enable),
    .B(rd_ptr[0]),
    .Y(_142_)
  );
  NOT _371_ (
    .A(_142_),
    .Y(_143_)
  );
  NOR _372_ (
    .A(rd_enable),
    .B(rd_ptr[0]),
    .Y(_144_)
  );
  NOT _373_ (
    .A(_144_),
    .Y(_145_)
  );
  NAND _374_ (
    .A(reset_L),
    .B(_145_),
    .Y(_146_)
  );
  NOR _375_ (
    .A(_143_),
    .B(_146_),
    .Y(_002_[0])
  );
  NOR _376_ (
    .A(_206_),
    .B(_142_),
    .Y(_147_)
  );
  NAND _377_ (
    .A(_206_),
    .B(_142_),
    .Y(_148_)
  );
  NAND _378_ (
    .A(reset_L),
    .B(_148_),
    .Y(_149_)
  );
  NOR _379_ (
    .A(_147_),
    .B(_149_),
    .Y(_002_[1])
  );
  NOR _380_ (
    .A(_204_),
    .B(_029_),
    .Y(_150_)
  );
  NAND _381_ (
    .A(wr_ptr[1]),
    .B(_150_),
    .Y(_151_)
  );
  NOR _382_ (
    .A(_028_),
    .B(_151_),
    .Y(_152_)
  );
  NAND _383_ (
    .A(wr_ptr[0]),
    .B(_039_),
    .Y(_153_)
  );
  NAND _384_ (
    .A(data_in[0]),
    .B(_152_),
    .Y(_154_)
  );
  NAND _385_ (
    .A(\mem[3] [0]),
    .B(_153_),
    .Y(_155_)
  );
  NAND _386_ (
    .A(_154_),
    .B(_155_),
    .Y(_022_)
  );
  NAND _387_ (
    .A(data_in[1]),
    .B(_152_),
    .Y(_156_)
  );
  NAND _388_ (
    .A(\mem[3] [1]),
    .B(_153_),
    .Y(_157_)
  );
  NAND _389_ (
    .A(_156_),
    .B(_157_),
    .Y(_023_)
  );
  NAND _390_ (
    .A(data_in[2]),
    .B(_152_),
    .Y(_158_)
  );
  NAND _391_ (
    .A(\mem[3] [2]),
    .B(_153_),
    .Y(_159_)
  );
  NAND _392_ (
    .A(_158_),
    .B(_159_),
    .Y(_024_)
  );
  NAND _393_ (
    .A(data_in[3]),
    .B(_152_),
    .Y(_160_)
  );
  NAND _394_ (
    .A(\mem[3] [3]),
    .B(_153_),
    .Y(_161_)
  );
  NAND _395_ (
    .A(_160_),
    .B(_161_),
    .Y(_025_)
  );
  NAND _396_ (
    .A(data_in[4]),
    .B(_152_),
    .Y(_162_)
  );
  NAND _397_ (
    .A(\mem[3] [4]),
    .B(_153_),
    .Y(_163_)
  );
  NAND _398_ (
    .A(_162_),
    .B(_163_),
    .Y(_026_)
  );
  NAND _399_ (
    .A(data_in[5]),
    .B(_152_),
    .Y(_164_)
  );
  NAND _400_ (
    .A(\mem[3] [5]),
    .B(_153_),
    .Y(_165_)
  );
  NAND _401_ (
    .A(_164_),
    .B(_165_),
    .Y(_027_)
  );
  NOR _402_ (
    .A(wr_enable),
    .B(wr_ptr[0]),
    .Y(_166_)
  );
  NOT _403_ (
    .A(_166_),
    .Y(_167_)
  );
  NAND _404_ (
    .A(reset_L),
    .B(_167_),
    .Y(_168_)
  );
  NOR _405_ (
    .A(_150_),
    .B(_168_),
    .Y(_003_[0])
  );
  NOR _406_ (
    .A(wr_ptr[1]),
    .B(_150_),
    .Y(_169_)
  );
  NOT _407_ (
    .A(_169_),
    .Y(_170_)
  );
  NAND _408_ (
    .A(reset_L),
    .B(_151_),
    .Y(_171_)
  );
  NOR _409_ (
    .A(_169_),
    .B(_171_),
    .Y(_003_[1])
  );
  NAND _410_ (
    .A(wr_ptr[0]),
    .B(_030_),
    .Y(_172_)
  );
  NOR _411_ (
    .A(_028_),
    .B(wr_ptr[1]),
    .Y(_173_)
  );
  NOR _412_ (
    .A(_038_),
    .B(_172_),
    .Y(_174_)
  );
  NAND _413_ (
    .A(_150_),
    .B(_173_),
    .Y(_175_)
  );
  NAND _414_ (
    .A(data_in[0]),
    .B(_174_),
    .Y(_176_)
  );
  NAND _415_ (
    .A(\mem[1] [0]),
    .B(_175_),
    .Y(_177_)
  );
  NAND _416_ (
    .A(_176_),
    .B(_177_),
    .Y(_010_)
  );
  NAND _417_ (
    .A(data_in[1]),
    .B(_174_),
    .Y(_178_)
  );
  NAND _418_ (
    .A(\mem[1] [1]),
    .B(_175_),
    .Y(_179_)
  );
  NAND _419_ (
    .A(_178_),
    .B(_179_),
    .Y(_011_)
  );
  NAND _420_ (
    .A(data_in[2]),
    .B(_174_),
    .Y(_180_)
  );
  NAND _421_ (
    .A(\mem[1] [2]),
    .B(_175_),
    .Y(_181_)
  );
  NAND _422_ (
    .A(_180_),
    .B(_181_),
    .Y(_012_)
  );
  NAND _423_ (
    .A(data_in[3]),
    .B(_174_),
    .Y(_182_)
  );
  NAND _424_ (
    .A(\mem[1] [3]),
    .B(_175_),
    .Y(_183_)
  );
  NAND _425_ (
    .A(_182_),
    .B(_183_),
    .Y(_013_)
  );
  NAND _426_ (
    .A(data_in[4]),
    .B(_174_),
    .Y(_184_)
  );
  NAND _427_ (
    .A(\mem[1] [4]),
    .B(_175_),
    .Y(_185_)
  );
  NAND _428_ (
    .A(_184_),
    .B(_185_),
    .Y(_014_)
  );
  NAND _429_ (
    .A(data_in[5]),
    .B(_174_),
    .Y(_186_)
  );
  NAND _430_ (
    .A(\mem[1] [5]),
    .B(_175_),
    .Y(_187_)
  );
  NAND _431_ (
    .A(_186_),
    .B(_187_),
    .Y(_015_)
  );
  NOR _432_ (
    .A(_038_),
    .B(_170_),
    .Y(_188_)
  );
  NAND _433_ (
    .A(_037_),
    .B(_169_),
    .Y(_189_)
  );
  NOR _434_ (
    .A(\mem[0] [0]),
    .B(_188_),
    .Y(_190_)
  );
  NOR _435_ (
    .A(data_in[0]),
    .B(_189_),
    .Y(_191_)
  );
  NOR _436_ (
    .A(_190_),
    .B(_191_),
    .Y(_004_)
  );
  NOR _437_ (
    .A(\mem[0] [1]),
    .B(_188_),
    .Y(_192_)
  );
  NOR _438_ (
    .A(data_in[1]),
    .B(_189_),
    .Y(_193_)
  );
  NOR _439_ (
    .A(_192_),
    .B(_193_),
    .Y(_005_)
  );
  NOR _440_ (
    .A(\mem[0] [2]),
    .B(_188_),
    .Y(_194_)
  );
  NOR _441_ (
    .A(data_in[2]),
    .B(_189_),
    .Y(_195_)
  );
  NOR _442_ (
    .A(_194_),
    .B(_195_),
    .Y(_006_)
  );
  NOR _443_ (
    .A(\mem[0] [3]),
    .B(_188_),
    .Y(_196_)
  );
  NOR _444_ (
    .A(data_in[3]),
    .B(_189_),
    .Y(_197_)
  );
  NOR _445_ (
    .A(_196_),
    .B(_197_),
    .Y(_007_)
  );
  NOR _446_ (
    .A(\mem[0] [4]),
    .B(_188_),
    .Y(_198_)
  );
  NOR _447_ (
    .A(data_in[4]),
    .B(_189_),
    .Y(_199_)
  );
  NOR _448_ (
    .A(_198_),
    .B(_199_),
    .Y(_008_)
  );
  NOR _449_ (
    .A(\mem[0] [5]),
    .B(_188_),
    .Y(_200_)
  );
  NOR _450_ (
    .A(data_in[5]),
    .B(_189_),
    .Y(_201_)
  );
  NOR _451_ (
    .A(_200_),
    .B(_201_),
    .Y(_009_)
  );
  DFF _452_ (
    .C(clk),
    .D(_002_[0]),
    .Q(rd_ptr[0])
  );
  DFF _453_ (
    .C(clk),
    .D(_002_[1]),
    .Q(rd_ptr[1])
  );
  DFF _454_ (
    .C(clk),
    .D(_022_),
    .Q(\mem[3] [0])
  );
  DFF _455_ (
    .C(clk),
    .D(_023_),
    .Q(\mem[3] [1])
  );
  DFF _456_ (
    .C(clk),
    .D(_024_),
    .Q(\mem[3] [2])
  );
  DFF _457_ (
    .C(clk),
    .D(_025_),
    .Q(\mem[3] [3])
  );
  DFF _458_ (
    .C(clk),
    .D(_026_),
    .Q(\mem[3] [4])
  );
  DFF _459_ (
    .C(clk),
    .D(_027_),
    .Q(\mem[3] [5])
  );
  DFF _460_ (
    .C(clk),
    .D(_016_),
    .Q(\mem[2] [0])
  );
  DFF _461_ (
    .C(clk),
    .D(_017_),
    .Q(\mem[2] [1])
  );
  DFF _462_ (
    .C(clk),
    .D(_018_),
    .Q(\mem[2] [2])
  );
  DFF _463_ (
    .C(clk),
    .D(_019_),
    .Q(\mem[2] [3])
  );
  DFF _464_ (
    .C(clk),
    .D(_020_),
    .Q(\mem[2] [4])
  );
  DFF _465_ (
    .C(clk),
    .D(_021_),
    .Q(\mem[2] [5])
  );
  DFF _466_ (
    .C(clk),
    .D(_010_),
    .Q(\mem[1] [0])
  );
  DFF _467_ (
    .C(clk),
    .D(_011_),
    .Q(\mem[1] [1])
  );
  DFF _468_ (
    .C(clk),
    .D(_012_),
    .Q(\mem[1] [2])
  );
  DFF _469_ (
    .C(clk),
    .D(_013_),
    .Q(\mem[1] [3])
  );
  DFF _470_ (
    .C(clk),
    .D(_014_),
    .Q(\mem[1] [4])
  );
  DFF _471_ (
    .C(clk),
    .D(_015_),
    .Q(\mem[1] [5])
  );
  DFF _472_ (
    .C(clk),
    .D(_004_),
    .Q(\mem[0] [0])
  );
  DFF _473_ (
    .C(clk),
    .D(_005_),
    .Q(\mem[0] [1])
  );
  DFF _474_ (
    .C(clk),
    .D(_006_),
    .Q(\mem[0] [2])
  );
  DFF _475_ (
    .C(clk),
    .D(_007_),
    .Q(\mem[0] [3])
  );
  DFF _476_ (
    .C(clk),
    .D(_008_),
    .Q(\mem[0] [4])
  );
  DFF _477_ (
    .C(clk),
    .D(_009_),
    .Q(\mem[0] [5])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:58" *)
  DFF _478_ (
    .C(clk),
    .D(_000_[0]),
    .Q(cnt[0])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:58" *)
  DFF _479_ (
    .C(clk),
    .D(_000_[1]),
    .Q(cnt[1])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:58" *)
  DFF _480_ (
    .C(clk),
    .D(_000_[2]),
    .Q(cnt[2])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:43" *)
  DFF _481_ (
    .C(clk),
    .D(_001_[0]),
    .Q(data_out_D1_synth[0])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:43" *)
  DFF _482_ (
    .C(clk),
    .D(_001_[1]),
    .Q(data_out_D1_synth[1])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:43" *)
  DFF _483_ (
    .C(clk),
    .D(_001_[2]),
    .Q(data_out_D1_synth[2])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:43" *)
  DFF _484_ (
    .C(clk),
    .D(_001_[3]),
    .Q(data_out_D1_synth[3])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:43" *)
  DFF _485_ (
    .C(clk),
    .D(_001_[4]),
    .Q(data_out_D1_synth[4])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:43" *)
  DFF _486_ (
    .C(clk),
    .D(_001_[5]),
    .Q(data_out_D1_synth[5])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:30" *)
  DFF _487_ (
    .C(clk),
    .D(_003_[0]),
    .Q(wr_ptr[0])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:30" *)
  DFF _488_ (
    .C(clk),
    .D(_003_[1]),
    .Q(wr_ptr[1])
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:5" *)
module arbitro_enrutamiento_synth(VC0, VC1, clk, reset_L, VC0_empty, VC1_empty, D1_pause, D0_pause, VC1_pop, VC0_pop, D0_push, D1_push, D0_out, D1_out);
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:9" *)
  output [5:0] D0_out;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:7" *)
  input D0_pause;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:8" *)
  output D0_push;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:9" *)
  output [5:0] D1_out;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:7" *)
  input D1_pause;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:8" *)
  output D1_push;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:5" *)
  input [5:0] VC0;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:7" *)
  input VC0_empty;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:8" *)
  output VC0_pop;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:5" *)
  input [5:0] VC1;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:7" *)
  input VC1_empty;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:8" *)
  output VC1_pop;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:6" *)
  input clk;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:11" *)
  wire pop_delay_VC0;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:11" *)
  wire pop_delay_VC1;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:6" *)
  input reset_L;
  (* module_not_derived = 32'd1 *)
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:13" *)
  arbitro_mux_synth u_arbitro_mux_synthes (
    .D0_out(D0_out),
    .D0_push(D0_push),
    .D1_out(D1_out),
    .D1_push(D1_push),
    .VC0(VC0),
    .VC0_empty(VC0_empty),
    .VC1(VC1),
    .VC1_empty(VC1_empty),
    .clk(clk),
    .pop_delay_VC0(pop_delay_VC0),
    .pop_delay_VC1(pop_delay_VC1),
    .reset_L(reset_L)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:39" *)
  logica_pops_synth u_logica_pops_synth (
    .D0_pause(D0_pause),
    .D1_pause(D1_pause),
    .VC0_empty(VC0_empty),
    .VC0_pop(VC0_pop),
    .VC1_empty(VC1_empty),
    .VC1_pop(VC1_pop),
    .clk(clk),
    .pop_delay_VC0(pop_delay_VC0),
    .pop_delay_VC1(pop_delay_VC1)
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:1" *)
module arbitro_mux_synth(reset_L, clk, VC0, VC1, pop_delay_VC0, pop_delay_VC1, VC0_empty, VC1_empty, D0_out, D1_out, D0_push, D1_push);
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  wire [5:0] _000_;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  wire _001_;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  wire [5:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:6" *)
  output [5:0] D0_out;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:7" *)
  output D0_push;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:6" *)
  output [5:0] D1_out;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:7" *)
  output D1_push;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:2" *)
  input [5:0] VC0;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:5" *)
  input VC0_empty;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:3" *)
  input [5:0] VC1;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:5" *)
  input VC1_empty;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:1" *)
  input clk;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:4" *)
  input pop_delay_VC0;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:4" *)
  input pop_delay_VC1;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:1" *)
  input reset_L;
  NOT _058_ (
    .A(VC1[4]),
    .Y(_003_)
  );
  NOT _059_ (
    .A(VC0[4]),
    .Y(_004_)
  );
  NOT _060_ (
    .A(reset_L),
    .Y(_005_)
  );
  NOT _061_ (
    .A(VC1[0]),
    .Y(_006_)
  );
  NOT _062_ (
    .A(VC1[1]),
    .Y(_007_)
  );
  NOT _063_ (
    .A(VC1[2]),
    .Y(_008_)
  );
  NOT _064_ (
    .A(VC1[3]),
    .Y(_009_)
  );
  NOT _065_ (
    .A(VC1[5]),
    .Y(_010_)
  );
  NOT _066_ (
    .A(VC0[0]),
    .Y(_011_)
  );
  NOT _067_ (
    .A(VC0[1]),
    .Y(_012_)
  );
  NOT _068_ (
    .A(VC0[2]),
    .Y(_013_)
  );
  NOT _069_ (
    .A(VC0[3]),
    .Y(_014_)
  );
  NOT _070_ (
    .A(VC0[5]),
    .Y(_015_)
  );
  NOR _071_ (
    .A(VC0_empty),
    .B(VC0[4]),
    .Y(_016_)
  );
  NAND _072_ (
    .A(pop_delay_VC0),
    .B(_016_),
    .Y(_017_)
  );
  NAND _073_ (
    .A(pop_delay_VC1),
    .B(VC0_empty),
    .Y(_018_)
  );
  NOR _074_ (
    .A(VC1_empty),
    .B(_018_),
    .Y(_019_)
  );
  NAND _075_ (
    .A(_003_),
    .B(_019_),
    .Y(_020_)
  );
  NAND _076_ (
    .A(_017_),
    .B(_020_),
    .Y(_021_)
  );
  NAND _077_ (
    .A(reset_L),
    .B(_021_),
    .Y(_022_)
  );
  NOT _078_ (
    .A(_022_),
    .Y(_001_)
  );
  NOR _079_ (
    .A(VC0_empty),
    .B(_004_),
    .Y(_023_)
  );
  NAND _080_ (
    .A(pop_delay_VC0),
    .B(_023_),
    .Y(_024_)
  );
  NOR _081_ (
    .A(_011_),
    .B(_024_),
    .Y(_025_)
  );
  NAND _082_ (
    .A(VC1[4]),
    .B(_019_),
    .Y(_026_)
  );
  NOR _083_ (
    .A(_006_),
    .B(_026_),
    .Y(_027_)
  );
  NOR _084_ (
    .A(_025_),
    .B(_027_),
    .Y(_028_)
  );
  NOR _085_ (
    .A(_005_),
    .B(_028_),
    .Y(_002_[0])
  );
  NOR _086_ (
    .A(_012_),
    .B(_024_),
    .Y(_029_)
  );
  NOR _087_ (
    .A(_007_),
    .B(_026_),
    .Y(_030_)
  );
  NOR _088_ (
    .A(_029_),
    .B(_030_),
    .Y(_031_)
  );
  NOR _089_ (
    .A(_005_),
    .B(_031_),
    .Y(_002_[1])
  );
  NOR _090_ (
    .A(_013_),
    .B(_024_),
    .Y(_032_)
  );
  NOR _091_ (
    .A(_008_),
    .B(_026_),
    .Y(_033_)
  );
  NOR _092_ (
    .A(_032_),
    .B(_033_),
    .Y(_034_)
  );
  NOR _093_ (
    .A(_005_),
    .B(_034_),
    .Y(_002_[2])
  );
  NOR _094_ (
    .A(_014_),
    .B(_024_),
    .Y(_035_)
  );
  NOR _095_ (
    .A(_009_),
    .B(_026_),
    .Y(_036_)
  );
  NOR _096_ (
    .A(_035_),
    .B(_036_),
    .Y(_037_)
  );
  NOR _097_ (
    .A(_005_),
    .B(_037_),
    .Y(_002_[3])
  );
  NAND _098_ (
    .A(_024_),
    .B(_026_),
    .Y(_038_)
  );
  NAND _099_ (
    .A(reset_L),
    .B(_038_),
    .Y(_039_)
  );
  NOT _100_ (
    .A(_039_),
    .Y(_002_[4])
  );
  NOR _101_ (
    .A(_015_),
    .B(_024_),
    .Y(_040_)
  );
  NOR _102_ (
    .A(_010_),
    .B(_026_),
    .Y(_041_)
  );
  NOR _103_ (
    .A(_040_),
    .B(_041_),
    .Y(_042_)
  );
  NOR _104_ (
    .A(_005_),
    .B(_042_),
    .Y(_002_[5])
  );
  NOR _105_ (
    .A(_011_),
    .B(_017_),
    .Y(_043_)
  );
  NOR _106_ (
    .A(_006_),
    .B(_020_),
    .Y(_044_)
  );
  NOR _107_ (
    .A(_043_),
    .B(_044_),
    .Y(_045_)
  );
  NOR _108_ (
    .A(_005_),
    .B(_045_),
    .Y(_000_[0])
  );
  NOR _109_ (
    .A(_012_),
    .B(_017_),
    .Y(_046_)
  );
  NOR _110_ (
    .A(_007_),
    .B(_020_),
    .Y(_047_)
  );
  NOR _111_ (
    .A(_046_),
    .B(_047_),
    .Y(_048_)
  );
  NOR _112_ (
    .A(_005_),
    .B(_048_),
    .Y(_000_[1])
  );
  NOR _113_ (
    .A(_013_),
    .B(_017_),
    .Y(_049_)
  );
  NOR _114_ (
    .A(_008_),
    .B(_020_),
    .Y(_050_)
  );
  NOR _115_ (
    .A(_049_),
    .B(_050_),
    .Y(_051_)
  );
  NOR _116_ (
    .A(_005_),
    .B(_051_),
    .Y(_000_[2])
  );
  NOR _117_ (
    .A(_014_),
    .B(_017_),
    .Y(_052_)
  );
  NOR _118_ (
    .A(_009_),
    .B(_020_),
    .Y(_053_)
  );
  NOR _119_ (
    .A(_052_),
    .B(_053_),
    .Y(_054_)
  );
  NOR _120_ (
    .A(_005_),
    .B(_054_),
    .Y(_000_[3])
  );
  NOR _121_ (
    .A(_015_),
    .B(_017_),
    .Y(_055_)
  );
  NOR _122_ (
    .A(_010_),
    .B(_020_),
    .Y(_056_)
  );
  NOR _123_ (
    .A(_055_),
    .B(_056_),
    .Y(_057_)
  );
  NOR _124_ (
    .A(_005_),
    .B(_057_),
    .Y(_000_[5])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _125_ (
    .C(clk),
    .D(_000_[0]),
    .Q(D0_out[0])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _126_ (
    .C(clk),
    .D(_000_[1]),
    .Q(D0_out[1])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _127_ (
    .C(clk),
    .D(_000_[2]),
    .Q(D0_out[2])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _128_ (
    .C(clk),
    .D(_000_[3]),
    .Q(D0_out[3])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _129_ (
    .C(clk),
    .D(_000_[5]),
    .Q(D0_out[5])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _130_ (
    .C(clk),
    .D(_002_[0]),
    .Q(D1_out[0])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _131_ (
    .C(clk),
    .D(_002_[1]),
    .Q(D1_out[1])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _132_ (
    .C(clk),
    .D(_002_[2]),
    .Q(D1_out[2])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _133_ (
    .C(clk),
    .D(_002_[3]),
    .Q(D1_out[3])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _134_ (
    .C(clk),
    .D(_002_[5]),
    .Q(D1_out[5])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _135_ (
    .C(clk),
    .D(_001_),
    .Q(D0_push)
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:9" *)
  DFF _136_ (
    .C(clk),
    .D(_002_[4]),
    .Q(D1_push)
  );
  assign _000_[4] = 1'h0;
  assign D0_out[4] = 1'h0;
  assign D1_out[4] = D1_push;
endmodule

(* cells_not_processed =  1  *)
(* src = "./final_logic_synth/final_logic_synth.v:5" *)
module final_logic_synth(data_out_VC0, data_out_VC1, clk, reset_L, empty_fifo_VC0, empty_fifo_VC1, D0_pop, D1_pop, data_out_D0_synth, data_out_D1_synth, pop_VC0_fifo_synth, pop_VC1_fifo_synth, error_D1_synth, error_D0_synth);
  (* src = "./final_logic_synth/final_logic_synth.v:17" *)
  wire [5:0] D0_out;
  (* src = "./final_logic_synth/final_logic_synth.v:11" *)
  input D0_pop;
  (* src = "./final_logic_synth/final_logic_synth.v:16" *)
  wire D0_push;
  (* src = "./final_logic_synth/final_logic_synth.v:17" *)
  wire [5:0] D1_out;
  (* src = "./final_logic_synth/final_logic_synth.v:11" *)
  input D1_pop;
  (* src = "./final_logic_synth/final_logic_synth.v:16" *)
  wire D1_push;
  (* src = "./final_logic_synth/final_logic_synth.v:45" *)
  (* unused_bits = "0" *)
  wire almost_empty_fifo_D0;
  (* src = "./final_logic_synth/final_logic_synth.v:59" *)
  (* unused_bits = "0" *)
  wire almost_empty_fifo_D1;
  (* src = "./final_logic_synth/final_logic_synth.v:10" *)
  input clk;
  (* src = "./final_logic_synth/final_logic_synth.v:12" *)
  output [5:0] data_out_D0_synth;
  (* src = "./final_logic_synth/final_logic_synth.v:12" *)
  output [5:0] data_out_D1_synth;
  (* src = "./final_logic_synth/final_logic_synth.v:9" *)
  input [5:0] data_out_VC0;
  (* src = "./final_logic_synth/final_logic_synth.v:9" *)
  input [5:0] data_out_VC1;
  (* src = "./final_logic_synth/final_logic_synth.v:43" *)
  (* unused_bits = "0" *)
  wire empty_fifo_D0;
  (* src = "./final_logic_synth/final_logic_synth.v:57" *)
  (* unused_bits = "0" *)
  wire empty_fifo_D1;
  (* src = "./final_logic_synth/final_logic_synth.v:10" *)
  input empty_fifo_VC0;
  (* src = "./final_logic_synth/final_logic_synth.v:10" *)
  input empty_fifo_VC1;
  (* src = "./final_logic_synth/final_logic_synth.v:14" *)
  output error_D0_synth;
  (* src = "./final_logic_synth/final_logic_synth.v:14" *)
  output error_D1_synth;
  (* src = "./final_logic_synth/final_logic_synth.v:42" *)
  (* unused_bits = "0" *)
  wire full_fifo_D0;
  (* src = "./final_logic_synth/final_logic_synth.v:56" *)
  (* unused_bits = "0" *)
  wire full_fifo_D1;
  (* src = "./final_logic_synth/final_logic_synth.v:16" *)
  wire fulloralmostfull_D0;
  (* src = "./final_logic_synth/final_logic_synth.v:16" *)
  wire fulloralmostfull_D1;
  (* src = "./final_logic_synth/final_logic_synth.v:13" *)
  output pop_VC0_fifo_synth;
  (* src = "./final_logic_synth/final_logic_synth.v:13" *)
  output pop_VC1_fifo_synth;
  (* src = "./final_logic_synth/final_logic_synth.v:10" *)
  input reset_L;
  (* module_not_derived = 32'd1 *)
  (* src = "./final_logic_synth/final_logic_synth.v:36" *)
  D0_fifo_synth u_D0_fifo_synth (
    .almost_empty_fifo_D0(almost_empty_fifo_D0),
    .almost_full_fifo_D0(fulloralmostfull_D0),
    .clk(clk),
    .data_in(D0_out),
    .data_out_D0_synth(data_out_D0_synth),
    .empty_fifo_D0(empty_fifo_D0),
    .error_D0_synth(error_D0_synth),
    .full_fifo_D0(full_fifo_D0),
    .rd_enable(D0_pop),
    .reset_L(reset_L),
    .wr_enable(D0_push)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./final_logic_synth/final_logic_synth.v:50" *)
  D1_fifo_synth u_D1_fifo_synth (
    .almost_empty_fifo_D1(almost_empty_fifo_D1),
    .almost_full_fifo_D1(fulloralmostfull_D1),
    .clk(clk),
    .data_in(D1_out),
    .data_out_D1_synth(data_out_D1_synth),
    .empty_fifo_D1(empty_fifo_D1),
    .error_D1_synth(error_D1_synth),
    .full_fifo_D1(full_fifo_D1),
    .rd_enable(D1_pop),
    .reset_L(reset_L),
    .wr_enable(D1_push)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./final_logic_synth/final_logic_synth.v:19" *)
  arbitro_enrutamiento_synth u_arbitro_enrutamiento_synth (
    .D0_out(D0_out),
    .D0_pause(fulloralmostfull_D0),
    .D0_push(D0_push),
    .D1_out(D1_out),
    .D1_pause(fulloralmostfull_D1),
    .D1_push(D1_push),
    .VC0(data_out_VC0),
    .VC0_empty(empty_fifo_VC0),
    .VC0_pop(pop_VC0_fifo_synth),
    .VC1(data_out_VC1),
    .VC1_empty(empty_fifo_VC1),
    .VC1_pop(pop_VC1_fifo_synth),
    .clk(clk),
    .reset_L(reset_L)
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
module logica_pops_synth(VC0_empty, VC1_empty, D0_pause, D1_pause, clk, VC0_pop, VC1_pop, pop_delay_VC0, pop_delay_VC1);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
  input D0_pause;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
  input D1_pause;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
  input VC0_empty;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:2" *)
  output VC0_pop;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
  input VC1_empty;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:2" *)
  output VC1_pop;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
  input clk;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:2" *)
  output pop_delay_VC0;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:2" *)
  output pop_delay_VC1;
  NOR _3_ (
    .A(D0_pause),
    .B(D1_pause),
    .Y(_1_)
  );
  NOT _4_ (
    .A(_1_),
    .Y(_2_)
  );
  NOR _5_ (
    .A(VC0_empty),
    .B(_2_),
    .Y(VC0_pop)
  );
  NAND _6_ (
    .A(VC0_empty),
    .B(_1_),
    .Y(_0_)
  );
  NOR _7_ (
    .A(VC1_empty),
    .B(_0_),
    .Y(VC1_pop)
  );
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:4" *)
  DFF _8_ (
    .C(clk),
    .D(VC0_pop),
    .Q(pop_delay_VC0)
  );
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:4" *)
  DFF _9_ (
    .C(clk),
    .D(VC1_pop),
    .Q(pop_delay_VC1)
  );
endmodule
