/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "./final_logic_synth/D0_fifo_synth.v:1" *)
module D0_fifo_synth(clk, reset_L, wr_enable, rd_enable, init, data_in, Umbral_D0, full_fifo_D0, empty_fifo_D0, almost_full_fifo_D0, almost_empty_fifo_D0, error_D0_synth, data_out_D0_synth);
  (* src = "./final_logic_synth/D0_fifo_synth.v:35" *)
  wire [2:0] _000_;
  (* src = "./final_logic_synth/D0_fifo_synth.v:35" *)
  wire [5:0] _001_;
  (* src = "./final_logic_synth/D0_fifo_synth.v:35" *)
  wire [1:0] _002_;
  (* src = "./final_logic_synth/D0_fifo_synth.v:35" *)
  wire [1:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  (* src = "./final_logic_synth/D0_fifo_synth.v:8" *)
  input [3:0] Umbral_D0;
  (* src = "./final_logic_synth/D0_fifo_synth.v:12" *)
  output almost_empty_fifo_D0;
  (* src = "./final_logic_synth/D0_fifo_synth.v:11" *)
  output almost_full_fifo_D0;
  (* src = "./final_logic_synth/D0_fifo_synth.v:6" *)
  input clk;
  (* src = "./final_logic_synth/D0_fifo_synth.v:21" *)
  wire [2:0] cnt;
  (* src = "./final_logic_synth/D0_fifo_synth.v:7" *)
  input [5:0] data_in;
  (* src = "./final_logic_synth/D0_fifo_synth.v:14" *)
  output [5:0] data_out_D0_synth;
  (* src = "./final_logic_synth/D0_fifo_synth.v:10" *)
  output empty_fifo_D0;
  (* src = "./final_logic_synth/D0_fifo_synth.v:13" *)
  output error_D0_synth;
  (* src = "./final_logic_synth/D0_fifo_synth.v:9" *)
  output full_fifo_D0;
  (* src = "./final_logic_synth/D0_fifo_synth.v:22" *)
  wire full_fifo_D0_reg;
  (* src = "./final_logic_synth/D0_fifo_synth.v:30" *)
  wire [31:0] i;
  (* src = "./final_logic_synth/D0_fifo_synth.v:6" *)
  input init;
  wire [5:0] \mem[0] ;
  wire [5:0] \mem[1] ;
  wire [5:0] \mem[2] ;
  wire [5:0] \mem[3] ;
  (* src = "./final_logic_synth/D0_fifo_synth.v:6" *)
  input rd_enable;
  (* src = "./final_logic_synth/D0_fifo_synth.v:20" *)
  wire [1:0] rd_ptr;
  (* src = "./final_logic_synth/D0_fifo_synth.v:6" *)
  input reset_L;
  (* src = "./final_logic_synth/D0_fifo_synth.v:6" *)
  input wr_enable;
  (* src = "./final_logic_synth/D0_fifo_synth.v:19" *)
  wire [1:0] wr_ptr;
  NOT _301_ (
    .A(rd_enable),
    .Y(_295_)
  );
  NOT _302_ (
    .A(wr_enable),
    .Y(_296_)
  );
  NOT _303_ (
    .A(cnt[2]),
    .Y(_297_)
  );
  NOT _304_ (
    .A(cnt[0]),
    .Y(_298_)
  );
  NOT _305_ (
    .A(cnt[1]),
    .Y(_299_)
  );
  NOT _306_ (
    .A(reset_L),
    .Y(_300_)
  );
  NOT _307_ (
    .A(init),
    .Y(_028_)
  );
  NOT _308_ (
    .A(\mem[2] [0]),
    .Y(_029_)
  );
  NOT _309_ (
    .A(\mem[2] [1]),
    .Y(_030_)
  );
  NOT _310_ (
    .A(\mem[2] [2]),
    .Y(_031_)
  );
  NOT _311_ (
    .A(\mem[2] [3]),
    .Y(_032_)
  );
  NOT _312_ (
    .A(\mem[2] [4]),
    .Y(_033_)
  );
  NOT _313_ (
    .A(\mem[2] [5]),
    .Y(_034_)
  );
  NOT _314_ (
    .A(data_in[0]),
    .Y(_035_)
  );
  NOT _315_ (
    .A(data_in[1]),
    .Y(_036_)
  );
  NOT _316_ (
    .A(data_in[2]),
    .Y(_037_)
  );
  NOT _317_ (
    .A(data_in[3]),
    .Y(_038_)
  );
  NOT _318_ (
    .A(data_in[4]),
    .Y(_039_)
  );
  NOT _319_ (
    .A(data_in[5]),
    .Y(_040_)
  );
  NOT _320_ (
    .A(wr_ptr[0]),
    .Y(_041_)
  );
  NOT _321_ (
    .A(wr_ptr[1]),
    .Y(_042_)
  );
  NOT _322_ (
    .A(rd_ptr[0]),
    .Y(_043_)
  );
  NOT _323_ (
    .A(rd_ptr[1]),
    .Y(_044_)
  );
  NOT _324_ (
    .A(\mem[3] [0]),
    .Y(_045_)
  );
  NOT _325_ (
    .A(\mem[1] [0]),
    .Y(_046_)
  );
  NOT _326_ (
    .A(\mem[1] [1]),
    .Y(_047_)
  );
  NOT _327_ (
    .A(\mem[1] [2]),
    .Y(_048_)
  );
  NOT _328_ (
    .A(\mem[1] [3]),
    .Y(_049_)
  );
  NOT _329_ (
    .A(\mem[1] [4]),
    .Y(_050_)
  );
  NOT _330_ (
    .A(\mem[1] [5]),
    .Y(_051_)
  );
  NOT _331_ (
    .A(\mem[0] [0]),
    .Y(_052_)
  );
  NOT _332_ (
    .A(\mem[0] [1]),
    .Y(_053_)
  );
  NOT _333_ (
    .A(\mem[0] [2]),
    .Y(_054_)
  );
  NOT _334_ (
    .A(\mem[0] [3]),
    .Y(_055_)
  );
  NOT _335_ (
    .A(\mem[0] [4]),
    .Y(_056_)
  );
  NOT _336_ (
    .A(\mem[0] [5]),
    .Y(_057_)
  );
  NOT _337_ (
    .A(Umbral_D0[1]),
    .Y(_058_)
  );
  NOT _338_ (
    .A(Umbral_D0[2]),
    .Y(_059_)
  );
  NOR _339_ (
    .A(cnt[0]),
    .B(cnt[1]),
    .Y(_060_)
  );
  NAND _340_ (
    .A(_298_),
    .B(_299_),
    .Y(_061_)
  );
  NAND _341_ (
    .A(cnt[2]),
    .B(_060_),
    .Y(_062_)
  );
  NOT _342_ (
    .A(_062_),
    .Y(full_fifo_D0)
  );
  NOR _343_ (
    .A(cnt[2]),
    .B(_061_),
    .Y(empty_fifo_D0)
  );
  NAND _344_ (
    .A(_297_),
    .B(Umbral_D0[2]),
    .Y(_063_)
  );
  NOR _345_ (
    .A(_299_),
    .B(Umbral_D0[1]),
    .Y(_064_)
  );
  NOR _346_ (
    .A(_297_),
    .B(Umbral_D0[2]),
    .Y(_065_)
  );
  NOR _347_ (
    .A(_064_),
    .B(_065_),
    .Y(_066_)
  );
  NAND _348_ (
    .A(_063_),
    .B(_066_),
    .Y(_067_)
  );
  NAND _349_ (
    .A(cnt[0]),
    .B(Umbral_D0[0]),
    .Y(_068_)
  );
  NOR _350_ (
    .A(cnt[0]),
    .B(Umbral_D0[0]),
    .Y(_069_)
  );
  NOT _351_ (
    .A(_069_),
    .Y(_070_)
  );
  NAND _352_ (
    .A(_068_),
    .B(_070_),
    .Y(_071_)
  );
  NOR _353_ (
    .A(cnt[1]),
    .B(_058_),
    .Y(_072_)
  );
  NOR _354_ (
    .A(Umbral_D0[3]),
    .B(_072_),
    .Y(_073_)
  );
  NAND _355_ (
    .A(_071_),
    .B(_073_),
    .Y(_074_)
  );
  NOR _356_ (
    .A(_067_),
    .B(_074_),
    .Y(almost_empty_fifo_D0)
  );
  NAND _357_ (
    .A(cnt[0]),
    .B(cnt[1]),
    .Y(_075_)
  );
  NAND _358_ (
    .A(Umbral_D0[0]),
    .B(_058_),
    .Y(_076_)
  );
  NAND _359_ (
    .A(_068_),
    .B(_072_),
    .Y(_077_)
  );
  NAND _360_ (
    .A(_076_),
    .B(_077_),
    .Y(_078_)
  );
  NAND _361_ (
    .A(_075_),
    .B(_078_),
    .Y(_079_)
  );
  NOR _362_ (
    .A(Umbral_D0[0]),
    .B(Umbral_D0[1]),
    .Y(_080_)
  );
  NOR _363_ (
    .A(_059_),
    .B(_080_),
    .Y(_081_)
  );
  NOR _364_ (
    .A(Umbral_D0[3]),
    .B(_081_),
    .Y(_082_)
  );
  NAND _365_ (
    .A(_297_),
    .B(_082_),
    .Y(_083_)
  );
  NAND _366_ (
    .A(_059_),
    .B(_080_),
    .Y(_084_)
  );
  NAND _367_ (
    .A(_079_),
    .B(_084_),
    .Y(_085_)
  );
  NOR _368_ (
    .A(_083_),
    .B(_085_),
    .Y(almost_full_fifo_D0)
  );
  NOR _369_ (
    .A(_300_),
    .B(_028_),
    .Y(_086_)
  );
  NAND _370_ (
    .A(reset_L),
    .B(init),
    .Y(_087_)
  );
  NOR _371_ (
    .A(full_fifo_D0),
    .B(_087_),
    .Y(_088_)
  );
  NAND _372_ (
    .A(_062_),
    .B(_086_),
    .Y(_089_)
  );
  NOR _373_ (
    .A(_296_),
    .B(_089_),
    .Y(_090_)
  );
  NAND _374_ (
    .A(wr_enable),
    .B(_088_),
    .Y(_091_)
  );
  NOR _375_ (
    .A(_041_),
    .B(_091_),
    .Y(_092_)
  );
  NAND _376_ (
    .A(wr_ptr[0]),
    .B(_090_),
    .Y(_093_)
  );
  NOR _377_ (
    .A(wr_ptr[1]),
    .B(_092_),
    .Y(_094_)
  );
  NAND _378_ (
    .A(_042_),
    .B(_093_),
    .Y(_095_)
  );
  NOR _379_ (
    .A(_091_),
    .B(_095_),
    .Y(_096_)
  );
  NAND _380_ (
    .A(_090_),
    .B(_094_),
    .Y(_097_)
  );
  NOR _381_ (
    .A(_052_),
    .B(_087_),
    .Y(_098_)
  );
  NOR _382_ (
    .A(_096_),
    .B(_098_),
    .Y(_099_)
  );
  NOR _383_ (
    .A(data_in[0]),
    .B(_097_),
    .Y(_100_)
  );
  NOR _384_ (
    .A(_035_),
    .B(_091_),
    .Y(_101_)
  );
  NOR _385_ (
    .A(_099_),
    .B(_100_),
    .Y(_004_)
  );
  NOR _386_ (
    .A(_053_),
    .B(_087_),
    .Y(_102_)
  );
  NOR _387_ (
    .A(_096_),
    .B(_102_),
    .Y(_103_)
  );
  NOR _388_ (
    .A(data_in[1]),
    .B(_097_),
    .Y(_104_)
  );
  NOR _389_ (
    .A(_036_),
    .B(_091_),
    .Y(_105_)
  );
  NOR _390_ (
    .A(_103_),
    .B(_104_),
    .Y(_005_)
  );
  NOR _391_ (
    .A(_054_),
    .B(_087_),
    .Y(_106_)
  );
  NOR _392_ (
    .A(_096_),
    .B(_106_),
    .Y(_107_)
  );
  NOR _393_ (
    .A(data_in[2]),
    .B(_097_),
    .Y(_108_)
  );
  NOR _394_ (
    .A(_037_),
    .B(_091_),
    .Y(_109_)
  );
  NOR _395_ (
    .A(_107_),
    .B(_108_),
    .Y(_006_)
  );
  NOR _396_ (
    .A(_055_),
    .B(_087_),
    .Y(_110_)
  );
  NOR _397_ (
    .A(_096_),
    .B(_110_),
    .Y(_111_)
  );
  NOR _398_ (
    .A(data_in[3]),
    .B(_097_),
    .Y(_112_)
  );
  NOR _399_ (
    .A(_038_),
    .B(_091_),
    .Y(_113_)
  );
  NOR _400_ (
    .A(_111_),
    .B(_112_),
    .Y(_007_)
  );
  NOR _401_ (
    .A(_056_),
    .B(_087_),
    .Y(_114_)
  );
  NOR _402_ (
    .A(_096_),
    .B(_114_),
    .Y(_115_)
  );
  NOR _403_ (
    .A(data_in[4]),
    .B(_097_),
    .Y(_116_)
  );
  NOR _404_ (
    .A(_039_),
    .B(_091_),
    .Y(_117_)
  );
  NOR _405_ (
    .A(_115_),
    .B(_116_),
    .Y(_008_)
  );
  NOR _406_ (
    .A(_057_),
    .B(_087_),
    .Y(_118_)
  );
  NOR _407_ (
    .A(_096_),
    .B(_118_),
    .Y(_119_)
  );
  NOR _408_ (
    .A(data_in[5]),
    .B(_097_),
    .Y(_120_)
  );
  NOR _409_ (
    .A(_040_),
    .B(_091_),
    .Y(_121_)
  );
  NOR _410_ (
    .A(_119_),
    .B(_120_),
    .Y(_009_)
  );
  NOR _411_ (
    .A(_042_),
    .B(_091_),
    .Y(_122_)
  );
  NAND _412_ (
    .A(wr_ptr[1]),
    .B(_090_),
    .Y(_123_)
  );
  NOR _413_ (
    .A(_087_),
    .B(_122_),
    .Y(_124_)
  );
  NAND _414_ (
    .A(_086_),
    .B(_123_),
    .Y(_125_)
  );
  NOR _415_ (
    .A(wr_ptr[0]),
    .B(_087_),
    .Y(_126_)
  );
  NAND _416_ (
    .A(_041_),
    .B(_086_),
    .Y(_127_)
  );
  NOR _417_ (
    .A(_124_),
    .B(_126_),
    .Y(_128_)
  );
  NAND _418_ (
    .A(_125_),
    .B(_127_),
    .Y(_129_)
  );
  NOR _419_ (
    .A(_101_),
    .B(_129_),
    .Y(_130_)
  );
  NOR _420_ (
    .A(\mem[3] [0]),
    .B(_128_),
    .Y(_131_)
  );
  NOR _421_ (
    .A(_130_),
    .B(_131_),
    .Y(_022_)
  );
  NOR _422_ (
    .A(_105_),
    .B(_129_),
    .Y(_132_)
  );
  NOR _423_ (
    .A(\mem[3] [1]),
    .B(_128_),
    .Y(_133_)
  );
  NOR _424_ (
    .A(_132_),
    .B(_133_),
    .Y(_023_)
  );
  NOR _425_ (
    .A(_109_),
    .B(_129_),
    .Y(_134_)
  );
  NOR _426_ (
    .A(\mem[3] [2]),
    .B(_128_),
    .Y(_135_)
  );
  NOR _427_ (
    .A(_134_),
    .B(_135_),
    .Y(_024_)
  );
  NOR _428_ (
    .A(_113_),
    .B(_129_),
    .Y(_136_)
  );
  NOR _429_ (
    .A(\mem[3] [3]),
    .B(_128_),
    .Y(_137_)
  );
  NOR _430_ (
    .A(_136_),
    .B(_137_),
    .Y(_025_)
  );
  NOR _431_ (
    .A(_117_),
    .B(_129_),
    .Y(_138_)
  );
  NOR _432_ (
    .A(\mem[3] [4]),
    .B(_128_),
    .Y(_139_)
  );
  NOR _433_ (
    .A(_138_),
    .B(_139_),
    .Y(_026_)
  );
  NOR _434_ (
    .A(_121_),
    .B(_129_),
    .Y(_140_)
  );
  NOR _435_ (
    .A(\mem[3] [5]),
    .B(_128_),
    .Y(_141_)
  );
  NOR _436_ (
    .A(_140_),
    .B(_141_),
    .Y(_027_)
  );
  NAND _437_ (
    .A(rd_enable),
    .B(_296_),
    .Y(_142_)
  );
  NAND _438_ (
    .A(_295_),
    .B(wr_enable),
    .Y(_143_)
  );
  NAND _439_ (
    .A(_142_),
    .B(_143_),
    .Y(_144_)
  );
  NAND _440_ (
    .A(_088_),
    .B(_144_),
    .Y(_145_)
  );
  NOR _441_ (
    .A(cnt[0]),
    .B(_145_),
    .Y(_146_)
  );
  NOT _442_ (
    .A(_146_),
    .Y(_147_)
  );
  NAND _443_ (
    .A(cnt[0]),
    .B(_145_),
    .Y(_148_)
  );
  NAND _444_ (
    .A(_147_),
    .B(_148_),
    .Y(_149_)
  );
  NAND _445_ (
    .A(rd_enable),
    .B(cnt[0]),
    .Y(_150_)
  );
  NOT _446_ (
    .A(_150_),
    .Y(_151_)
  );
  NOR _447_ (
    .A(_087_),
    .B(_151_),
    .Y(_152_)
  );
  NOR _448_ (
    .A(_062_),
    .B(_087_),
    .Y(_153_)
  );
  NAND _449_ (
    .A(rd_enable),
    .B(_153_),
    .Y(_154_)
  );
  NOT _450_ (
    .A(_154_),
    .Y(_155_)
  );
  NOR _451_ (
    .A(_149_),
    .B(_155_),
    .Y(_156_)
  );
  NOR _452_ (
    .A(_087_),
    .B(_156_),
    .Y(_000_[0])
  );
  NAND _453_ (
    .A(wr_enable),
    .B(cnt[0]),
    .Y(_157_)
  );
  NAND _454_ (
    .A(_142_),
    .B(_157_),
    .Y(_158_)
  );
  NAND _455_ (
    .A(_152_),
    .B(_158_),
    .Y(_159_)
  );
  NOR _456_ (
    .A(cnt[1]),
    .B(_159_),
    .Y(_160_)
  );
  NOT _457_ (
    .A(_160_),
    .Y(_161_)
  );
  NAND _458_ (
    .A(cnt[1]),
    .B(_159_),
    .Y(_162_)
  );
  NAND _459_ (
    .A(_161_),
    .B(_162_),
    .Y(_163_)
  );
  NAND _460_ (
    .A(_088_),
    .B(_163_),
    .Y(_164_)
  );
  NAND _461_ (
    .A(_154_),
    .B(_164_),
    .Y(_000_[1])
  );
  NOR _462_ (
    .A(_075_),
    .B(_143_),
    .Y(_165_)
  );
  NOR _463_ (
    .A(_061_),
    .B(_142_),
    .Y(_166_)
  );
  NAND _464_ (
    .A(cnt[2]),
    .B(_165_),
    .Y(_167_)
  );
  NOT _465_ (
    .A(_167_),
    .Y(_168_)
  );
  NOR _466_ (
    .A(cnt[2]),
    .B(_165_),
    .Y(_169_)
  );
  NOR _467_ (
    .A(_168_),
    .B(_169_),
    .Y(_170_)
  );
  NOR _468_ (
    .A(_166_),
    .B(_170_),
    .Y(_171_)
  );
  NOR _469_ (
    .A(rd_enable),
    .B(_087_),
    .Y(_172_)
  );
  NOT _470_ (
    .A(_172_),
    .Y(_173_)
  );
  NAND _471_ (
    .A(_086_),
    .B(_154_),
    .Y(_174_)
  );
  NOR _472_ (
    .A(_171_),
    .B(_174_),
    .Y(_000_[2])
  );
  NAND _473_ (
    .A(rd_enable),
    .B(rd_ptr[0]),
    .Y(_175_)
  );
  NOR _474_ (
    .A(rd_enable),
    .B(rd_ptr[0]),
    .Y(_176_)
  );
  NOR _475_ (
    .A(_087_),
    .B(_176_),
    .Y(_177_)
  );
  NAND _476_ (
    .A(_175_),
    .B(_177_),
    .Y(_178_)
  );
  NOT _477_ (
    .A(_178_),
    .Y(_002_[0])
  );
  NOR _478_ (
    .A(_044_),
    .B(_175_),
    .Y(_179_)
  );
  NAND _479_ (
    .A(_044_),
    .B(_175_),
    .Y(_180_)
  );
  NAND _480_ (
    .A(_086_),
    .B(_180_),
    .Y(_181_)
  );
  NOR _481_ (
    .A(_179_),
    .B(_181_),
    .Y(_002_[1])
  );
  NAND _482_ (
    .A(wr_ptr[0]),
    .B(_086_),
    .Y(_182_)
  );
  NAND _483_ (
    .A(_091_),
    .B(_182_),
    .Y(_183_)
  );
  NAND _484_ (
    .A(_093_),
    .B(_183_),
    .Y(_184_)
  );
  NOT _485_ (
    .A(_184_),
    .Y(_003_[0])
  );
  NOR _486_ (
    .A(_094_),
    .B(_128_),
    .Y(_003_[1])
  );
  NOR _487_ (
    .A(_123_),
    .B(_127_),
    .Y(_185_)
  );
  NAND _488_ (
    .A(_122_),
    .B(_126_),
    .Y(_186_)
  );
  NOR _489_ (
    .A(_029_),
    .B(_087_),
    .Y(_187_)
  );
  NOR _490_ (
    .A(_185_),
    .B(_187_),
    .Y(_188_)
  );
  NOR _491_ (
    .A(data_in[0]),
    .B(_186_),
    .Y(_189_)
  );
  NOR _492_ (
    .A(_188_),
    .B(_189_),
    .Y(_016_)
  );
  NOR _493_ (
    .A(_030_),
    .B(_087_),
    .Y(_190_)
  );
  NOR _494_ (
    .A(_185_),
    .B(_190_),
    .Y(_191_)
  );
  NOR _495_ (
    .A(data_in[1]),
    .B(_186_),
    .Y(_192_)
  );
  NOR _496_ (
    .A(_191_),
    .B(_192_),
    .Y(_017_)
  );
  NOR _497_ (
    .A(_031_),
    .B(_087_),
    .Y(_193_)
  );
  NOR _498_ (
    .A(_185_),
    .B(_193_),
    .Y(_194_)
  );
  NOR _499_ (
    .A(data_in[2]),
    .B(_186_),
    .Y(_195_)
  );
  NOR _500_ (
    .A(_194_),
    .B(_195_),
    .Y(_018_)
  );
  NOR _501_ (
    .A(_032_),
    .B(_087_),
    .Y(_196_)
  );
  NOR _502_ (
    .A(_185_),
    .B(_196_),
    .Y(_197_)
  );
  NOR _503_ (
    .A(data_in[3]),
    .B(_186_),
    .Y(_198_)
  );
  NOR _504_ (
    .A(_197_),
    .B(_198_),
    .Y(_019_)
  );
  NOR _505_ (
    .A(_033_),
    .B(_087_),
    .Y(_199_)
  );
  NOR _506_ (
    .A(_185_),
    .B(_199_),
    .Y(_200_)
  );
  NOR _507_ (
    .A(data_in[4]),
    .B(_186_),
    .Y(_201_)
  );
  NOR _508_ (
    .A(_200_),
    .B(_201_),
    .Y(_020_)
  );
  NOR _509_ (
    .A(_034_),
    .B(_087_),
    .Y(_202_)
  );
  NOR _510_ (
    .A(_185_),
    .B(_202_),
    .Y(_203_)
  );
  NOR _511_ (
    .A(data_in[5]),
    .B(_186_),
    .Y(_204_)
  );
  NOR _512_ (
    .A(_203_),
    .B(_204_),
    .Y(_021_)
  );
  NAND _513_ (
    .A(data_out_D0_synth[0]),
    .B(_153_),
    .Y(_205_)
  );
  NOR _514_ (
    .A(rd_enable),
    .B(_205_),
    .Y(_206_)
  );
  NOR _515_ (
    .A(rd_ptr[0]),
    .B(\mem[0] [0]),
    .Y(_207_)
  );
  NOR _516_ (
    .A(_043_),
    .B(\mem[1] [0]),
    .Y(_208_)
  );
  NOR _517_ (
    .A(_207_),
    .B(_208_),
    .Y(_209_)
  );
  NOR _518_ (
    .A(rd_ptr[1]),
    .B(_209_),
    .Y(_210_)
  );
  NOR _519_ (
    .A(_295_),
    .B(_087_),
    .Y(_211_)
  );
  NAND _520_ (
    .A(_029_),
    .B(_043_),
    .Y(_212_)
  );
  NAND _521_ (
    .A(rd_ptr[0]),
    .B(_045_),
    .Y(_213_)
  );
  NAND _522_ (
    .A(_212_),
    .B(_213_),
    .Y(_214_)
  );
  NAND _523_ (
    .A(rd_ptr[1]),
    .B(_214_),
    .Y(_215_)
  );
  NAND _524_ (
    .A(_211_),
    .B(_215_),
    .Y(_216_)
  );
  NOR _525_ (
    .A(_210_),
    .B(_216_),
    .Y(_217_)
  );
  NOR _526_ (
    .A(_206_),
    .B(_217_),
    .Y(_218_)
  );
  NOT _527_ (
    .A(_218_),
    .Y(_001_[0])
  );
  NOR _528_ (
    .A(_062_),
    .B(_173_),
    .Y(_219_)
  );
  NAND _529_ (
    .A(data_out_D0_synth[1]),
    .B(_219_),
    .Y(_220_)
  );
  NAND _530_ (
    .A(rd_ptr[0]),
    .B(\mem[1] [1]),
    .Y(_221_)
  );
  NAND _531_ (
    .A(_043_),
    .B(\mem[0] [1]),
    .Y(_222_)
  );
  NAND _532_ (
    .A(_221_),
    .B(_222_),
    .Y(_223_)
  );
  NOR _533_ (
    .A(rd_ptr[1]),
    .B(_223_),
    .Y(_224_)
  );
  NOR _534_ (
    .A(_030_),
    .B(rd_ptr[0]),
    .Y(_225_)
  );
  NAND _535_ (
    .A(rd_ptr[0]),
    .B(\mem[3] [1]),
    .Y(_226_)
  );
  NAND _536_ (
    .A(rd_ptr[1]),
    .B(_226_),
    .Y(_227_)
  );
  NOR _537_ (
    .A(_225_),
    .B(_227_),
    .Y(_228_)
  );
  NOR _538_ (
    .A(_224_),
    .B(_228_),
    .Y(_229_)
  );
  NAND _539_ (
    .A(_211_),
    .B(_229_),
    .Y(_230_)
  );
  NAND _540_ (
    .A(_220_),
    .B(_230_),
    .Y(_001_[1])
  );
  NAND _541_ (
    .A(data_out_D0_synth[2]),
    .B(_219_),
    .Y(_231_)
  );
  NOR _542_ (
    .A(rd_ptr[1]),
    .B(\mem[1] [2]),
    .Y(_232_)
  );
  NOR _543_ (
    .A(_044_),
    .B(\mem[3] [2]),
    .Y(_233_)
  );
  NOR _544_ (
    .A(_232_),
    .B(_233_),
    .Y(_234_)
  );
  NOR _545_ (
    .A(_043_),
    .B(_234_),
    .Y(_235_)
  );
  NOR _546_ (
    .A(rd_ptr[1]),
    .B(\mem[0] [2]),
    .Y(_236_)
  );
  NOR _547_ (
    .A(\mem[2] [2]),
    .B(_044_),
    .Y(_237_)
  );
  NOR _548_ (
    .A(_236_),
    .B(_237_),
    .Y(_238_)
  );
  NOR _549_ (
    .A(rd_ptr[0]),
    .B(_238_),
    .Y(_239_)
  );
  NOR _550_ (
    .A(_235_),
    .B(_239_),
    .Y(_240_)
  );
  NAND _551_ (
    .A(_211_),
    .B(_240_),
    .Y(_241_)
  );
  NAND _552_ (
    .A(_231_),
    .B(_241_),
    .Y(_001_[2])
  );
  NAND _553_ (
    .A(data_out_D0_synth[3]),
    .B(_219_),
    .Y(_242_)
  );
  NOR _554_ (
    .A(rd_ptr[1]),
    .B(\mem[1] [3]),
    .Y(_243_)
  );
  NOR _555_ (
    .A(_044_),
    .B(\mem[3] [3]),
    .Y(_244_)
  );
  NOR _556_ (
    .A(_243_),
    .B(_244_),
    .Y(_245_)
  );
  NOR _557_ (
    .A(_043_),
    .B(_245_),
    .Y(_246_)
  );
  NOR _558_ (
    .A(rd_ptr[1]),
    .B(\mem[0] [3]),
    .Y(_247_)
  );
  NOR _559_ (
    .A(\mem[2] [3]),
    .B(_044_),
    .Y(_248_)
  );
  NOR _560_ (
    .A(_247_),
    .B(_248_),
    .Y(_249_)
  );
  NOR _561_ (
    .A(rd_ptr[0]),
    .B(_249_),
    .Y(_250_)
  );
  NOR _562_ (
    .A(_246_),
    .B(_250_),
    .Y(_251_)
  );
  NAND _563_ (
    .A(_211_),
    .B(_251_),
    .Y(_252_)
  );
  NAND _564_ (
    .A(_242_),
    .B(_252_),
    .Y(_001_[3])
  );
  NAND _565_ (
    .A(data_out_D0_synth[4]),
    .B(_219_),
    .Y(_253_)
  );
  NOR _566_ (
    .A(rd_ptr[1]),
    .B(\mem[1] [4]),
    .Y(_254_)
  );
  NOR _567_ (
    .A(_044_),
    .B(\mem[3] [4]),
    .Y(_255_)
  );
  NOR _568_ (
    .A(_254_),
    .B(_255_),
    .Y(_256_)
  );
  NOR _569_ (
    .A(_043_),
    .B(_256_),
    .Y(_257_)
  );
  NOR _570_ (
    .A(rd_ptr[1]),
    .B(\mem[0] [4]),
    .Y(_258_)
  );
  NOR _571_ (
    .A(\mem[2] [4]),
    .B(_044_),
    .Y(_259_)
  );
  NOR _572_ (
    .A(_258_),
    .B(_259_),
    .Y(_260_)
  );
  NOR _573_ (
    .A(rd_ptr[0]),
    .B(_260_),
    .Y(_261_)
  );
  NOR _574_ (
    .A(_257_),
    .B(_261_),
    .Y(_262_)
  );
  NAND _575_ (
    .A(_211_),
    .B(_262_),
    .Y(_263_)
  );
  NAND _576_ (
    .A(_253_),
    .B(_263_),
    .Y(_001_[4])
  );
  NAND _577_ (
    .A(data_out_D0_synth[5]),
    .B(_219_),
    .Y(_264_)
  );
  NOR _578_ (
    .A(rd_ptr[1]),
    .B(\mem[1] [5]),
    .Y(_265_)
  );
  NOR _579_ (
    .A(_044_),
    .B(\mem[3] [5]),
    .Y(_266_)
  );
  NOR _580_ (
    .A(_265_),
    .B(_266_),
    .Y(_267_)
  );
  NOR _581_ (
    .A(_043_),
    .B(_267_),
    .Y(_268_)
  );
  NOR _582_ (
    .A(rd_ptr[1]),
    .B(\mem[0] [5]),
    .Y(_269_)
  );
  NOR _583_ (
    .A(\mem[2] [5]),
    .B(_044_),
    .Y(_270_)
  );
  NOR _584_ (
    .A(_269_),
    .B(_270_),
    .Y(_271_)
  );
  NOR _585_ (
    .A(rd_ptr[0]),
    .B(_271_),
    .Y(_272_)
  );
  NOR _586_ (
    .A(_268_),
    .B(_272_),
    .Y(_273_)
  );
  NAND _587_ (
    .A(_211_),
    .B(_273_),
    .Y(_274_)
  );
  NAND _588_ (
    .A(_264_),
    .B(_274_),
    .Y(_001_[5])
  );
  NOR _589_ (
    .A(_093_),
    .B(_125_),
    .Y(_275_)
  );
  NAND _590_ (
    .A(_092_),
    .B(_124_),
    .Y(_276_)
  );
  NOR _591_ (
    .A(_046_),
    .B(_087_),
    .Y(_277_)
  );
  NOR _592_ (
    .A(_275_),
    .B(_277_),
    .Y(_278_)
  );
  NOR _593_ (
    .A(data_in[0]),
    .B(_276_),
    .Y(_279_)
  );
  NOR _594_ (
    .A(_278_),
    .B(_279_),
    .Y(_010_)
  );
  NOR _595_ (
    .A(_047_),
    .B(_087_),
    .Y(_280_)
  );
  NAND _596_ (
    .A(_276_),
    .B(_280_),
    .Y(_281_)
  );
  NAND _597_ (
    .A(data_in[1]),
    .B(_275_),
    .Y(_282_)
  );
  NAND _598_ (
    .A(_281_),
    .B(_282_),
    .Y(_011_)
  );
  NOR _599_ (
    .A(_048_),
    .B(_087_),
    .Y(_283_)
  );
  NOR _600_ (
    .A(_275_),
    .B(_283_),
    .Y(_284_)
  );
  NOR _601_ (
    .A(data_in[2]),
    .B(_276_),
    .Y(_285_)
  );
  NOR _602_ (
    .A(_284_),
    .B(_285_),
    .Y(_012_)
  );
  NOR _603_ (
    .A(_049_),
    .B(_087_),
    .Y(_286_)
  );
  NOR _604_ (
    .A(_275_),
    .B(_286_),
    .Y(_287_)
  );
  NOR _605_ (
    .A(data_in[3]),
    .B(_276_),
    .Y(_288_)
  );
  NOR _606_ (
    .A(_287_),
    .B(_288_),
    .Y(_013_)
  );
  NOR _607_ (
    .A(_050_),
    .B(_087_),
    .Y(_289_)
  );
  NOR _608_ (
    .A(_275_),
    .B(_289_),
    .Y(_290_)
  );
  NOR _609_ (
    .A(data_in[4]),
    .B(_276_),
    .Y(_291_)
  );
  NOR _610_ (
    .A(_290_),
    .B(_291_),
    .Y(_014_)
  );
  NOR _611_ (
    .A(_051_),
    .B(_087_),
    .Y(_292_)
  );
  NOR _612_ (
    .A(_275_),
    .B(_292_),
    .Y(_293_)
  );
  NOR _613_ (
    .A(data_in[5]),
    .B(_276_),
    .Y(_294_)
  );
  NOR _614_ (
    .A(_293_),
    .B(_294_),
    .Y(_015_)
  );
  NOR _615_ (
    .A(_297_),
    .B(_060_),
    .Y(error_D0_synth)
  );
  DFF _616_ (
    .C(clk),
    .D(_010_),
    .Q(\mem[1] [0])
  );
  DFF _617_ (
    .C(clk),
    .D(_011_),
    .Q(\mem[1] [1])
  );
  DFF _618_ (
    .C(clk),
    .D(_012_),
    .Q(\mem[1] [2])
  );
  DFF _619_ (
    .C(clk),
    .D(_013_),
    .Q(\mem[1] [3])
  );
  DFF _620_ (
    .C(clk),
    .D(_014_),
    .Q(\mem[1] [4])
  );
  DFF _621_ (
    .C(clk),
    .D(_015_),
    .Q(\mem[1] [5])
  );
  DFF _622_ (
    .C(clk),
    .D(_016_),
    .Q(\mem[2] [0])
  );
  DFF _623_ (
    .C(clk),
    .D(_017_),
    .Q(\mem[2] [1])
  );
  DFF _624_ (
    .C(clk),
    .D(_018_),
    .Q(\mem[2] [2])
  );
  DFF _625_ (
    .C(clk),
    .D(_019_),
    .Q(\mem[2] [3])
  );
  DFF _626_ (
    .C(clk),
    .D(_020_),
    .Q(\mem[2] [4])
  );
  DFF _627_ (
    .C(clk),
    .D(_021_),
    .Q(\mem[2] [5])
  );
  DFF _628_ (
    .C(clk),
    .D(_004_),
    .Q(\mem[0] [0])
  );
  DFF _629_ (
    .C(clk),
    .D(_005_),
    .Q(\mem[0] [1])
  );
  DFF _630_ (
    .C(clk),
    .D(_006_),
    .Q(\mem[0] [2])
  );
  DFF _631_ (
    .C(clk),
    .D(_007_),
    .Q(\mem[0] [3])
  );
  DFF _632_ (
    .C(clk),
    .D(_008_),
    .Q(\mem[0] [4])
  );
  DFF _633_ (
    .C(clk),
    .D(_009_),
    .Q(\mem[0] [5])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:35" *)
  DFF _634_ (
    .C(clk),
    .D(_001_[0]),
    .Q(data_out_D0_synth[0])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:35" *)
  DFF _635_ (
    .C(clk),
    .D(_001_[1]),
    .Q(data_out_D0_synth[1])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:35" *)
  DFF _636_ (
    .C(clk),
    .D(_001_[2]),
    .Q(data_out_D0_synth[2])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:35" *)
  DFF _637_ (
    .C(clk),
    .D(_001_[3]),
    .Q(data_out_D0_synth[3])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:35" *)
  DFF _638_ (
    .C(clk),
    .D(_001_[4]),
    .Q(data_out_D0_synth[4])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:35" *)
  DFF _639_ (
    .C(clk),
    .D(_001_[5]),
    .Q(data_out_D0_synth[5])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:35" *)
  DFF _640_ (
    .C(clk),
    .D(_003_[0]),
    .Q(wr_ptr[0])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:35" *)
  DFF _641_ (
    .C(clk),
    .D(_003_[1]),
    .Q(wr_ptr[1])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:35" *)
  DFF _642_ (
    .C(clk),
    .D(_000_[0]),
    .Q(cnt[0])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:35" *)
  DFF _643_ (
    .C(clk),
    .D(_000_[1]),
    .Q(cnt[1])
  );
  (* src = "./final_logic_synth/D0_fifo_synth.v:35" *)
  DFF _644_ (
    .C(clk),
    .D(_000_[2]),
    .Q(cnt[2])
  );
  DFF _645_ (
    .C(clk),
    .D(_002_[0]),
    .Q(rd_ptr[0])
  );
  DFF _646_ (
    .C(clk),
    .D(_002_[1]),
    .Q(rd_ptr[1])
  );
  DFF _647_ (
    .C(clk),
    .D(_022_),
    .Q(\mem[3] [0])
  );
  DFF _648_ (
    .C(clk),
    .D(_023_),
    .Q(\mem[3] [1])
  );
  DFF _649_ (
    .C(clk),
    .D(_024_),
    .Q(\mem[3] [2])
  );
  DFF _650_ (
    .C(clk),
    .D(_025_),
    .Q(\mem[3] [3])
  );
  DFF _651_ (
    .C(clk),
    .D(_026_),
    .Q(\mem[3] [4])
  );
  DFF _652_ (
    .C(clk),
    .D(_027_),
    .Q(\mem[3] [5])
  );
  assign full_fifo_D0_reg = full_fifo_D0;
  assign i = 32'd4;
endmodule

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "./final_logic_synth/D1_fifo_synth.v:1" *)
module D1_fifo_synth(clk, reset_L, wr_enable, rd_enable, init, data_in, Umbral_D1, full_fifo_D1, empty_fifo_D1, almost_full_fifo_D1, almost_empty_fifo_D1, error_D1_synth, data_out_D1_synth);
  (* src = "./final_logic_synth/D1_fifo_synth.v:35" *)
  wire [2:0] _000_;
  (* src = "./final_logic_synth/D1_fifo_synth.v:35" *)
  wire [5:0] _001_;
  (* src = "./final_logic_synth/D1_fifo_synth.v:35" *)
  wire [1:0] _002_;
  (* src = "./final_logic_synth/D1_fifo_synth.v:35" *)
  wire [1:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  (* src = "./final_logic_synth/D1_fifo_synth.v:8" *)
  input [3:0] Umbral_D1;
  (* src = "./final_logic_synth/D1_fifo_synth.v:12" *)
  output almost_empty_fifo_D1;
  (* src = "./final_logic_synth/D1_fifo_synth.v:11" *)
  output almost_full_fifo_D1;
  (* src = "./final_logic_synth/D1_fifo_synth.v:6" *)
  input clk;
  (* src = "./final_logic_synth/D1_fifo_synth.v:21" *)
  wire [2:0] cnt;
  (* src = "./final_logic_synth/D1_fifo_synth.v:7" *)
  input [5:0] data_in;
  (* src = "./final_logic_synth/D1_fifo_synth.v:14" *)
  output [5:0] data_out_D1_synth;
  (* src = "./final_logic_synth/D1_fifo_synth.v:10" *)
  output empty_fifo_D1;
  (* src = "./final_logic_synth/D1_fifo_synth.v:13" *)
  output error_D1_synth;
  (* src = "./final_logic_synth/D1_fifo_synth.v:9" *)
  output full_fifo_D1;
  (* src = "./final_logic_synth/D1_fifo_synth.v:23" *)
  wire full_fifo_D1_reg;
  (* src = "./final_logic_synth/D1_fifo_synth.v:32" *)
  wire [31:0] i;
  (* src = "./final_logic_synth/D1_fifo_synth.v:6" *)
  input init;
  wire [5:0] \mem[0] ;
  wire [5:0] \mem[1] ;
  wire [5:0] \mem[2] ;
  wire [5:0] \mem[3] ;
  (* src = "./final_logic_synth/D1_fifo_synth.v:6" *)
  input rd_enable;
  (* src = "./final_logic_synth/D1_fifo_synth.v:20" *)
  wire [1:0] rd_ptr;
  (* src = "./final_logic_synth/D1_fifo_synth.v:6" *)
  input reset_L;
  (* src = "./final_logic_synth/D1_fifo_synth.v:6" *)
  input wr_enable;
  (* src = "./final_logic_synth/D1_fifo_synth.v:19" *)
  wire [1:0] wr_ptr;
  NOT _297_ (
    .A(wr_enable),
    .Y(_291_)
  );
  NOT _298_ (
    .A(rd_enable),
    .Y(_292_)
  );
  NOT _299_ (
    .A(cnt[2]),
    .Y(_293_)
  );
  NOT _300_ (
    .A(cnt[0]),
    .Y(_294_)
  );
  NOT _301_ (
    .A(cnt[1]),
    .Y(_295_)
  );
  NOT _302_ (
    .A(reset_L),
    .Y(_296_)
  );
  NOT _303_ (
    .A(init),
    .Y(_028_)
  );
  NOT _304_ (
    .A(\mem[2] [0]),
    .Y(_029_)
  );
  NOT _305_ (
    .A(\mem[2] [1]),
    .Y(_030_)
  );
  NOT _306_ (
    .A(\mem[2] [2]),
    .Y(_031_)
  );
  NOT _307_ (
    .A(\mem[2] [3]),
    .Y(_032_)
  );
  NOT _308_ (
    .A(\mem[2] [4]),
    .Y(_033_)
  );
  NOT _309_ (
    .A(\mem[2] [5]),
    .Y(_034_)
  );
  NOT _310_ (
    .A(data_in[0]),
    .Y(_035_)
  );
  NOT _311_ (
    .A(data_in[1]),
    .Y(_036_)
  );
  NOT _312_ (
    .A(data_in[2]),
    .Y(_037_)
  );
  NOT _313_ (
    .A(data_in[3]),
    .Y(_038_)
  );
  NOT _314_ (
    .A(data_in[4]),
    .Y(_039_)
  );
  NOT _315_ (
    .A(data_in[5]),
    .Y(_040_)
  );
  NOT _316_ (
    .A(wr_ptr[0]),
    .Y(_041_)
  );
  NOT _317_ (
    .A(wr_ptr[1]),
    .Y(_042_)
  );
  NOT _318_ (
    .A(\mem[1] [0]),
    .Y(_043_)
  );
  NOT _319_ (
    .A(\mem[1] [1]),
    .Y(_044_)
  );
  NOT _320_ (
    .A(\mem[1] [2]),
    .Y(_045_)
  );
  NOT _321_ (
    .A(\mem[1] [3]),
    .Y(_046_)
  );
  NOT _322_ (
    .A(\mem[1] [4]),
    .Y(_047_)
  );
  NOT _323_ (
    .A(\mem[1] [5]),
    .Y(_048_)
  );
  NOT _324_ (
    .A(rd_ptr[0]),
    .Y(_049_)
  );
  NOT _325_ (
    .A(rd_ptr[1]),
    .Y(_050_)
  );
  NOT _326_ (
    .A(\mem[0] [0]),
    .Y(_051_)
  );
  NOT _327_ (
    .A(\mem[0] [1]),
    .Y(_052_)
  );
  NOT _328_ (
    .A(\mem[0] [2]),
    .Y(_053_)
  );
  NOT _329_ (
    .A(\mem[0] [3]),
    .Y(_054_)
  );
  NOT _330_ (
    .A(\mem[0] [4]),
    .Y(_055_)
  );
  NOT _331_ (
    .A(\mem[0] [5]),
    .Y(_056_)
  );
  NOT _332_ (
    .A(Umbral_D1[1]),
    .Y(_057_)
  );
  NOR _333_ (
    .A(cnt[0]),
    .B(cnt[1]),
    .Y(_058_)
  );
  NOT _334_ (
    .A(_058_),
    .Y(_059_)
  );
  NAND _335_ (
    .A(cnt[2]),
    .B(_058_),
    .Y(_060_)
  );
  NOT _336_ (
    .A(_060_),
    .Y(full_fifo_D1)
  );
  NOR _337_ (
    .A(cnt[2]),
    .B(_059_),
    .Y(empty_fifo_D1)
  );
  NAND _338_ (
    .A(_293_),
    .B(Umbral_D1[2]),
    .Y(_061_)
  );
  NOR _339_ (
    .A(_295_),
    .B(Umbral_D1[1]),
    .Y(_062_)
  );
  NOR _340_ (
    .A(_293_),
    .B(Umbral_D1[2]),
    .Y(_063_)
  );
  NOR _341_ (
    .A(_062_),
    .B(_063_),
    .Y(_064_)
  );
  NAND _342_ (
    .A(_061_),
    .B(_064_),
    .Y(_065_)
  );
  NAND _343_ (
    .A(cnt[0]),
    .B(Umbral_D1[0]),
    .Y(_066_)
  );
  NOR _344_ (
    .A(cnt[0]),
    .B(Umbral_D1[0]),
    .Y(_067_)
  );
  NOT _345_ (
    .A(_067_),
    .Y(_068_)
  );
  NAND _346_ (
    .A(_066_),
    .B(_068_),
    .Y(_069_)
  );
  NOR _347_ (
    .A(cnt[1]),
    .B(_057_),
    .Y(_070_)
  );
  NOR _348_ (
    .A(Umbral_D1[3]),
    .B(_070_),
    .Y(_071_)
  );
  NAND _349_ (
    .A(_069_),
    .B(_071_),
    .Y(_072_)
  );
  NOR _350_ (
    .A(_065_),
    .B(_072_),
    .Y(almost_empty_fifo_D1)
  );
  NOR _351_ (
    .A(_294_),
    .B(_295_),
    .Y(_073_)
  );
  NAND _352_ (
    .A(Umbral_D1[0]),
    .B(_073_),
    .Y(_074_)
  );
  NOR _353_ (
    .A(Umbral_D1[1]),
    .B(Umbral_D1[2]),
    .Y(_075_)
  );
  NAND _354_ (
    .A(_074_),
    .B(_075_),
    .Y(_076_)
  );
  NOR _355_ (
    .A(Umbral_D1[0]),
    .B(Umbral_D1[1]),
    .Y(_077_)
  );
  NOT _356_ (
    .A(_077_),
    .Y(_078_)
  );
  NAND _357_ (
    .A(Umbral_D1[2]),
    .B(_078_),
    .Y(_079_)
  );
  NOR _358_ (
    .A(Umbral_D1[3]),
    .B(cnt[2]),
    .Y(_080_)
  );
  NAND _359_ (
    .A(_079_),
    .B(_080_),
    .Y(_081_)
  );
  NAND _360_ (
    .A(_066_),
    .B(_070_),
    .Y(_082_)
  );
  NAND _361_ (
    .A(_076_),
    .B(_082_),
    .Y(_083_)
  );
  NOR _362_ (
    .A(_081_),
    .B(_083_),
    .Y(almost_full_fifo_D1)
  );
  NOR _363_ (
    .A(_296_),
    .B(_028_),
    .Y(_084_)
  );
  NAND _364_ (
    .A(reset_L),
    .B(init),
    .Y(_085_)
  );
  NOR _365_ (
    .A(full_fifo_D1),
    .B(_085_),
    .Y(_086_)
  );
  NAND _366_ (
    .A(_060_),
    .B(_084_),
    .Y(_087_)
  );
  NOR _367_ (
    .A(_291_),
    .B(_087_),
    .Y(_088_)
  );
  NAND _368_ (
    .A(wr_enable),
    .B(_086_),
    .Y(_089_)
  );
  NOR _369_ (
    .A(wr_ptr[0]),
    .B(_089_),
    .Y(_090_)
  );
  NAND _370_ (
    .A(_041_),
    .B(_088_),
    .Y(_091_)
  );
  NOR _371_ (
    .A(wr_ptr[1]),
    .B(_091_),
    .Y(_092_)
  );
  NAND _372_ (
    .A(_042_),
    .B(_090_),
    .Y(_093_)
  );
  NOR _373_ (
    .A(_051_),
    .B(_085_),
    .Y(_094_)
  );
  NOR _374_ (
    .A(_092_),
    .B(_094_),
    .Y(_095_)
  );
  NOR _375_ (
    .A(data_in[0]),
    .B(_093_),
    .Y(_096_)
  );
  NOR _376_ (
    .A(_095_),
    .B(_096_),
    .Y(_004_)
  );
  NOR _377_ (
    .A(_052_),
    .B(_085_),
    .Y(_097_)
  );
  NOR _378_ (
    .A(_092_),
    .B(_097_),
    .Y(_098_)
  );
  NOR _379_ (
    .A(data_in[1]),
    .B(_093_),
    .Y(_099_)
  );
  NOR _380_ (
    .A(_098_),
    .B(_099_),
    .Y(_005_)
  );
  NOR _381_ (
    .A(_053_),
    .B(_085_),
    .Y(_100_)
  );
  NOR _382_ (
    .A(_092_),
    .B(_100_),
    .Y(_101_)
  );
  NOR _383_ (
    .A(data_in[2]),
    .B(_093_),
    .Y(_102_)
  );
  NOR _384_ (
    .A(_101_),
    .B(_102_),
    .Y(_006_)
  );
  NOR _385_ (
    .A(_054_),
    .B(_085_),
    .Y(_103_)
  );
  NOR _386_ (
    .A(_092_),
    .B(_103_),
    .Y(_104_)
  );
  NOR _387_ (
    .A(data_in[3]),
    .B(_093_),
    .Y(_105_)
  );
  NOR _388_ (
    .A(_104_),
    .B(_105_),
    .Y(_007_)
  );
  NOR _389_ (
    .A(_055_),
    .B(_085_),
    .Y(_106_)
  );
  NOR _390_ (
    .A(_092_),
    .B(_106_),
    .Y(_107_)
  );
  NOR _391_ (
    .A(data_in[4]),
    .B(_093_),
    .Y(_108_)
  );
  NOR _392_ (
    .A(_107_),
    .B(_108_),
    .Y(_008_)
  );
  NOR _393_ (
    .A(_056_),
    .B(_085_),
    .Y(_109_)
  );
  NOR _394_ (
    .A(_092_),
    .B(_109_),
    .Y(_110_)
  );
  NOR _395_ (
    .A(data_in[5]),
    .B(_093_),
    .Y(_111_)
  );
  NOR _396_ (
    .A(_110_),
    .B(_111_),
    .Y(_009_)
  );
  NOR _397_ (
    .A(_041_),
    .B(_089_),
    .Y(_112_)
  );
  NAND _398_ (
    .A(wr_ptr[0]),
    .B(_088_),
    .Y(_113_)
  );
  NOR _399_ (
    .A(_085_),
    .B(_112_),
    .Y(_114_)
  );
  NAND _400_ (
    .A(_084_),
    .B(_113_),
    .Y(_115_)
  );
  NOR _401_ (
    .A(wr_ptr[1]),
    .B(_085_),
    .Y(_116_)
  );
  NOT _402_ (
    .A(_116_),
    .Y(_117_)
  );
  NOR _403_ (
    .A(_114_),
    .B(_116_),
    .Y(_118_)
  );
  NAND _404_ (
    .A(_115_),
    .B(_117_),
    .Y(_119_)
  );
  NOR _405_ (
    .A(_035_),
    .B(_089_),
    .Y(_120_)
  );
  NOR _406_ (
    .A(_119_),
    .B(_120_),
    .Y(_121_)
  );
  NOR _407_ (
    .A(\mem[3] [0]),
    .B(_118_),
    .Y(_122_)
  );
  NOR _408_ (
    .A(_121_),
    .B(_122_),
    .Y(_022_)
  );
  NOR _409_ (
    .A(_036_),
    .B(_089_),
    .Y(_123_)
  );
  NOR _410_ (
    .A(_119_),
    .B(_123_),
    .Y(_124_)
  );
  NOR _411_ (
    .A(\mem[3] [1]),
    .B(_118_),
    .Y(_125_)
  );
  NOR _412_ (
    .A(_124_),
    .B(_125_),
    .Y(_023_)
  );
  NOR _413_ (
    .A(_037_),
    .B(_089_),
    .Y(_126_)
  );
  NOR _414_ (
    .A(_119_),
    .B(_126_),
    .Y(_127_)
  );
  NOR _415_ (
    .A(\mem[3] [2]),
    .B(_118_),
    .Y(_128_)
  );
  NOR _416_ (
    .A(_127_),
    .B(_128_),
    .Y(_024_)
  );
  NOR _417_ (
    .A(_038_),
    .B(_089_),
    .Y(_129_)
  );
  NOR _418_ (
    .A(_119_),
    .B(_129_),
    .Y(_130_)
  );
  NOR _419_ (
    .A(\mem[3] [3]),
    .B(_118_),
    .Y(_131_)
  );
  NOR _420_ (
    .A(_130_),
    .B(_131_),
    .Y(_025_)
  );
  NOR _421_ (
    .A(_039_),
    .B(_089_),
    .Y(_132_)
  );
  NOR _422_ (
    .A(_119_),
    .B(_132_),
    .Y(_133_)
  );
  NOR _423_ (
    .A(\mem[3] [4]),
    .B(_118_),
    .Y(_134_)
  );
  NOR _424_ (
    .A(_133_),
    .B(_134_),
    .Y(_026_)
  );
  NOR _425_ (
    .A(_040_),
    .B(_089_),
    .Y(_135_)
  );
  NOR _426_ (
    .A(_119_),
    .B(_135_),
    .Y(_136_)
  );
  NOR _427_ (
    .A(\mem[3] [5]),
    .B(_118_),
    .Y(_137_)
  );
  NOR _428_ (
    .A(_136_),
    .B(_137_),
    .Y(_027_)
  );
  NOR _429_ (
    .A(_042_),
    .B(_091_),
    .Y(_138_)
  );
  NAND _430_ (
    .A(wr_ptr[1]),
    .B(_090_),
    .Y(_139_)
  );
  NAND _431_ (
    .A(data_in[0]),
    .B(_138_),
    .Y(_140_)
  );
  NOR _432_ (
    .A(_029_),
    .B(_085_),
    .Y(_141_)
  );
  NAND _433_ (
    .A(_139_),
    .B(_141_),
    .Y(_142_)
  );
  NAND _434_ (
    .A(_140_),
    .B(_142_),
    .Y(_016_)
  );
  NAND _435_ (
    .A(data_in[1]),
    .B(_138_),
    .Y(_143_)
  );
  NOR _436_ (
    .A(_030_),
    .B(_085_),
    .Y(_144_)
  );
  NAND _437_ (
    .A(_139_),
    .B(_144_),
    .Y(_145_)
  );
  NAND _438_ (
    .A(_143_),
    .B(_145_),
    .Y(_017_)
  );
  NAND _439_ (
    .A(data_in[2]),
    .B(_138_),
    .Y(_146_)
  );
  NOR _440_ (
    .A(_031_),
    .B(_085_),
    .Y(_147_)
  );
  NAND _441_ (
    .A(_139_),
    .B(_147_),
    .Y(_148_)
  );
  NAND _442_ (
    .A(_146_),
    .B(_148_),
    .Y(_018_)
  );
  NAND _443_ (
    .A(data_in[3]),
    .B(_138_),
    .Y(_149_)
  );
  NOR _444_ (
    .A(_032_),
    .B(_085_),
    .Y(_150_)
  );
  NAND _445_ (
    .A(_139_),
    .B(_150_),
    .Y(_151_)
  );
  NAND _446_ (
    .A(_149_),
    .B(_151_),
    .Y(_019_)
  );
  NAND _447_ (
    .A(data_in[4]),
    .B(_138_),
    .Y(_152_)
  );
  NOR _448_ (
    .A(_033_),
    .B(_085_),
    .Y(_153_)
  );
  NAND _449_ (
    .A(_139_),
    .B(_153_),
    .Y(_154_)
  );
  NAND _450_ (
    .A(_152_),
    .B(_154_),
    .Y(_020_)
  );
  NAND _451_ (
    .A(data_in[5]),
    .B(_138_),
    .Y(_155_)
  );
  NOR _452_ (
    .A(_034_),
    .B(_085_),
    .Y(_156_)
  );
  NAND _453_ (
    .A(_139_),
    .B(_156_),
    .Y(_157_)
  );
  NAND _454_ (
    .A(_155_),
    .B(_157_),
    .Y(_021_)
  );
  NOR _455_ (
    .A(_113_),
    .B(_117_),
    .Y(_158_)
  );
  NAND _456_ (
    .A(_112_),
    .B(_116_),
    .Y(_159_)
  );
  NOR _457_ (
    .A(_043_),
    .B(_085_),
    .Y(_160_)
  );
  NOR _458_ (
    .A(_158_),
    .B(_160_),
    .Y(_161_)
  );
  NOR _459_ (
    .A(data_in[0]),
    .B(_159_),
    .Y(_162_)
  );
  NOR _460_ (
    .A(_161_),
    .B(_162_),
    .Y(_010_)
  );
  NOR _461_ (
    .A(_044_),
    .B(_085_),
    .Y(_163_)
  );
  NOR _462_ (
    .A(_158_),
    .B(_163_),
    .Y(_164_)
  );
  NOR _463_ (
    .A(data_in[1]),
    .B(_159_),
    .Y(_165_)
  );
  NOR _464_ (
    .A(_164_),
    .B(_165_),
    .Y(_011_)
  );
  NOR _465_ (
    .A(_045_),
    .B(_085_),
    .Y(_166_)
  );
  NOR _466_ (
    .A(_158_),
    .B(_166_),
    .Y(_167_)
  );
  NOR _467_ (
    .A(data_in[2]),
    .B(_159_),
    .Y(_168_)
  );
  NOR _468_ (
    .A(_167_),
    .B(_168_),
    .Y(_012_)
  );
  NOR _469_ (
    .A(_046_),
    .B(_085_),
    .Y(_169_)
  );
  NOR _470_ (
    .A(_158_),
    .B(_169_),
    .Y(_170_)
  );
  NOR _471_ (
    .A(data_in[3]),
    .B(_159_),
    .Y(_171_)
  );
  NOR _472_ (
    .A(_170_),
    .B(_171_),
    .Y(_013_)
  );
  NOR _473_ (
    .A(_047_),
    .B(_085_),
    .Y(_172_)
  );
  NOR _474_ (
    .A(_158_),
    .B(_172_),
    .Y(_173_)
  );
  NOR _475_ (
    .A(data_in[4]),
    .B(_159_),
    .Y(_174_)
  );
  NOR _476_ (
    .A(_173_),
    .B(_174_),
    .Y(_014_)
  );
  NOR _477_ (
    .A(_048_),
    .B(_085_),
    .Y(_175_)
  );
  NOR _478_ (
    .A(_158_),
    .B(_175_),
    .Y(_176_)
  );
  NOR _479_ (
    .A(data_in[5]),
    .B(_159_),
    .Y(_177_)
  );
  NOR _480_ (
    .A(_176_),
    .B(_177_),
    .Y(_015_)
  );
  NOR _481_ (
    .A(rd_enable),
    .B(_085_),
    .Y(_178_)
  );
  NOT _482_ (
    .A(_178_),
    .Y(_179_)
  );
  NOR _483_ (
    .A(_060_),
    .B(_179_),
    .Y(_180_)
  );
  NOR _484_ (
    .A(_060_),
    .B(_085_),
    .Y(_181_)
  );
  NOT _485_ (
    .A(_181_),
    .Y(_182_)
  );
  NOR _486_ (
    .A(wr_enable),
    .B(_292_),
    .Y(_183_)
  );
  NOR _487_ (
    .A(_291_),
    .B(rd_enable),
    .Y(_184_)
  );
  NOR _488_ (
    .A(_183_),
    .B(_184_),
    .Y(_185_)
  );
  NOR _489_ (
    .A(_087_),
    .B(_185_),
    .Y(_186_)
  );
  NOR _490_ (
    .A(cnt[0]),
    .B(_186_),
    .Y(_187_)
  );
  NAND _491_ (
    .A(cnt[0]),
    .B(_186_),
    .Y(_188_)
  );
  NOT _492_ (
    .A(_188_),
    .Y(_189_)
  );
  NOR _493_ (
    .A(_187_),
    .B(_189_),
    .Y(_190_)
  );
  NOR _494_ (
    .A(_292_),
    .B(_182_),
    .Y(_191_)
  );
  NAND _495_ (
    .A(data_out_D1_synth[0]),
    .B(_180_),
    .Y(_192_)
  );
  NOR _496_ (
    .A(rd_ptr[0]),
    .B(\mem[0] [0]),
    .Y(_193_)
  );
  NOR _497_ (
    .A(\mem[1] [0]),
    .B(_049_),
    .Y(_194_)
  );
  NOR _498_ (
    .A(_193_),
    .B(_194_),
    .Y(_195_)
  );
  NOR _499_ (
    .A(_292_),
    .B(_085_),
    .Y(_196_)
  );
  NAND _500_ (
    .A(rd_enable),
    .B(_084_),
    .Y(_197_)
  );
  NAND _501_ (
    .A(_029_),
    .B(_049_),
    .Y(_198_)
  );
  NOR _502_ (
    .A(\mem[3] [0]),
    .B(_049_),
    .Y(_199_)
  );
  NOR _503_ (
    .A(_050_),
    .B(_199_),
    .Y(_200_)
  );
  NAND _504_ (
    .A(_198_),
    .B(_200_),
    .Y(_201_)
  );
  NAND _505_ (
    .A(_050_),
    .B(_195_),
    .Y(_202_)
  );
  NAND _506_ (
    .A(_201_),
    .B(_202_),
    .Y(_203_)
  );
  NAND _507_ (
    .A(_060_),
    .B(_085_),
    .Y(_204_)
  );
  NAND _508_ (
    .A(rd_enable),
    .B(_204_),
    .Y(_205_)
  );
  NAND _509_ (
    .A(_196_),
    .B(_203_),
    .Y(_206_)
  );
  NAND _510_ (
    .A(_192_),
    .B(_206_),
    .Y(_001_[0])
  );
  NAND _511_ (
    .A(\mem[1] [1]),
    .B(rd_ptr[0]),
    .Y(_207_)
  );
  NAND _512_ (
    .A(_049_),
    .B(\mem[0] [1]),
    .Y(_208_)
  );
  NAND _513_ (
    .A(_207_),
    .B(_208_),
    .Y(_209_)
  );
  NOR _514_ (
    .A(rd_ptr[1]),
    .B(_209_),
    .Y(_210_)
  );
  NOR _515_ (
    .A(_030_),
    .B(rd_ptr[0]),
    .Y(_211_)
  );
  NAND _516_ (
    .A(\mem[3] [1]),
    .B(rd_ptr[0]),
    .Y(_212_)
  );
  NAND _517_ (
    .A(rd_ptr[1]),
    .B(_212_),
    .Y(_213_)
  );
  NOR _518_ (
    .A(_211_),
    .B(_213_),
    .Y(_214_)
  );
  NOR _519_ (
    .A(_210_),
    .B(_214_),
    .Y(_215_)
  );
  NAND _520_ (
    .A(_196_),
    .B(_215_),
    .Y(_216_)
  );
  NAND _521_ (
    .A(data_out_D1_synth[1]),
    .B(_180_),
    .Y(_217_)
  );
  NAND _522_ (
    .A(_216_),
    .B(_217_),
    .Y(_001_[1])
  );
  NAND _523_ (
    .A(data_out_D1_synth[2]),
    .B(_180_),
    .Y(_218_)
  );
  NOR _524_ (
    .A(_045_),
    .B(_049_),
    .Y(_219_)
  );
  NOR _525_ (
    .A(rd_ptr[0]),
    .B(_053_),
    .Y(_220_)
  );
  NOR _526_ (
    .A(_219_),
    .B(_220_),
    .Y(_221_)
  );
  NAND _527_ (
    .A(_050_),
    .B(_221_),
    .Y(_222_)
  );
  NOR _528_ (
    .A(_031_),
    .B(rd_ptr[0]),
    .Y(_223_)
  );
  NAND _529_ (
    .A(\mem[3] [2]),
    .B(rd_ptr[0]),
    .Y(_224_)
  );
  NAND _530_ (
    .A(rd_ptr[1]),
    .B(_224_),
    .Y(_225_)
  );
  NOR _531_ (
    .A(_223_),
    .B(_225_),
    .Y(_226_)
  );
  NOR _532_ (
    .A(_197_),
    .B(_226_),
    .Y(_227_)
  );
  NAND _533_ (
    .A(_222_),
    .B(_227_),
    .Y(_228_)
  );
  NAND _534_ (
    .A(_218_),
    .B(_228_),
    .Y(_001_[2])
  );
  NAND _535_ (
    .A(\mem[1] [3]),
    .B(rd_ptr[0]),
    .Y(_229_)
  );
  NAND _536_ (
    .A(_049_),
    .B(\mem[0] [3]),
    .Y(_230_)
  );
  NAND _537_ (
    .A(_229_),
    .B(_230_),
    .Y(_231_)
  );
  NOR _538_ (
    .A(rd_ptr[1]),
    .B(_231_),
    .Y(_232_)
  );
  NOR _539_ (
    .A(_032_),
    .B(rd_ptr[0]),
    .Y(_233_)
  );
  NAND _540_ (
    .A(\mem[3] [3]),
    .B(rd_ptr[0]),
    .Y(_234_)
  );
  NAND _541_ (
    .A(rd_ptr[1]),
    .B(_234_),
    .Y(_235_)
  );
  NOR _542_ (
    .A(_233_),
    .B(_235_),
    .Y(_236_)
  );
  NOR _543_ (
    .A(_232_),
    .B(_236_),
    .Y(_237_)
  );
  NAND _544_ (
    .A(_196_),
    .B(_237_),
    .Y(_238_)
  );
  NAND _545_ (
    .A(data_out_D1_synth[3]),
    .B(_180_),
    .Y(_239_)
  );
  NAND _546_ (
    .A(_238_),
    .B(_239_),
    .Y(_001_[3])
  );
  NOR _547_ (
    .A(_047_),
    .B(_049_),
    .Y(_240_)
  );
  NOR _548_ (
    .A(rd_ptr[0]),
    .B(_055_),
    .Y(_241_)
  );
  NOR _549_ (
    .A(_240_),
    .B(_241_),
    .Y(_242_)
  );
  NAND _550_ (
    .A(_050_),
    .B(_242_),
    .Y(_243_)
  );
  NOR _551_ (
    .A(_033_),
    .B(rd_ptr[0]),
    .Y(_244_)
  );
  NAND _552_ (
    .A(\mem[3] [4]),
    .B(rd_ptr[0]),
    .Y(_245_)
  );
  NAND _553_ (
    .A(rd_ptr[1]),
    .B(_245_),
    .Y(_246_)
  );
  NOR _554_ (
    .A(_244_),
    .B(_246_),
    .Y(_247_)
  );
  NOR _555_ (
    .A(_197_),
    .B(_247_),
    .Y(_248_)
  );
  NAND _556_ (
    .A(_243_),
    .B(_248_),
    .Y(_249_)
  );
  NAND _557_ (
    .A(data_out_D1_synth[4]),
    .B(_180_),
    .Y(_250_)
  );
  NAND _558_ (
    .A(_249_),
    .B(_250_),
    .Y(_001_[4])
  );
  NOR _559_ (
    .A(rd_ptr[0]),
    .B(\mem[0] [5]),
    .Y(_251_)
  );
  NOR _560_ (
    .A(\mem[1] [5]),
    .B(_049_),
    .Y(_252_)
  );
  NOR _561_ (
    .A(_251_),
    .B(_252_),
    .Y(_253_)
  );
  NOR _562_ (
    .A(rd_ptr[1]),
    .B(_253_),
    .Y(_254_)
  );
  NOR _563_ (
    .A(\mem[2] [5]),
    .B(rd_ptr[0]),
    .Y(_255_)
  );
  NOR _564_ (
    .A(\mem[3] [5]),
    .B(_049_),
    .Y(_256_)
  );
  NOR _565_ (
    .A(_255_),
    .B(_256_),
    .Y(_257_)
  );
  NOR _566_ (
    .A(_050_),
    .B(_257_),
    .Y(_258_)
  );
  NOR _567_ (
    .A(_205_),
    .B(_254_),
    .Y(_259_)
  );
  NOT _568_ (
    .A(_259_),
    .Y(_260_)
  );
  NOR _569_ (
    .A(_258_),
    .B(_260_),
    .Y(_261_)
  );
  NAND _570_ (
    .A(data_out_D1_synth[5]),
    .B(_087_),
    .Y(_262_)
  );
  NOR _571_ (
    .A(rd_enable),
    .B(_262_),
    .Y(_263_)
  );
  NOR _572_ (
    .A(_261_),
    .B(_263_),
    .Y(_264_)
  );
  NOR _573_ (
    .A(_085_),
    .B(_264_),
    .Y(_001_[5])
  );
  NOR _574_ (
    .A(_190_),
    .B(_191_),
    .Y(_265_)
  );
  NOR _575_ (
    .A(_085_),
    .B(_265_),
    .Y(_000_[0])
  );
  NOR _576_ (
    .A(_294_),
    .B(_184_),
    .Y(_266_)
  );
  NOR _577_ (
    .A(cnt[0]),
    .B(_183_),
    .Y(_267_)
  );
  NOR _578_ (
    .A(_266_),
    .B(_267_),
    .Y(_268_)
  );
  NAND _579_ (
    .A(_086_),
    .B(_268_),
    .Y(_269_)
  );
  NOR _580_ (
    .A(cnt[1]),
    .B(_269_),
    .Y(_270_)
  );
  NOT _581_ (
    .A(_270_),
    .Y(_271_)
  );
  NAND _582_ (
    .A(cnt[1]),
    .B(_269_),
    .Y(_272_)
  );
  NAND _583_ (
    .A(_271_),
    .B(_272_),
    .Y(_273_)
  );
  NOR _584_ (
    .A(_191_),
    .B(_273_),
    .Y(_274_)
  );
  NOR _585_ (
    .A(_085_),
    .B(_274_),
    .Y(_000_[1])
  );
  NAND _586_ (
    .A(_073_),
    .B(_184_),
    .Y(_275_)
  );
  NOR _587_ (
    .A(cnt[2]),
    .B(_275_),
    .Y(_276_)
  );
  NAND _588_ (
    .A(_058_),
    .B(_183_),
    .Y(_277_)
  );
  NAND _589_ (
    .A(cnt[2]),
    .B(_275_),
    .Y(_278_)
  );
  NAND _590_ (
    .A(_277_),
    .B(_278_),
    .Y(_279_)
  );
  NOR _591_ (
    .A(_276_),
    .B(_279_),
    .Y(_280_)
  );
  NOR _592_ (
    .A(_086_),
    .B(_178_),
    .Y(_281_)
  );
  NOR _593_ (
    .A(_280_),
    .B(_281_),
    .Y(_000_[2])
  );
  NAND _594_ (
    .A(rd_enable),
    .B(rd_ptr[0]),
    .Y(_282_)
  );
  NOR _595_ (
    .A(rd_enable),
    .B(rd_ptr[0]),
    .Y(_283_)
  );
  NOR _596_ (
    .A(_085_),
    .B(_283_),
    .Y(_284_)
  );
  NAND _597_ (
    .A(_282_),
    .B(_284_),
    .Y(_285_)
  );
  NOT _598_ (
    .A(_285_),
    .Y(_002_[0])
  );
  NOR _599_ (
    .A(_050_),
    .B(_282_),
    .Y(_286_)
  );
  NAND _600_ (
    .A(_050_),
    .B(_282_),
    .Y(_287_)
  );
  NAND _601_ (
    .A(_084_),
    .B(_287_),
    .Y(_288_)
  );
  NOR _602_ (
    .A(_286_),
    .B(_288_),
    .Y(_002_[1])
  );
  NAND _603_ (
    .A(wr_ptr[0]),
    .B(_114_),
    .Y(_289_)
  );
  NAND _604_ (
    .A(_091_),
    .B(_289_),
    .Y(_003_[0])
  );
  NOR _605_ (
    .A(wr_ptr[1]),
    .B(_112_),
    .Y(_290_)
  );
  NOR _606_ (
    .A(_118_),
    .B(_290_),
    .Y(_003_[1])
  );
  NOR _607_ (
    .A(_293_),
    .B(_058_),
    .Y(error_D1_synth)
  );
  DFF _608_ (
    .C(clk),
    .D(_002_[0]),
    .Q(rd_ptr[0])
  );
  DFF _609_ (
    .C(clk),
    .D(_002_[1]),
    .Q(rd_ptr[1])
  );
  DFF _610_ (
    .C(clk),
    .D(_022_),
    .Q(\mem[3] [0])
  );
  DFF _611_ (
    .C(clk),
    .D(_023_),
    .Q(\mem[3] [1])
  );
  DFF _612_ (
    .C(clk),
    .D(_024_),
    .Q(\mem[3] [2])
  );
  DFF _613_ (
    .C(clk),
    .D(_025_),
    .Q(\mem[3] [3])
  );
  DFF _614_ (
    .C(clk),
    .D(_026_),
    .Q(\mem[3] [4])
  );
  DFF _615_ (
    .C(clk),
    .D(_027_),
    .Q(\mem[3] [5])
  );
  DFF _616_ (
    .C(clk),
    .D(_016_),
    .Q(\mem[2] [0])
  );
  DFF _617_ (
    .C(clk),
    .D(_017_),
    .Q(\mem[2] [1])
  );
  DFF _618_ (
    .C(clk),
    .D(_018_),
    .Q(\mem[2] [2])
  );
  DFF _619_ (
    .C(clk),
    .D(_019_),
    .Q(\mem[2] [3])
  );
  DFF _620_ (
    .C(clk),
    .D(_020_),
    .Q(\mem[2] [4])
  );
  DFF _621_ (
    .C(clk),
    .D(_021_),
    .Q(\mem[2] [5])
  );
  DFF _622_ (
    .C(clk),
    .D(_010_),
    .Q(\mem[1] [0])
  );
  DFF _623_ (
    .C(clk),
    .D(_011_),
    .Q(\mem[1] [1])
  );
  DFF _624_ (
    .C(clk),
    .D(_012_),
    .Q(\mem[1] [2])
  );
  DFF _625_ (
    .C(clk),
    .D(_013_),
    .Q(\mem[1] [3])
  );
  DFF _626_ (
    .C(clk),
    .D(_014_),
    .Q(\mem[1] [4])
  );
  DFF _627_ (
    .C(clk),
    .D(_015_),
    .Q(\mem[1] [5])
  );
  DFF _628_ (
    .C(clk),
    .D(_004_),
    .Q(\mem[0] [0])
  );
  DFF _629_ (
    .C(clk),
    .D(_005_),
    .Q(\mem[0] [1])
  );
  DFF _630_ (
    .C(clk),
    .D(_006_),
    .Q(\mem[0] [2])
  );
  DFF _631_ (
    .C(clk),
    .D(_007_),
    .Q(\mem[0] [3])
  );
  DFF _632_ (
    .C(clk),
    .D(_008_),
    .Q(\mem[0] [4])
  );
  DFF _633_ (
    .C(clk),
    .D(_009_),
    .Q(\mem[0] [5])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:35" *)
  DFF _634_ (
    .C(clk),
    .D(_003_[0]),
    .Q(wr_ptr[0])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:35" *)
  DFF _635_ (
    .C(clk),
    .D(_003_[1]),
    .Q(wr_ptr[1])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:35" *)
  DFF _636_ (
    .C(clk),
    .D(_000_[0]),
    .Q(cnt[0])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:35" *)
  DFF _637_ (
    .C(clk),
    .D(_000_[1]),
    .Q(cnt[1])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:35" *)
  DFF _638_ (
    .C(clk),
    .D(_000_[2]),
    .Q(cnt[2])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:35" *)
  DFF _639_ (
    .C(clk),
    .D(_001_[0]),
    .Q(data_out_D1_synth[0])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:35" *)
  DFF _640_ (
    .C(clk),
    .D(_001_[1]),
    .Q(data_out_D1_synth[1])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:35" *)
  DFF _641_ (
    .C(clk),
    .D(_001_[2]),
    .Q(data_out_D1_synth[2])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:35" *)
  DFF _642_ (
    .C(clk),
    .D(_001_[3]),
    .Q(data_out_D1_synth[3])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:35" *)
  DFF _643_ (
    .C(clk),
    .D(_001_[4]),
    .Q(data_out_D1_synth[4])
  );
  (* src = "./final_logic_synth/D1_fifo_synth.v:35" *)
  DFF _644_ (
    .C(clk),
    .D(_001_[5]),
    .Q(data_out_D1_synth[5])
  );
  assign full_fifo_D1_reg = full_fifo_D1;
  assign i = 32'd4;
endmodule

(* cells_not_processed =  1  *)
(* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:6" *)
module arbitro_enrutamiento_synth(VC0, VC1, data_arbitro_VC0, data_arbitro_VC1, clk, reset_L, almost_full_fifo_D0, almost_full_fifo_D1, full_fifo_D0, full_fifo_D1, VC0_empty, VC1_empty, VC1_pop, VC0_pop, D0_push, D1_push, arbitro_D0_out, arbitro_D1_out);
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:9" *)
  output D0_push;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:9" *)
  output D1_push;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:6" *)
  input [5:0] VC0;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:8" *)
  input VC0_empty;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:15" *)
  wire VC0_empty_retrasado;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:9" *)
  output VC0_pop;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:6" *)
  input [5:0] VC1;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:8" *)
  input VC1_empty;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:15" *)
  wire VC1_empty_retrasado;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:9" *)
  output VC1_pop;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:7" *)
  input almost_full_fifo_D0;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:7" *)
  input almost_full_fifo_D1;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:10" *)
  output [5:0] arbitro_D0_out;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:10" *)
  output [5:0] arbitro_D1_out;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:7" *)
  input clk;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:6" *)
  input [5:0] data_arbitro_VC0;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:13" *)
  wire [5:0] data_arbitro_VC0_retrasado;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:6" *)
  input [5:0] data_arbitro_VC1;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:14" *)
  wire [5:0] data_arbitro_VC1_retrasado;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:7" *)
  input full_fifo_D0;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:7" *)
  input full_fifo_D1;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:12" *)
  wire pop_delay_VC0;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:12" *)
  wire pop_delay_VC1;
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:7" *)
  input reset_L;
  (* module_not_derived = 32'd1 *)
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:61" *)
  retraso1 retraso1a (
    .VC0_empty(VC0_empty),
    .VC0_empty_retrasado(VC0_empty_retrasado),
    .VC1_empty(VC1_empty),
    .VC1_empty_retrasado(VC1_empty_retrasado),
    .almost_full_fifo_D0(almost_full_fifo_D0),
    .almost_full_fifo_D1(almost_full_fifo_D1),
    .clk(clk),
    .data_arbitro_VC0(data_arbitro_VC0),
    .data_arbitro_VC0_retrasado(data_arbitro_VC0_retrasado),
    .data_arbitro_VC1(data_arbitro_VC1),
    .data_arbitro_VC1_retrasado(data_arbitro_VC1_retrasado),
    .full_fifo_D0(full_fifo_D0),
    .full_fifo_D1(full_fifo_D1),
    .reset_L(reset_L)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:17" *)
  arbitro_mux_synth u_arbitro_mux_synthes (
    .D0_push(D0_push),
    .D1_push(D1_push),
    .VC0(VC0),
    .VC0_empty(VC0_empty),
    .VC1(VC1),
    .VC1_empty(VC1_empty),
    .almost_full_fifo_D0(almost_full_fifo_D0),
    .almost_full_fifo_D1(almost_full_fifo_D1),
    .arbitro_D0_out(arbitro_D0_out),
    .arbitro_D1_out(arbitro_D1_out),
    .clk(clk),
    .full_fifo_D0(full_fifo_D0),
    .full_fifo_D1(full_fifo_D1),
    .pop_delay_VC0(pop_delay_VC0),
    .pop_delay_VC1(pop_delay_VC1),
    .reset_L(reset_L)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./arbitro_mux_synthes/arbitro_enrutamiento_synth.v:78" *)
  logica_pops_synth u_logica_pops_synth (
    .VC0_empty(VC0_empty_retrasado),
    .VC0_pop(VC0_pop),
    .VC1_empty(VC1_empty_retrasado),
    .VC1_pop(VC1_pop),
    .almost_full_fifo_D0(almost_full_fifo_D0),
    .almost_full_fifo_D1(almost_full_fifo_D1),
    .clk(clk),
    .data_arbitro_VC0(data_arbitro_VC0_retrasado),
    .data_arbitro_VC1(data_arbitro_VC1_retrasado),
    .full_fifo_D0(full_fifo_D0),
    .full_fifo_D1(full_fifo_D1),
    .pop_delay_VC0(pop_delay_VC0),
    .pop_delay_VC1(pop_delay_VC1),
    .reset_L(reset_L)
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:1" *)
module arbitro_mux_synth(reset_L, clk, VC0, VC1, pop_delay_VC0, pop_delay_VC1, almost_full_fifo_D0, almost_full_fifo_D1, full_fifo_D0, full_fifo_D1, VC0_empty, VC1_empty, arbitro_D0_out, arbitro_D1_out, D0_push, D1_push);
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:10" *)
  wire _000_;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:10" *)
  wire _001_;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:10" *)
  wire [5:0] _002_;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:10" *)
  wire [5:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:8" *)
  output D0_push;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:8" *)
  output D1_push;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:2" *)
  input [5:0] VC0;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:6" *)
  input VC0_empty;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:3" *)
  input [5:0] VC1;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:6" *)
  input VC1_empty;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:5" *)
  input almost_full_fifo_D0;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:5" *)
  input almost_full_fifo_D1;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:7" *)
  output [5:0] arbitro_D0_out;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:7" *)
  output [5:0] arbitro_D1_out;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:1" *)
  input clk;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:5" *)
  input full_fifo_D0;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:5" *)
  input full_fifo_D1;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:4" *)
  input pop_delay_VC0;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:4" *)
  input pop_delay_VC1;
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:1" *)
  input reset_L;
  NOT _113_ (
    .A(VC1[4]),
    .Y(_066_)
  );
  NOT _114_ (
    .A(VC1[5]),
    .Y(_067_)
  );
  NOT _115_ (
    .A(VC0[0]),
    .Y(_068_)
  );
  NOT _116_ (
    .A(VC0[4]),
    .Y(_069_)
  );
  NOT _117_ (
    .A(VC0[1]),
    .Y(_070_)
  );
  NOT _118_ (
    .A(VC0[2]),
    .Y(_071_)
  );
  NOT _119_ (
    .A(VC0[3]),
    .Y(_072_)
  );
  NOT _120_ (
    .A(VC0_empty),
    .Y(_073_)
  );
  NOT _121_ (
    .A(reset_L),
    .Y(_074_)
  );
  NAND _122_ (
    .A(almost_full_fifo_D1),
    .B(full_fifo_D0),
    .Y(_075_)
  );
  NAND _123_ (
    .A(full_fifo_D1),
    .B(almost_full_fifo_D0),
    .Y(_076_)
  );
  NOR _124_ (
    .A(_075_),
    .B(_076_),
    .Y(_077_)
  );
  NAND _125_ (
    .A(arbitro_D0_out[0]),
    .B(_077_),
    .Y(_078_)
  );
  NAND _126_ (
    .A(pop_delay_VC0),
    .B(_073_),
    .Y(_079_)
  );
  NAND _127_ (
    .A(pop_delay_VC1),
    .B(VC0_empty),
    .Y(_080_)
  );
  NOR _128_ (
    .A(VC1_empty),
    .B(_080_),
    .Y(_081_)
  );
  NOT _129_ (
    .A(_081_),
    .Y(_082_)
  );
  NAND _130_ (
    .A(_079_),
    .B(_082_),
    .Y(_083_)
  );
  NAND _131_ (
    .A(reset_L),
    .B(_083_),
    .Y(_084_)
  );
  NOT _132_ (
    .A(_084_),
    .Y(_085_)
  );
  NOR _133_ (
    .A(_078_),
    .B(_084_),
    .Y(_086_)
  );
  NOT _134_ (
    .A(_086_),
    .Y(_087_)
  );
  NOR _135_ (
    .A(VC0[4]),
    .B(_077_),
    .Y(_088_)
  );
  NOR _136_ (
    .A(_068_),
    .B(_079_),
    .Y(_089_)
  );
  NAND _137_ (
    .A(_088_),
    .B(_089_),
    .Y(_090_)
  );
  NAND _138_ (
    .A(_066_),
    .B(_081_),
    .Y(_091_)
  );
  NOR _139_ (
    .A(VC1[4]),
    .B(_077_),
    .Y(_092_)
  );
  NOR _140_ (
    .A(_077_),
    .B(_091_),
    .Y(_093_)
  );
  NAND _141_ (
    .A(_081_),
    .B(_092_),
    .Y(_094_)
  );
  NAND _142_ (
    .A(VC1[0]),
    .B(_093_),
    .Y(_095_)
  );
  NAND _143_ (
    .A(_090_),
    .B(_095_),
    .Y(_096_)
  );
  NAND _144_ (
    .A(reset_L),
    .B(_096_),
    .Y(_097_)
  );
  NAND _145_ (
    .A(_087_),
    .B(_097_),
    .Y(_002_[0])
  );
  NOR _146_ (
    .A(_074_),
    .B(_094_),
    .Y(_098_)
  );
  NAND _147_ (
    .A(VC1[1]),
    .B(_098_),
    .Y(_099_)
  );
  NAND _148_ (
    .A(arbitro_D0_out[1]),
    .B(_077_),
    .Y(_100_)
  );
  NOR _149_ (
    .A(_070_),
    .B(_079_),
    .Y(_101_)
  );
  NAND _150_ (
    .A(_088_),
    .B(_101_),
    .Y(_102_)
  );
  NAND _151_ (
    .A(_100_),
    .B(_102_),
    .Y(_103_)
  );
  NAND _152_ (
    .A(_085_),
    .B(_103_),
    .Y(_104_)
  );
  NAND _153_ (
    .A(_099_),
    .B(_104_),
    .Y(_002_[1])
  );
  NAND _154_ (
    .A(VC1[2]),
    .B(_098_),
    .Y(_105_)
  );
  NAND _155_ (
    .A(arbitro_D0_out[2]),
    .B(_077_),
    .Y(_106_)
  );
  NOR _156_ (
    .A(_071_),
    .B(_079_),
    .Y(_107_)
  );
  NAND _157_ (
    .A(_088_),
    .B(_107_),
    .Y(_108_)
  );
  NAND _158_ (
    .A(_106_),
    .B(_108_),
    .Y(_109_)
  );
  NAND _159_ (
    .A(_085_),
    .B(_109_),
    .Y(_110_)
  );
  NAND _160_ (
    .A(_105_),
    .B(_110_),
    .Y(_002_[2])
  );
  NAND _161_ (
    .A(VC1[3]),
    .B(_098_),
    .Y(_111_)
  );
  NAND _162_ (
    .A(arbitro_D0_out[3]),
    .B(_077_),
    .Y(_112_)
  );
  NOR _163_ (
    .A(_072_),
    .B(_079_),
    .Y(_004_)
  );
  NAND _164_ (
    .A(_088_),
    .B(_004_),
    .Y(_005_)
  );
  NAND _165_ (
    .A(_112_),
    .B(_005_),
    .Y(_006_)
  );
  NAND _166_ (
    .A(_085_),
    .B(_006_),
    .Y(_007_)
  );
  NAND _167_ (
    .A(_111_),
    .B(_007_),
    .Y(_002_[3])
  );
  NAND _168_ (
    .A(arbitro_D0_out[4]),
    .B(_077_),
    .Y(_008_)
  );
  NOR _169_ (
    .A(_084_),
    .B(_008_),
    .Y(_002_[4])
  );
  NAND _170_ (
    .A(arbitro_D0_out[5]),
    .B(_077_),
    .Y(_009_)
  );
  NOR _171_ (
    .A(_069_),
    .B(VC0_empty),
    .Y(_010_)
  );
  NAND _172_ (
    .A(VC0[4]),
    .B(_073_),
    .Y(_011_)
  );
  NAND _173_ (
    .A(VC1[4]),
    .B(VC0_empty),
    .Y(_012_)
  );
  NOT _174_ (
    .A(_012_),
    .Y(_013_)
  );
  NOR _175_ (
    .A(_010_),
    .B(_013_),
    .Y(_014_)
  );
  NAND _176_ (
    .A(_011_),
    .B(_012_),
    .Y(_015_)
  );
  NOR _177_ (
    .A(_077_),
    .B(_015_),
    .Y(_016_)
  );
  NOR _178_ (
    .A(VC0[5]),
    .B(VC0_empty),
    .Y(_017_)
  );
  NOR _179_ (
    .A(VC1[5]),
    .B(_073_),
    .Y(_018_)
  );
  NAND _180_ (
    .A(_067_),
    .B(VC0_empty),
    .Y(_019_)
  );
  NOR _181_ (
    .A(_017_),
    .B(_018_),
    .Y(_020_)
  );
  NAND _182_ (
    .A(_016_),
    .B(_020_),
    .Y(_021_)
  );
  NAND _183_ (
    .A(_009_),
    .B(_021_),
    .Y(_022_)
  );
  NOT _184_ (
    .A(_022_),
    .Y(_023_)
  );
  NOR _185_ (
    .A(_084_),
    .B(_023_),
    .Y(_002_[5])
  );
  NAND _186_ (
    .A(D1_push),
    .B(_077_),
    .Y(_024_)
  );
  NOT _187_ (
    .A(_024_),
    .Y(_025_)
  );
  NOR _188_ (
    .A(_077_),
    .B(_012_),
    .Y(_026_)
  );
  NOR _189_ (
    .A(_077_),
    .B(_011_),
    .Y(_027_)
  );
  NOR _190_ (
    .A(_077_),
    .B(_014_),
    .Y(_028_)
  );
  NOR _191_ (
    .A(_025_),
    .B(_028_),
    .Y(_029_)
  );
  NOR _192_ (
    .A(_084_),
    .B(_029_),
    .Y(_001_)
  );
  NAND _193_ (
    .A(D0_push),
    .B(_077_),
    .Y(_030_)
  );
  NOT _194_ (
    .A(_030_),
    .Y(_031_)
  );
  NOR _195_ (
    .A(_016_),
    .B(_031_),
    .Y(_032_)
  );
  NOR _196_ (
    .A(_084_),
    .B(_032_),
    .Y(_000_)
  );
  NAND _197_ (
    .A(VC1[0]),
    .B(_026_),
    .Y(_033_)
  );
  NOT _198_ (
    .A(_033_),
    .Y(_034_)
  );
  NAND _199_ (
    .A(VC0[0]),
    .B(_027_),
    .Y(_035_)
  );
  NAND _200_ (
    .A(arbitro_D1_out[0]),
    .B(_077_),
    .Y(_036_)
  );
  NAND _201_ (
    .A(_035_),
    .B(_036_),
    .Y(_037_)
  );
  NOR _202_ (
    .A(_034_),
    .B(_037_),
    .Y(_038_)
  );
  NOR _203_ (
    .A(_084_),
    .B(_038_),
    .Y(_003_[0])
  );
  NAND _204_ (
    .A(VC1[1]),
    .B(_026_),
    .Y(_039_)
  );
  NOT _205_ (
    .A(_039_),
    .Y(_040_)
  );
  NAND _206_ (
    .A(VC0[1]),
    .B(_027_),
    .Y(_041_)
  );
  NAND _207_ (
    .A(arbitro_D1_out[1]),
    .B(_077_),
    .Y(_042_)
  );
  NAND _208_ (
    .A(_041_),
    .B(_042_),
    .Y(_043_)
  );
  NOR _209_ (
    .A(_040_),
    .B(_043_),
    .Y(_044_)
  );
  NOR _210_ (
    .A(_084_),
    .B(_044_),
    .Y(_003_[1])
  );
  NAND _211_ (
    .A(VC0[2]),
    .B(_027_),
    .Y(_045_)
  );
  NOT _212_ (
    .A(_045_),
    .Y(_046_)
  );
  NAND _213_ (
    .A(VC1[2]),
    .B(_026_),
    .Y(_047_)
  );
  NAND _214_ (
    .A(arbitro_D1_out[2]),
    .B(_077_),
    .Y(_048_)
  );
  NAND _215_ (
    .A(_047_),
    .B(_048_),
    .Y(_049_)
  );
  NOR _216_ (
    .A(_046_),
    .B(_049_),
    .Y(_050_)
  );
  NOR _217_ (
    .A(_084_),
    .B(_050_),
    .Y(_003_[2])
  );
  NAND _218_ (
    .A(VC1[3]),
    .B(_026_),
    .Y(_051_)
  );
  NOT _219_ (
    .A(_051_),
    .Y(_052_)
  );
  NAND _220_ (
    .A(VC0[3]),
    .B(_027_),
    .Y(_053_)
  );
  NAND _221_ (
    .A(arbitro_D1_out[3]),
    .B(_077_),
    .Y(_054_)
  );
  NAND _222_ (
    .A(_053_),
    .B(_054_),
    .Y(_055_)
  );
  NOR _223_ (
    .A(_052_),
    .B(_055_),
    .Y(_056_)
  );
  NOR _224_ (
    .A(_084_),
    .B(_056_),
    .Y(_003_[3])
  );
  NAND _225_ (
    .A(arbitro_D1_out[4]),
    .B(_077_),
    .Y(_057_)
  );
  NOT _226_ (
    .A(_057_),
    .Y(_058_)
  );
  NOR _227_ (
    .A(_028_),
    .B(_058_),
    .Y(_059_)
  );
  NOR _228_ (
    .A(_084_),
    .B(_059_),
    .Y(_003_[4])
  );
  NAND _229_ (
    .A(arbitro_D1_out[5]),
    .B(_077_),
    .Y(_060_)
  );
  NOT _230_ (
    .A(_060_),
    .Y(_061_)
  );
  NOR _231_ (
    .A(VC0[5]),
    .B(_026_),
    .Y(_062_)
  );
  NAND _232_ (
    .A(_019_),
    .B(_028_),
    .Y(_063_)
  );
  NOR _233_ (
    .A(_062_),
    .B(_063_),
    .Y(_064_)
  );
  NOR _234_ (
    .A(_061_),
    .B(_064_),
    .Y(_065_)
  );
  NOR _235_ (
    .A(_084_),
    .B(_065_),
    .Y(_003_[5])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:10" *)
  DFF _236_ (
    .C(clk),
    .D(_002_[0]),
    .Q(arbitro_D0_out[0])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:10" *)
  DFF _237_ (
    .C(clk),
    .D(_002_[1]),
    .Q(arbitro_D0_out[1])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:10" *)
  DFF _238_ (
    .C(clk),
    .D(_002_[2]),
    .Q(arbitro_D0_out[2])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:10" *)
  DFF _239_ (
    .C(clk),
    .D(_002_[3]),
    .Q(arbitro_D0_out[3])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:10" *)
  DFF _240_ (
    .C(clk),
    .D(_002_[4]),
    .Q(arbitro_D0_out[4])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:10" *)
  DFF _241_ (
    .C(clk),
    .D(_002_[5]),
    .Q(arbitro_D0_out[5])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:10" *)
  DFF _242_ (
    .C(clk),
    .D(_003_[0]),
    .Q(arbitro_D1_out[0])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:10" *)
  DFF _243_ (
    .C(clk),
    .D(_003_[1]),
    .Q(arbitro_D1_out[1])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:10" *)
  DFF _244_ (
    .C(clk),
    .D(_003_[2]),
    .Q(arbitro_D1_out[2])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:10" *)
  DFF _245_ (
    .C(clk),
    .D(_003_[3]),
    .Q(arbitro_D1_out[3])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:10" *)
  DFF _246_ (
    .C(clk),
    .D(_003_[4]),
    .Q(arbitro_D1_out[4])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:10" *)
  DFF _247_ (
    .C(clk),
    .D(_003_[5]),
    .Q(arbitro_D1_out[5])
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:10" *)
  DFF _248_ (
    .C(clk),
    .D(_000_),
    .Q(D0_push)
  );
  (* src = "./arbitro_mux_synthes/arbitro_mux_synth.v:10" *)
  DFF _249_ (
    .C(clk),
    .D(_001_),
    .Q(D1_push)
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "./final_logic_synth/final_logic_synth.v:6" *)
module final_logic_synth(data_out_VC0, data_out_VC1, data_arbitro_VC0, data_arbitro_VC1, clk, reset_L, empty_fifo_VC0, empty_fifo_VC1, init, D0_pop, D1_pop, Umbral_D0, Umbral_D1, data_out_D0_synth, data_out_D1_synth, pop_VC0_fifo_synth, pop_VC1_fifo_synth, error_D1_synth, error_D0_synth, empty_fifo_D1, empty_fifo_D0);
  (* src = "./final_logic_synth/final_logic_synth.v:12" *)
  input D0_pop;
  (* src = "./final_logic_synth/final_logic_synth.v:19" *)
  wire D0_push;
  (* src = "./final_logic_synth/final_logic_synth.v:12" *)
  input D1_pop;
  (* src = "./final_logic_synth/final_logic_synth.v:19" *)
  wire D1_push;
  (* src = "./final_logic_synth/final_logic_synth.v:13" *)
  input [3:0] Umbral_D0;
  (* src = "./final_logic_synth/final_logic_synth.v:14" *)
  input [3:0] Umbral_D1;
  (* src = "./final_logic_synth/final_logic_synth.v:67" *)
  (* unused_bits = "0" *)
  wire almost_empty_fifo_D0;
  (* src = "./final_logic_synth/final_logic_synth.v:83" *)
  (* unused_bits = "0" *)
  wire almost_empty_fifo_D1;
  (* src = "./final_logic_synth/final_logic_synth.v:33" *)
  wire almost_full_fifo_D0;
  (* src = "./final_logic_synth/final_logic_synth.v:35" *)
  wire almost_full_fifo_D1;
  (* src = "./final_logic_synth/final_logic_synth.v:21" *)
  wire [5:0] arbitro_D0_out;
  (* src = "./final_logic_synth/final_logic_synth.v:21" *)
  wire [5:0] arbitro_D1_out;
  (* src = "./final_logic_synth/final_logic_synth.v:11" *)
  input clk;
  (* src = "./final_logic_synth/final_logic_synth.v:10" *)
  input [5:0] data_arbitro_VC0;
  (* src = "./final_logic_synth/final_logic_synth.v:10" *)
  input [5:0] data_arbitro_VC1;
  (* src = "./final_logic_synth/final_logic_synth.v:15" *)
  output [5:0] data_out_D0_synth;
  (* src = "./final_logic_synth/final_logic_synth.v:15" *)
  output [5:0] data_out_D1_synth;
  (* src = "./final_logic_synth/final_logic_synth.v:10" *)
  input [5:0] data_out_VC0;
  (* src = "./final_logic_synth/final_logic_synth.v:10" *)
  input [5:0] data_out_VC1;
  (* src = "./final_logic_synth/final_logic_synth.v:17" *)
  output empty_fifo_D0;
  (* src = "./final_logic_synth/final_logic_synth.v:17" *)
  output empty_fifo_D1;
  (* src = "./final_logic_synth/final_logic_synth.v:11" *)
  input empty_fifo_VC0;
  (* src = "./final_logic_synth/final_logic_synth.v:11" *)
  input empty_fifo_VC1;
  (* src = "./final_logic_synth/final_logic_synth.v:17" *)
  output error_D0_synth;
  (* src = "./final_logic_synth/final_logic_synth.v:17" *)
  output error_D1_synth;
  (* src = "./final_logic_synth/final_logic_synth.v:32" *)
  wire full_fifo_D0;
  (* src = "./final_logic_synth/final_logic_synth.v:34" *)
  wire full_fifo_D1;
  (* src = "./final_logic_synth/final_logic_synth.v:11" *)
  input init;
  (* src = "./final_logic_synth/final_logic_synth.v:16" *)
  output pop_VC0_fifo_synth;
  (* src = "./final_logic_synth/final_logic_synth.v:16" *)
  output pop_VC1_fifo_synth;
  (* src = "./final_logic_synth/final_logic_synth.v:11" *)
  input reset_L;
  (* module_not_derived = 32'd1 *)
  (* src = "./final_logic_synth/final_logic_synth.v:57" *)
  D0_fifo_synth u_D0_fifo_synth (
    .Umbral_D0(Umbral_D0),
    .almost_empty_fifo_D0(almost_empty_fifo_D0),
    .almost_full_fifo_D0(almost_full_fifo_D0),
    .clk(clk),
    .data_in(arbitro_D0_out),
    .data_out_D0_synth(data_out_D0_synth),
    .empty_fifo_D0(empty_fifo_D0),
    .error_D0_synth(error_D0_synth),
    .full_fifo_D0(full_fifo_D0),
    .init(init),
    .rd_enable(D0_pop),
    .reset_L(reset_L),
    .wr_enable(D0_push)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./final_logic_synth/final_logic_synth.v:73" *)
  D1_fifo_synth u_D1_fifo_synth (
    .Umbral_D1(Umbral_D1),
    .almost_empty_fifo_D1(almost_empty_fifo_D1),
    .almost_full_fifo_D1(almost_full_fifo_D1),
    .clk(clk),
    .data_in(arbitro_D1_out),
    .data_out_D1_synth(data_out_D1_synth),
    .empty_fifo_D1(empty_fifo_D1),
    .error_D1_synth(error_D1_synth),
    .full_fifo_D1(full_fifo_D1),
    .init(init),
    .rd_enable(D1_pop),
    .reset_L(reset_L),
    .wr_enable(D1_push)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "./final_logic_synth/final_logic_synth.v:25" *)
  arbitro_enrutamiento_synth u_arbitro_enrutamiento_synth (
    .D0_push(D0_push),
    .D1_push(D1_push),
    .VC0(data_out_VC0),
    .VC0_empty(empty_fifo_VC0),
    .VC0_pop(pop_VC0_fifo_synth),
    .VC1(data_out_VC1),
    .VC1_empty(empty_fifo_VC1),
    .VC1_pop(pop_VC1_fifo_synth),
    .almost_full_fifo_D0(almost_full_fifo_D0),
    .almost_full_fifo_D1(almost_full_fifo_D1),
    .arbitro_D0_out(arbitro_D0_out),
    .arbitro_D1_out(arbitro_D1_out),
    .clk(clk),
    .data_arbitro_VC0(data_arbitro_VC0),
    .data_arbitro_VC1(data_arbitro_VC1),
    .full_fifo_D0(full_fifo_D0),
    .full_fifo_D1(full_fifo_D1),
    .reset_L(reset_L)
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
module logica_pops_synth(VC0_empty, VC1_empty, full_fifo_D0, full_fifo_D1, almost_full_fifo_D0, almost_full_fifo_D1, clk, reset_L, data_arbitro_VC0, data_arbitro_VC1, VC0_pop, VC1_pop, pop_delay_VC0, pop_delay_VC1);
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:6" *)
  wire _00_;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:6" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
  input VC0_empty;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:3" *)
  output VC0_pop;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
  input VC1_empty;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:3" *)
  output VC1_pop;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
  input almost_full_fifo_D0;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
  input almost_full_fifo_D1;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
  input clk;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:2" *)
  input [5:0] data_arbitro_VC0;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:2" *)
  input [5:0] data_arbitro_VC1;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
  input full_fifo_D0;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
  input full_fifo_D1;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:3" *)
  output pop_delay_VC0;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:3" *)
  output pop_delay_VC1;
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:1" *)
  input reset_L;
  NOT _08_ (
    .A(reset_L),
    .Y(_02_)
  );
  NOT _09_ (
    .A(VC1_empty),
    .Y(_03_)
  );
  NOR _10_ (
    .A(almost_full_fifo_D0),
    .B(full_fifo_D0),
    .Y(_04_)
  );
  NOR _11_ (
    .A(_02_),
    .B(full_fifo_D1),
    .Y(_05_)
  );
  NAND _12_ (
    .A(_04_),
    .B(_05_),
    .Y(_06_)
  );
  NAND _13_ (
    .A(VC0_empty),
    .B(_03_),
    .Y(_07_)
  );
  NOR _14_ (
    .A(_06_),
    .B(_07_),
    .Y(VC1_pop)
  );
  NOR _15_ (
    .A(VC0_empty),
    .B(_06_),
    .Y(VC0_pop)
  );
  NOR _16_ (
    .A(_06_),
    .B(_07_),
    .Y(_01_)
  );
  NOR _17_ (
    .A(VC0_empty),
    .B(_06_),
    .Y(_00_)
  );
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:6" *)
  DFF _18_ (
    .C(clk),
    .D(_00_),
    .Q(pop_delay_VC0)
  );
  (* src = "./arbitro_mux_synthes/logica_pops_synth.v:6" *)
  DFF _19_ (
    .C(clk),
    .D(_01_),
    .Q(pop_delay_VC1)
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "./arbitro_mux_synthes/retraso1.v:1" *)
module retraso1(VC0_empty, VC1_empty, full_fifo_D0, full_fifo_D1, almost_full_fifo_D0, almost_full_fifo_D1, clk, reset_L, data_arbitro_VC0, data_arbitro_VC1, VC0_empty_retrasado, VC1_empty_retrasado, full_fifo_D0_retrasado, full_fifo_D1_retrasado, almost_full_fifo_D0_retrasado, almost_full_fifo_D1_retrasado, data_arbitro_VC0_retrasado, data_arbitro_VC1_retrasado);
  (* src = "./arbitro_mux_synthes/retraso1.v:1" *)
  input VC0_empty;
  (* src = "./arbitro_mux_synthes/retraso1.v:3" *)
  output VC0_empty_retrasado;
  (* src = "./arbitro_mux_synthes/retraso1.v:1" *)
  input VC1_empty;
  (* src = "./arbitro_mux_synthes/retraso1.v:3" *)
  output VC1_empty_retrasado;
  (* src = "./arbitro_mux_synthes/retraso1.v:1" *)
  input almost_full_fifo_D0;
  (* src = "./arbitro_mux_synthes/retraso1.v:3" *)
  output almost_full_fifo_D0_retrasado;
  (* src = "./arbitro_mux_synthes/retraso1.v:1" *)
  input almost_full_fifo_D1;
  (* src = "./arbitro_mux_synthes/retraso1.v:3" *)
  output almost_full_fifo_D1_retrasado;
  (* src = "./arbitro_mux_synthes/retraso1.v:1" *)
  input clk;
  (* src = "./arbitro_mux_synthes/retraso1.v:2" *)
  input [5:0] data_arbitro_VC0;
  (* src = "./arbitro_mux_synthes/retraso1.v:4" *)
  output [5:0] data_arbitro_VC0_retrasado;
  (* src = "./arbitro_mux_synthes/retraso1.v:2" *)
  input [5:0] data_arbitro_VC1;
  (* src = "./arbitro_mux_synthes/retraso1.v:4" *)
  output [5:0] data_arbitro_VC1_retrasado;
  (* src = "./arbitro_mux_synthes/retraso1.v:1" *)
  input full_fifo_D0;
  (* src = "./arbitro_mux_synthes/retraso1.v:3" *)
  output full_fifo_D0_retrasado;
  (* src = "./arbitro_mux_synthes/retraso1.v:1" *)
  input full_fifo_D1;
  (* src = "./arbitro_mux_synthes/retraso1.v:3" *)
  output full_fifo_D1_retrasado;
  (* src = "./arbitro_mux_synthes/retraso1.v:1" *)
  input reset_L;
  (* src = "./arbitro_mux_synthes/retraso1.v:8" *)
  DFF _00_ (
    .C(clk),
    .D(data_arbitro_VC1[0]),
    .Q(data_arbitro_VC1_retrasado[0])
  );
  (* src = "./arbitro_mux_synthes/retraso1.v:8" *)
  DFF _01_ (
    .C(clk),
    .D(data_arbitro_VC1[1]),
    .Q(data_arbitro_VC1_retrasado[1])
  );
  (* src = "./arbitro_mux_synthes/retraso1.v:8" *)
  DFF _02_ (
    .C(clk),
    .D(data_arbitro_VC1[2]),
    .Q(data_arbitro_VC1_retrasado[2])
  );
  (* src = "./arbitro_mux_synthes/retraso1.v:8" *)
  DFF _03_ (
    .C(clk),
    .D(data_arbitro_VC1[3]),
    .Q(data_arbitro_VC1_retrasado[3])
  );
  (* src = "./arbitro_mux_synthes/retraso1.v:8" *)
  DFF _04_ (
    .C(clk),
    .D(data_arbitro_VC1[4]),
    .Q(data_arbitro_VC1_retrasado[4])
  );
  (* src = "./arbitro_mux_synthes/retraso1.v:8" *)
  DFF _05_ (
    .C(clk),
    .D(data_arbitro_VC1[5]),
    .Q(data_arbitro_VC1_retrasado[5])
  );
  (* src = "./arbitro_mux_synthes/retraso1.v:8" *)
  DFF _06_ (
    .C(clk),
    .D(data_arbitro_VC0[0]),
    .Q(data_arbitro_VC0_retrasado[0])
  );
  (* src = "./arbitro_mux_synthes/retraso1.v:8" *)
  DFF _07_ (
    .C(clk),
    .D(data_arbitro_VC0[1]),
    .Q(data_arbitro_VC0_retrasado[1])
  );
  (* src = "./arbitro_mux_synthes/retraso1.v:8" *)
  DFF _08_ (
    .C(clk),
    .D(data_arbitro_VC0[2]),
    .Q(data_arbitro_VC0_retrasado[2])
  );
  (* src = "./arbitro_mux_synthes/retraso1.v:8" *)
  DFF _09_ (
    .C(clk),
    .D(data_arbitro_VC0[3]),
    .Q(data_arbitro_VC0_retrasado[3])
  );
  (* src = "./arbitro_mux_synthes/retraso1.v:8" *)
  DFF _10_ (
    .C(clk),
    .D(data_arbitro_VC0[4]),
    .Q(data_arbitro_VC0_retrasado[4])
  );
  (* src = "./arbitro_mux_synthes/retraso1.v:8" *)
  DFF _11_ (
    .C(clk),
    .D(data_arbitro_VC0[5]),
    .Q(data_arbitro_VC0_retrasado[5])
  );
  (* src = "./arbitro_mux_synthes/retraso1.v:8" *)
  DFF _12_ (
    .C(clk),
    .D(VC0_empty),
    .Q(VC0_empty_retrasado)
  );
  (* src = "./arbitro_mux_synthes/retraso1.v:8" *)
  DFF _13_ (
    .C(clk),
    .D(VC1_empty),
    .Q(VC1_empty_retrasado)
  );
endmodule
