/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* cells_not_processed =  1  *)
(* src = "arbitro_enrutamiento_synth.v:6" *)
module arbitro_enrutamiento_synth(VC0, VC1, clk, reset_L, VC0_empty, VC1_empty, D1_pause, D0_pause, VC1_pop_synth, VC0_pop_synth, D0_out_synth, D1_out_synth);
  (* src = "arbitro_enrutamiento_synth.v:10" *)
  output [5:0] D0_out_synth;
  (* src = "arbitro_enrutamiento_synth.v:8" *)
  input D0_pause;
  (* src = "arbitro_enrutamiento_synth.v:10" *)
  output [5:0] D1_out_synth;
  (* src = "arbitro_enrutamiento_synth.v:8" *)
  input D1_pause;
  (* src = "arbitro_enrutamiento_synth.v:6" *)
  input [5:0] VC0;
  (* src = "arbitro_enrutamiento_synth.v:8" *)
  input VC0_empty;
  (* src = "arbitro_enrutamiento_synth.v:9" *)
  output VC0_pop_synth;
  (* src = "arbitro_enrutamiento_synth.v:6" *)
  input [5:0] VC1;
  (* src = "arbitro_enrutamiento_synth.v:8" *)
  input VC1_empty;
  (* src = "arbitro_enrutamiento_synth.v:9" *)
  output VC1_pop_synth;
  (* src = "arbitro_enrutamiento_synth.v:7" *)
  input clk;
  (* src = "arbitro_enrutamiento_synth.v:12" *)
  wire pop_delay_VC0;
  (* src = "arbitro_enrutamiento_synth.v:12" *)
  wire pop_delay_VC1;
  (* src = "arbitro_enrutamiento_synth.v:7" *)
  input reset_L;
  (* module_not_derived = 32'd1 *)
  (* src = "arbitro_enrutamiento_synth.v:14" *)
  arbitro_mux_synth u_arbitro_mux_synthes (
    .D0_out_synth(D0_out_synth),
    .D1_out_synth(D1_out_synth),
    .VC0(VC0),
    .VC0_empty(VC0_empty),
    .VC1(VC1),
    .clk(clk),
    .pop_delay_VC0(pop_delay_VC0),
    .pop_delay_VC1(pop_delay_VC1),
    .reset_L(reset_L)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "arbitro_enrutamiento_synth.v:37" *)
  logica_pops_synth u_logica_pops_synth (
    .D0_pause(D0_pause),
    .D1_pause(D1_pause),
    .VC0_empty(VC0_empty),
    .VC0_pop_synth(VC0_pop_synth),
    .VC1_empty(VC1_empty),
    .VC1_pop_synth(VC1_pop_synth),
    .clk(clk),
    .pop_delay_VC0(pop_delay_VC0),
    .pop_delay_VC1(pop_delay_VC1)
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "arbitro_mux_synth.v:1" *)
module arbitro_mux_synth(reset_L, clk, VC0, VC1, pop_delay_VC0, pop_delay_VC1, VC0_empty, D0_out_synth, D1_out_synth);
  (* src = "arbitro_mux_synth.v:8" *)
  wire [5:0] _000_;
  (* src = "arbitro_mux_synth.v:8" *)
  wire [5:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  (* src = "arbitro_mux_synth.v:6" *)
  output [5:0] D0_out_synth;
  (* src = "arbitro_mux_synth.v:6" *)
  output [5:0] D1_out_synth;
  (* src = "arbitro_mux_synth.v:2" *)
  input [5:0] VC0;
  (* src = "arbitro_mux_synth.v:5" *)
  input VC0_empty;
  (* src = "arbitro_mux_synth.v:3" *)
  input [5:0] VC1;
  (* src = "arbitro_mux_synth.v:1" *)
  input clk;
  (* src = "arbitro_mux_synth.v:4" *)
  input pop_delay_VC0;
  (* src = "arbitro_mux_synth.v:4" *)
  input pop_delay_VC1;
  (* src = "arbitro_mux_synth.v:1" *)
  input reset_L;
  NOT _134_ (
    .A(VC1[1]),
    .Y(_078_)
  );
  NOT _135_ (
    .A(VC1[4]),
    .Y(_079_)
  );
  NOT _136_ (
    .A(VC1[2]),
    .Y(_080_)
  );
  NOT _137_ (
    .A(VC1[3]),
    .Y(_081_)
  );
  NOT _138_ (
    .A(VC1[5]),
    .Y(_082_)
  );
  NOT _139_ (
    .A(pop_delay_VC1),
    .Y(_083_)
  );
  NOT _140_ (
    .A(VC0_empty),
    .Y(_084_)
  );
  NOT _141_ (
    .A(VC0[0]),
    .Y(_085_)
  );
  NOT _142_ (
    .A(VC0[4]),
    .Y(_086_)
  );
  NOT _143_ (
    .A(VC0[1]),
    .Y(_087_)
  );
  NOT _144_ (
    .A(VC0[2]),
    .Y(_088_)
  );
  NOT _145_ (
    .A(VC0[3]),
    .Y(_089_)
  );
  NOT _146_ (
    .A(VC0[5]),
    .Y(_090_)
  );
  NOT _147_ (
    .A(pop_delay_VC0),
    .Y(_091_)
  );
  NOT _148_ (
    .A(reset_L),
    .Y(_092_)
  );
  NOT _149_ (
    .A(D0_out_synth[0]),
    .Y(_093_)
  );
  NOT _150_ (
    .A(D0_out_synth[1]),
    .Y(_094_)
  );
  NOT _151_ (
    .A(D0_out_synth[2]),
    .Y(_095_)
  );
  NOT _152_ (
    .A(D0_out_synth[3]),
    .Y(_096_)
  );
  NOT _153_ (
    .A(D0_out_synth[5]),
    .Y(_097_)
  );
  NOT _154_ (
    .A(VC1[0]),
    .Y(_098_)
  );
  NOR _155_ (
    .A(_079_),
    .B(_083_),
    .Y(_099_)
  );
  NAND _156_ (
    .A(VC1[4]),
    .B(pop_delay_VC1),
    .Y(_100_)
  );
  NOR _157_ (
    .A(VC1[0]),
    .B(_100_),
    .Y(_101_)
  );
  NOT _158_ (
    .A(_101_),
    .Y(_102_)
  );
  NAND _159_ (
    .A(VC0_empty),
    .B(_099_),
    .Y(_103_)
  );
  NAND _160_ (
    .A(VC0_empty),
    .B(_102_),
    .Y(_104_)
  );
  NOR _161_ (
    .A(D1_out_synth[0]),
    .B(_099_),
    .Y(_105_)
  );
  NOR _162_ (
    .A(_104_),
    .B(_105_),
    .Y(_106_)
  );
  NAND _163_ (
    .A(VC0[4]),
    .B(pop_delay_VC0),
    .Y(_107_)
  );
  NAND _164_ (
    .A(D1_out_synth[0]),
    .B(_107_),
    .Y(_108_)
  );
  NOT _165_ (
    .A(_108_),
    .Y(_109_)
  );
  NOR _166_ (
    .A(_085_),
    .B(_107_),
    .Y(_110_)
  );
  NOR _167_ (
    .A(_109_),
    .B(_110_),
    .Y(_111_)
  );
  NOR _168_ (
    .A(VC0_empty),
    .B(_111_),
    .Y(_112_)
  );
  NOR _169_ (
    .A(_106_),
    .B(_112_),
    .Y(_113_)
  );
  NOR _170_ (
    .A(_092_),
    .B(_113_),
    .Y(_001_[0])
  );
  NAND _171_ (
    .A(_078_),
    .B(_099_),
    .Y(_114_)
  );
  NAND _172_ (
    .A(VC0_empty),
    .B(_114_),
    .Y(_115_)
  );
  NOR _173_ (
    .A(D1_out_synth[1]),
    .B(_099_),
    .Y(_116_)
  );
  NOR _174_ (
    .A(_115_),
    .B(_116_),
    .Y(_117_)
  );
  NAND _175_ (
    .A(D1_out_synth[1]),
    .B(_107_),
    .Y(_118_)
  );
  NOT _176_ (
    .A(_118_),
    .Y(_119_)
  );
  NOR _177_ (
    .A(_087_),
    .B(_107_),
    .Y(_120_)
  );
  NOR _178_ (
    .A(_119_),
    .B(_120_),
    .Y(_121_)
  );
  NOR _179_ (
    .A(VC0_empty),
    .B(_121_),
    .Y(_122_)
  );
  NOR _180_ (
    .A(_117_),
    .B(_122_),
    .Y(_123_)
  );
  NOR _181_ (
    .A(_092_),
    .B(_123_),
    .Y(_001_[1])
  );
  NAND _182_ (
    .A(_080_),
    .B(_099_),
    .Y(_124_)
  );
  NAND _183_ (
    .A(VC0_empty),
    .B(_124_),
    .Y(_125_)
  );
  NOR _184_ (
    .A(D1_out_synth[2]),
    .B(_099_),
    .Y(_126_)
  );
  NOR _185_ (
    .A(_125_),
    .B(_126_),
    .Y(_127_)
  );
  NAND _186_ (
    .A(D1_out_synth[2]),
    .B(_107_),
    .Y(_128_)
  );
  NOT _187_ (
    .A(_128_),
    .Y(_129_)
  );
  NOR _188_ (
    .A(_088_),
    .B(_107_),
    .Y(_130_)
  );
  NOR _189_ (
    .A(_129_),
    .B(_130_),
    .Y(_131_)
  );
  NOR _190_ (
    .A(VC0_empty),
    .B(_131_),
    .Y(_132_)
  );
  NOR _191_ (
    .A(_127_),
    .B(_132_),
    .Y(_133_)
  );
  NOR _192_ (
    .A(_092_),
    .B(_133_),
    .Y(_001_[2])
  );
  NAND _193_ (
    .A(_081_),
    .B(_099_),
    .Y(_002_)
  );
  NAND _194_ (
    .A(VC0_empty),
    .B(_002_),
    .Y(_003_)
  );
  NOR _195_ (
    .A(D1_out_synth[3]),
    .B(_099_),
    .Y(_004_)
  );
  NOR _196_ (
    .A(_003_),
    .B(_004_),
    .Y(_005_)
  );
  NAND _197_ (
    .A(D1_out_synth[3]),
    .B(_107_),
    .Y(_006_)
  );
  NOT _198_ (
    .A(_006_),
    .Y(_007_)
  );
  NOR _199_ (
    .A(_089_),
    .B(_107_),
    .Y(_008_)
  );
  NOR _200_ (
    .A(_007_),
    .B(_008_),
    .Y(_009_)
  );
  NOR _201_ (
    .A(VC0_empty),
    .B(_009_),
    .Y(_010_)
  );
  NOR _202_ (
    .A(_005_),
    .B(_010_),
    .Y(_011_)
  );
  NOR _203_ (
    .A(_092_),
    .B(_011_),
    .Y(_001_[3])
  );
  NOR _204_ (
    .A(VC0_empty),
    .B(_107_),
    .Y(_012_)
  );
  NOR _205_ (
    .A(D1_out_synth[4]),
    .B(_012_),
    .Y(_013_)
  );
  NAND _206_ (
    .A(_103_),
    .B(_013_),
    .Y(_014_)
  );
  NAND _207_ (
    .A(reset_L),
    .B(_014_),
    .Y(_015_)
  );
  NOT _208_ (
    .A(_015_),
    .Y(_001_[4])
  );
  NAND _209_ (
    .A(_082_),
    .B(_099_),
    .Y(_016_)
  );
  NAND _210_ (
    .A(VC0_empty),
    .B(_016_),
    .Y(_017_)
  );
  NOR _211_ (
    .A(D1_out_synth[5]),
    .B(_099_),
    .Y(_018_)
  );
  NOR _212_ (
    .A(_017_),
    .B(_018_),
    .Y(_019_)
  );
  NAND _213_ (
    .A(D1_out_synth[5]),
    .B(_107_),
    .Y(_020_)
  );
  NOT _214_ (
    .A(_020_),
    .Y(_021_)
  );
  NOR _215_ (
    .A(_090_),
    .B(_107_),
    .Y(_022_)
  );
  NOR _216_ (
    .A(_021_),
    .B(_022_),
    .Y(_023_)
  );
  NOR _217_ (
    .A(VC0_empty),
    .B(_023_),
    .Y(_024_)
  );
  NOR _218_ (
    .A(_019_),
    .B(_024_),
    .Y(_025_)
  );
  NOR _219_ (
    .A(_092_),
    .B(_025_),
    .Y(_001_[5])
  );
  NOR _220_ (
    .A(VC1[4]),
    .B(_083_),
    .Y(_026_)
  );
  NAND _221_ (
    .A(_098_),
    .B(_026_),
    .Y(_027_)
  );
  NAND _222_ (
    .A(VC0_empty),
    .B(_027_),
    .Y(_028_)
  );
  NOR _223_ (
    .A(D0_out_synth[0]),
    .B(_026_),
    .Y(_029_)
  );
  NOR _224_ (
    .A(_028_),
    .B(_029_),
    .Y(_030_)
  );
  NOR _225_ (
    .A(VC0[4]),
    .B(_091_),
    .Y(_031_)
  );
  NAND _226_ (
    .A(_086_),
    .B(pop_delay_VC0),
    .Y(_032_)
  );
  NOR _227_ (
    .A(_093_),
    .B(_031_),
    .Y(_033_)
  );
  NOR _228_ (
    .A(_085_),
    .B(_032_),
    .Y(_034_)
  );
  NOR _229_ (
    .A(_033_),
    .B(_034_),
    .Y(_035_)
  );
  NOR _230_ (
    .A(VC0_empty),
    .B(_035_),
    .Y(_036_)
  );
  NOR _231_ (
    .A(_030_),
    .B(_036_),
    .Y(_037_)
  );
  NOR _232_ (
    .A(_092_),
    .B(_037_),
    .Y(_000_[0])
  );
  NAND _233_ (
    .A(_078_),
    .B(_026_),
    .Y(_038_)
  );
  NAND _234_ (
    .A(VC0_empty),
    .B(_038_),
    .Y(_039_)
  );
  NOR _235_ (
    .A(D0_out_synth[1]),
    .B(_026_),
    .Y(_040_)
  );
  NOR _236_ (
    .A(_039_),
    .B(_040_),
    .Y(_041_)
  );
  NOR _237_ (
    .A(_094_),
    .B(_031_),
    .Y(_042_)
  );
  NOR _238_ (
    .A(_087_),
    .B(_032_),
    .Y(_043_)
  );
  NOR _239_ (
    .A(_042_),
    .B(_043_),
    .Y(_044_)
  );
  NOR _240_ (
    .A(VC0_empty),
    .B(_044_),
    .Y(_045_)
  );
  NOR _241_ (
    .A(_041_),
    .B(_045_),
    .Y(_046_)
  );
  NOR _242_ (
    .A(_092_),
    .B(_046_),
    .Y(_000_[1])
  );
  NAND _243_ (
    .A(_080_),
    .B(_026_),
    .Y(_047_)
  );
  NAND _244_ (
    .A(VC0_empty),
    .B(_047_),
    .Y(_048_)
  );
  NOR _245_ (
    .A(D0_out_synth[2]),
    .B(_026_),
    .Y(_049_)
  );
  NOR _246_ (
    .A(_048_),
    .B(_049_),
    .Y(_050_)
  );
  NOR _247_ (
    .A(_095_),
    .B(_031_),
    .Y(_051_)
  );
  NOR _248_ (
    .A(_088_),
    .B(_032_),
    .Y(_052_)
  );
  NOR _249_ (
    .A(_051_),
    .B(_052_),
    .Y(_053_)
  );
  NOR _250_ (
    .A(VC0_empty),
    .B(_053_),
    .Y(_054_)
  );
  NOR _251_ (
    .A(_050_),
    .B(_054_),
    .Y(_055_)
  );
  NOR _252_ (
    .A(_092_),
    .B(_055_),
    .Y(_000_[2])
  );
  NAND _253_ (
    .A(_081_),
    .B(_026_),
    .Y(_056_)
  );
  NAND _254_ (
    .A(VC0_empty),
    .B(_056_),
    .Y(_057_)
  );
  NOR _255_ (
    .A(D0_out_synth[3]),
    .B(_026_),
    .Y(_058_)
  );
  NOR _256_ (
    .A(_057_),
    .B(_058_),
    .Y(_059_)
  );
  NOR _257_ (
    .A(_096_),
    .B(_031_),
    .Y(_060_)
  );
  NOR _258_ (
    .A(_089_),
    .B(_032_),
    .Y(_061_)
  );
  NOR _259_ (
    .A(_060_),
    .B(_061_),
    .Y(_062_)
  );
  NOR _260_ (
    .A(VC0_empty),
    .B(_062_),
    .Y(_063_)
  );
  NOR _261_ (
    .A(_059_),
    .B(_063_),
    .Y(_064_)
  );
  NOR _262_ (
    .A(_092_),
    .B(_064_),
    .Y(_000_[3])
  );
  NAND _263_ (
    .A(VC0_empty),
    .B(_026_),
    .Y(_065_)
  );
  NAND _264_ (
    .A(_084_),
    .B(_031_),
    .Y(_066_)
  );
  NAND _265_ (
    .A(_065_),
    .B(_066_),
    .Y(_067_)
  );
  NAND _266_ (
    .A(reset_L),
    .B(D0_out_synth[4]),
    .Y(_068_)
  );
  NOR _267_ (
    .A(_067_),
    .B(_068_),
    .Y(_000_[4])
  );
  NAND _268_ (
    .A(_082_),
    .B(_026_),
    .Y(_069_)
  );
  NAND _269_ (
    .A(VC0_empty),
    .B(_069_),
    .Y(_070_)
  );
  NOR _270_ (
    .A(D0_out_synth[5]),
    .B(_026_),
    .Y(_071_)
  );
  NOR _271_ (
    .A(_070_),
    .B(_071_),
    .Y(_072_)
  );
  NOR _272_ (
    .A(_097_),
    .B(_031_),
    .Y(_073_)
  );
  NOR _273_ (
    .A(_090_),
    .B(_032_),
    .Y(_074_)
  );
  NOR _274_ (
    .A(_073_),
    .B(_074_),
    .Y(_075_)
  );
  NOR _275_ (
    .A(VC0_empty),
    .B(_075_),
    .Y(_076_)
  );
  NOR _276_ (
    .A(_072_),
    .B(_076_),
    .Y(_077_)
  );
  NOR _277_ (
    .A(_092_),
    .B(_077_),
    .Y(_000_[5])
  );
  (* src = "arbitro_mux_synth.v:8" *)
  DFF _278_ (
    .C(clk),
    .D(_000_[0]),
    .Q(D0_out_synth[0])
  );
  (* src = "arbitro_mux_synth.v:8" *)
  DFF _279_ (
    .C(clk),
    .D(_000_[1]),
    .Q(D0_out_synth[1])
  );
  (* src = "arbitro_mux_synth.v:8" *)
  DFF _280_ (
    .C(clk),
    .D(_000_[2]),
    .Q(D0_out_synth[2])
  );
  (* src = "arbitro_mux_synth.v:8" *)
  DFF _281_ (
    .C(clk),
    .D(_000_[3]),
    .Q(D0_out_synth[3])
  );
  (* src = "arbitro_mux_synth.v:8" *)
  DFF _282_ (
    .C(clk),
    .D(_000_[4]),
    .Q(D0_out_synth[4])
  );
  (* src = "arbitro_mux_synth.v:8" *)
  DFF _283_ (
    .C(clk),
    .D(_000_[5]),
    .Q(D0_out_synth[5])
  );
  (* src = "arbitro_mux_synth.v:8" *)
  DFF _284_ (
    .C(clk),
    .D(_001_[0]),
    .Q(D1_out_synth[0])
  );
  (* src = "arbitro_mux_synth.v:8" *)
  DFF _285_ (
    .C(clk),
    .D(_001_[1]),
    .Q(D1_out_synth[1])
  );
  (* src = "arbitro_mux_synth.v:8" *)
  DFF _286_ (
    .C(clk),
    .D(_001_[2]),
    .Q(D1_out_synth[2])
  );
  (* src = "arbitro_mux_synth.v:8" *)
  DFF _287_ (
    .C(clk),
    .D(_001_[3]),
    .Q(D1_out_synth[3])
  );
  (* src = "arbitro_mux_synth.v:8" *)
  DFF _288_ (
    .C(clk),
    .D(_001_[4]),
    .Q(D1_out_synth[4])
  );
  (* src = "arbitro_mux_synth.v:8" *)
  DFF _289_ (
    .C(clk),
    .D(_001_[5]),
    .Q(D1_out_synth[5])
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "logica_pops_synth.v:1" *)
module logica_pops_synth(VC0_empty, VC1_empty, D0_pause, D1_pause, clk, VC0_pop_synth, VC1_pop_synth, pop_delay_VC0, pop_delay_VC1);
  wire _0_;
  wire _1_;
  wire _2_;
  (* src = "logica_pops_synth.v:1" *)
  input D0_pause;
  (* src = "logica_pops_synth.v:1" *)
  input D1_pause;
  (* src = "logica_pops_synth.v:1" *)
  input VC0_empty;
  (* src = "logica_pops_synth.v:2" *)
  output VC0_pop_synth;
  (* src = "logica_pops_synth.v:1" *)
  input VC1_empty;
  (* src = "logica_pops_synth.v:2" *)
  output VC1_pop_synth;
  (* src = "logica_pops_synth.v:1" *)
  input clk;
  (* src = "logica_pops_synth.v:2" *)
  output pop_delay_VC0;
  (* src = "logica_pops_synth.v:2" *)
  output pop_delay_VC1;
  NOR _3_ (
    .A(D0_pause),
    .B(D1_pause),
    .Y(_1_)
  );
  NOT _4_ (
    .A(_1_),
    .Y(_2_)
  );
  NOR _5_ (
    .A(VC0_empty),
    .B(_2_),
    .Y(VC0_pop_synth)
  );
  NAND _6_ (
    .A(VC0_empty),
    .B(_1_),
    .Y(_0_)
  );
  NOR _7_ (
    .A(VC1_empty),
    .B(_0_),
    .Y(VC1_pop_synth)
  );
  (* src = "logica_pops_synth.v:4" *)
  DFF _8_ (
    .C(clk),
    .D(VC0_pop_synth),
    .Q(pop_delay_VC0)
  );
  (* src = "logica_pops_synth.v:4" *)
  DFF _9_ (
    .C(clk),
    .D(VC1_pop_synth),
    .Q(pop_delay_VC1)
  );
endmodule
